// internal/oidc/block_b313.go — B313 (v1.5.78): ONE renderer for the headscale-side
// `oidc:` block.
//
// WHY: the block used to be rendered only by `skygate oidc-export` (cmd/skygate), which
// the operator had to run by hand on the host — the panel could show it but not apply
// it. B313 turns the apply into a privileged request (the same split as the policy
// applier: the panel writes DATA, a root-owned helper performs the write and the
// restart), and a request that carries a pre-rendered block cannot drift from what
// `oidc-export` prints, because both now call this function. The batch of tests that
// pinned the exporter's output keeps pinning it through the delegation.
package oidc

import "strings"

// HeadscaleBlockValues is what the block needs. SecretSet is explicit so an unset
// secret renders the documented placeholder instead of an empty line (headscale would
// start without OIDC and the operator would see "nothing happened").
type HeadscaleBlockValues struct {
	Issuer       string
	ClientID     string
	ClientSecret string
	RedirectURIs string
	SecretSet    bool
}

// RenderHeadscaleBlock renders the `oidc:` section headscale expects, in the exact
// shape `skygate oidc-export --headscale [--secret]` has always printed.
func RenderHeadscaleBlock(v HeadscaleBlockValues, withSecret bool) string {
	redirect := FirstRedirectURI(v.RedirectURIs)
	secret := "<set-on-headscale-side>"
	if v.SecretSet && withSecret {
		secret = v.ClientSecret
	}
	suffix := ""
	if withSecret {
		suffix = " --secret"
	}
	var b strings.Builder
	b.WriteString("# headscale config — OIDC block generated by `skygate oidc-export --headscale" + suffix + "`\n")
	b.WriteString("oidc:\n")
	b.WriteString("  issuer: " + v.Issuer + "\n")
	b.WriteString("  client_id: " + v.ClientID + "\n")
	b.WriteString("  client_secret: " + secret + "\n")
	b.WriteString("  scope: [openid, profile, email]\n")
	b.WriteString("  extra_params:\n")
	b.WriteString("    domain: client_id\n")
	b.WriteString("  allowed_domains:\n")
	b.WriteString("    - " + HostOrPlaceholder(redirect) + "\n")
	b.WriteString("  auto_update: true\n")
	b.WriteString("  strip_email_domain: true\n")
	return b.String()
}

// FirstRedirectURI returns the first entry of the comma-separated allowlist.
func FirstRedirectURI(redirects string) string {
	for _, part := range strings.Split(redirects, ",") {
		if p := strings.TrimSpace(part); p != "" {
			return p
		}
	}
	return ""
}

// HostOrPlaceholder turns "https://head.example.com/oidc/callback" into
// "head.example.com" for allowed_domains, and keeps a placeholder when there is nothing
// to derive — an empty allowed_domains makes headscale reject every login.
func HostOrPlaceholder(redirect string) string {
	r := strings.TrimSpace(redirect)
	if r == "" {
		return "head.example.com"
	}
	r = strings.TrimPrefix(r, "https://")
	r = strings.TrimPrefix(r, "http://")
	if i := strings.IndexAny(r, "/?#"); i >= 0 {
		r = r[:i]
	}
	if i := strings.Index(r, ":"); i > 0 {
		r = r[:i]
	}
	if strings.TrimSpace(r) == "" {
		return "head.example.com"
	}
	return r
}
