// Code generated by split_i18n.py — refactor-v0.30 Phase C.
// DO NOT EDIT THIS FILE BY HAND — run scripts/split_i18n.py to
// regenerate from the per-feature files.
//
// i18n catalog: maps a top-level prefix (app, nav, bot, ...) to
// a package-level map of (key, translated-string). The New()
// function below merges every per-feature map into the
// translations table; the per-feature maps are declared in
// catalog_<feature>.go in the same package.
//
// refactor-v0.30 Phase C (2026-07-29): the previous single
// catalog.go file (4260 lines, 3782 keys RU+EN) was split
// into 12 per-feature files for navigability. The
// translation contract (T(lang, key) → string) is unchanged.
// Tests that previously read ruCatalog / enCatalog directly
// (TestCatalogsParity, TestPlaceholderOrder, TestHTMLSafeCatalog)
// now build the catalog via New() and inspect the merged
// result — the tests work the same way, but the source
// data is split by feature.

package i18n

// perFeatureRU + perFeatureEN list every per-feature map the
// glue needs to merge. New() iterates these and combines the
// entries into the translations table. Keep in lockstep with
// the per-feature files (catalog_<feature>.go) — if you add
// a new catalog_<feature>.go file, append its maps to BOTH
// slices below.

var perFeatureRU = []map[string]string{
	ruCommon,
	ruMy,
	ruAdmin,
	ruExitRules,
	ruExitNodes,
	ruDerp,
	ruBackup,
	ruUserSubnet,
	ruTelegram,
	ruTailscale,
	ruHelp,
	ruBot,
	ruUpdate,
}

var perFeatureEN = []map[string]string{
	enCommon,
	enMy,
	enAdmin,
	enExitRules,
	enExitNodes,
	enDerp,
	enBackup,
	enUserSubnet,
	enTelegram,
	enTailscale,
	enHelp,
	enBot,
	enUpdate,
}

// mergeMaps concatenates N maps into a single map.
// Used by New() to flatten the per-feature maps into one
// RU + one EN map keyed by translation key.
func mergeMaps(maps ...map[string]string) map[string]string {
	out := make(map[string]string)
	for _, m := range maps {
		for k, v := range m {
			out[k] = v
		}
	}
	return out
}
