// Code generated by split_i18n.py — refactor-v0.30 Phase C.
// DO NOT EDIT THIS FILE BY HAND — run scripts/split_i18n.py to
// regenerate from the source-of-truth (catalog_common.go etc.)
//
// Per-feature i18n keys for the update feature. The keys are
// declared as package-level maps; the glue file (i18n.go)
// merges them in New().

package i18n

// update feature — 44 ru keys, 44 en keys.
// Top-level prefixes: update

var ruUpdate = map[string]string{
	"update.banner_title"          : "Доступно обновление",
	"update.banner_body"           : "Запущена %s, на GitHub есть %s.",
	"update.banner_checked"        : "проверено: %s",
	"update.banner_open"           : "Открыть релиз",
	"update.subtitle"              : "Фоновая проверка GitHub Releases каждые 24ч. Показывает последнюю доступную версию и команды для безопасного апгрейда.",
	"update.check_now"             : "Проверить сейчас",
	"update.current_label"         : "Текущая",
	"update.latest_label"          : "Последняя",
	"update.install_label"         : "Установка",
	"update.channel"               : "Канал",
	"update.checked_at"            : "Проверено",
	"update.error_prefix"          : "GitHub недоступен",
	"update.release_notes"         : "Описание релиза",
	"update.view_on_github"        : "Полное описание на GitHub",
	"update.manual_steps_title"    : "Ручные шаги",
	"update.manual_steps_subtitle" : "Команды для обновления",
	"update.copy_to_clipboard"     : "Скопировать",
	"update.verify_after"          : "После — проверь",
	"update.rollback_title"        : "Откат",
	"update.rollback_subtitle"     : "Если новая версия сломалась — вернуться на предыдущую",
	"update.disabled"              : "Авто-проверка обновлений отключена (SKYGATE_UPDATE_CHECK=false).",
	"update.banner_new_version"    : "Доступна новая версия!",
	"update.banner_jump_to_steps"  : "Перейти к шагам",
	"update.banner_dev_build"      : "Сборка для разработки",
	"update.banner_dev_build_hint" : "Включён SKYGATE_DEV_BUILD — автообновление отключено. Сверка с GitHub возможна через «Проверить сейчас», но версия на GitHub устаревшая, обновление не требуется.",
	"update.apply"                 : "Обновить",
	"update.apply_confirm"         : "Запустить авто-обновление? Это перезапустит контейнер (3-5 минут). При любой ошибке — авто-откат на текущую версию.",
	"update.push"                  : "Протолкнуть обновление",
	"update.push_help"             : "Запустить оркестратор обновления вручную (независимо от флага auto-update). Используйте если хотите принудительно пересобрать и перезапустить текущую сборку.",
	"update.push_confirm"          : "Запустить оркестратор обновления вручную? Это перезапустит контейнер (3-5 минут). При любой ошибке — авто-откат.",
	"update.auto_disabled_banner"  : "Авто-обновление отключено (SKYGATE_AUTO_UPDATE_ENABLED=false). Чтобы применить обновление — нажмите «Протолкнуть обновление» ниже.",
	"update.auto_enabled_banner"   : "Авто-обновление включено (SKYGATE_AUTO_UPDATE_ENABLED=true). При появлении новой версии — кнопка «Обновить» появится ниже.",
	"update.auto_toggle_on"        : "Включить авто-обновление",
	"update.auto_toggle_off"       : "Отключить авто-обновление",
	"update.rollback_now"          : "Откатить сейчас",
	"update.dismiss"               : "Скрыть",
	"update.status_title"          : "Статус обновления",
	"update.status_job"            : "Job",
	"update.log_entries"           : "Записей в логе",
	"update.failure"               : "Ошибка",
	"update.manual_fallback_hint"  : "Авто-обновление провалилось. Ниже — ручные шаги для восстановления.",
	"update.auto_apply_pending"    : "Авто-обновление запущено. Страница перезагрузится через 5 секунд.",
	"update.auto_apply_queued"     : "Задача поставлена в очередь",
	"update.auto_dismissed"        : "Статус обновления сброшен",
	"update.auto_rolled_back"      : "Запущен откат",
	"update.phase_backup"          : "Резервная копия",
	"update.phase_pull_build"      : "Загрузка и сборка",
	"update.phase_migrate"         : "Миграции",
	"update.phase_swap"            : "Подмена контейнера",
	"update.phase_verify"          : "Проверка",
	"update.phase_done"            : "Готово",
	"update.phase_failed"          : "Провалено",
	"update.phase_rolled_back"     : "Откачено",
	// 2026-08-18 (B129): the new "Schedule" section on
	// /admin/update. Replaces the pre-B129 auto-update
	// banner (which was misleading — it claimed "auto-update
	// is on" but the operator still had to click "Apply" to
	// run the orchestrator). Post-B129 the schedule is the
	// REAL auto-update mechanism: a time-of-day HH:MM at
	// which the background scheduler (B130) triggers the
	// orchestrator.
	"update.schedule_title"        : "Расписание автообновления",
	"update.schedule_subtitle"     : "Skygate сам выполнит обновление в указанное время, если вышла новая версия. По умолчанию — выключено.",
	"update.schedule_enabled"      : "Включить расписание",
	"update.schedule_time_label"   : "Время (HH:MM, 24-часовой формат)",
	"update.schedule_save"         : "Сохранить расписание",
	"update.schedule_last_run"     : "Последний запуск",
	"update.schedule_never"        : "ни разу",
	"update.schedule_saved"        : "Расписание сохранено",
	"update.schedule_fallback"     : "Некорректное время — использовано значение по умолчанию (03:00).",
	"update.schedule_next_run"     : "Следующий запуск",
	"update.section_settings"      : "Параметры",
}

var enUpdate = map[string]string{
	"update.banner_title"          : "Update available",
	"update.banner_body"           : "Running %s, GitHub has %s.",
	"update.banner_checked"        : "checked: %s",
	"update.banner_open"           : "Open release",
	"update.subtitle"              : "Background service polls GitHub Releases every 24h. Shows the latest available version and the copy-pasteable commands for a safe upgrade.",
	"update.check_now"             : "Check now",
	"update.current_label"         : "Current",
	"update.latest_label"          : "Latest",
	"update.install_label"         : "Install",
	"update.channel"               : "channel",
	"update.checked_at"            : "Checked",
	"update.error_prefix"          : "GitHub unreachable",
	"update.release_notes"         : "Release notes",
	"update.view_on_github"        : "Full release notes on GitHub",
	"update.manual_steps_title"    : "Manual steps",
	"update.manual_steps_subtitle" : "Commands to upgrade",
	"update.copy_to_clipboard"     : "Copy",
	"update.verify_after"          : "After — verify",
	"update.rollback_title"        : "Rollback",
	"update.rollback_subtitle"     : "If the new version breaks something — revert to the previous one",
	"update.disabled"              : "Update checking is disabled (SKYGATE_UPDATE_CHECK=false).",
	"update.banner_new_version"    : "New version available!",
	"update.banner_jump_to_steps"  : "Jump to steps",
	"update.banner_dev_build"      : "Development build",
	"update.banner_dev_build_hint" : "SKYGATE_DEV_BUILD is enabled — auto-update is disabled. You can still compare against GitHub via \"Check now\", but the GitHub version is outdated; no update is needed.",
	"update.apply"                 : "Apply",
	"update.apply_confirm"         : "Start the auto-update? This will restart the container (3-5 minutes). On any failure — automatic rollback to the current version.",
	"update.push"                  : "Push update",
	"update.push_help"             : "Manually trigger the update orchestrator (independent of the auto-update flag). Use this to force a rebuild + restart of the current build, e.g. after a failed auto-apply.",
	"update.push_confirm"          : "Manually trigger the update orchestrator? This will restart the container (3-5 minutes). On any failure — automatic rollback.",
	"update.auto_disabled_banner"  : "Auto-update is disabled (SKYGATE_AUTO_UPDATE_ENABLED=false). To apply an update, click \"Push update\" below — it works regardless of the flag.",
	"update.auto_enabled_banner"   : "Auto-update is enabled (SKYGATE_AUTO_UPDATE_ENABLED=true). When a newer release is detected, the \"Update\" button appears below for one-click apply.",
	"update.auto_toggle_on"        : "Enable auto-update",
	"update.auto_toggle_off"       : "Disable auto-update",
	"update.rollback_now"          : "Rollback now",
	"update.dismiss"               : "Dismiss",
	"update.status_title"          : "Update status",
	"update.status_job"            : "Job",
	"update.log_entries"           : "log entries",
	"update.failure"               : "Failure",
	"update.manual_fallback_hint"  : "Auto-update failed. Below — manual steps to recover.",
	"update.auto_apply_pending"    : "Auto-update started. Page will reload in 5 seconds.",
	"update.auto_apply_queued"     : "Job queued",
	"update.auto_dismissed"        : "Update status dismissed",
	"update.auto_rolled_back"      : "Rollback triggered",
	"update.phase_backup"          : "Backup",
	"update.phase_pull_build"      : "Pull & build",
	"update.phase_migrate"         : "Migrations",
	"update.phase_swap"            : "Container swap",
	"update.phase_verify"          : "Verify",
	"update.phase_done"            : "Done",
	"update.phase_failed"          : "Failed",
	"update.phase_rolled_back"     : "Rolled back",
	// 2026-08-18 (B129): the new "Schedule" section on
	// /admin/update. Replaces the pre-B129 auto-update
	// banner (which was misleading - it claimed "auto-update
	// is on" but the operator still had to click "Apply" to
	// run the orchestrator). Post-B129 the schedule is the
	// REAL auto-update mechanism: a time-of-day HH:MM at
	// which the background scheduler (B130) triggers the
	// orchestrator.
	"update.schedule_title"        : "Schedule auto-update",
	"update.schedule_subtitle"     : "Skygate will run the update orchestrator at the specified time if a newer release is available. Default - off.",
	"update.schedule_enabled"      : "Enable schedule",
	"update.schedule_time_label"   : "Time (HH:MM, 24-hour format)",
	"update.schedule_save"         : "Save schedule",
	"update.schedule_last_run"     : "Last run",
	"update.schedule_never"        : "never",
	"update.schedule_saved"        : "Schedule saved",
	"update.schedule_fallback"     : "Invalid time - fell back to default (03:00).",
	"update.schedule_next_run"     : "Next run",
	"update.section_settings"      : "Settings",
}
