// Code generated by split_i18n.py — refactor-v0.30 Phase C.
// DO NOT EDIT THIS FILE BY HAND — run scripts/split_i18n.py to
// regenerate from the source-of-truth (catalog_common.go etc.)
//
// Per-feature i18n keys for the exit_rules feature. The keys are
// declared as package-level maps; the glue file (i18n.go)
// merges them in New().

package i18n

// exit_rules feature — 144 ru keys, 144 en keys.
// Top-level prefixes: exit_rules, exit_rules_admin, exit_rules_nodes, cleanup

var ruExitRules = map[string]string{
	"exit_rules.title":                  "Exit Rules",
	"exit_rules.subtitle":               "Избирательная маршрутизация трафика через exit-узлы Tailscale",
	"exit_rules.dns_autoupdate":         "DNS auto-update",
	"exit_rules.dns_autoupdate_title":   "DNS auto-update каждые 5m",
	"exit_rules.api_help_btn":           "API / AI-помощник",
	"exit_rules.client_win_guide":       "Windows",
	"exit_rules.client_win_guide_title": "Полный гайд по настройке Tailscale на Windows (authkey, login-server, exit-node, метрики маршрутов)",
	"exit_rules.add_rule":               "Добавить правило",
	"exit_rules.add_rule_title":         "Добавить правило",
	"exit_rules.added_ok":               "Правило добавлено — ACL обновлён, exit-node синхронизирован",
	"exit_rules.partial":                "Часть IP уже были в правилах — добавлены только новые",
	// 2026-09-07 (B237.19): form-error flash banner
	// shown above the form when the form's POST handler
	// rejects the values (invalid IP, limit exceeded,
	// device not owned, etc.). Pre-fix this was a giant
	// plain-text page from http.Error; post-fix the
	// handler redirects back with ?err= and the template
	// shows the message here so the user can fix + retry
	// without losing their form values.
	"exit_rules.form_error": "Не удалось добавить правило: %s",
	// 2026-09-07 (B237.19): the previous wording
	// ("Правило для X уже существует — не дублируем. Удалите
	//  существующее, если нужно обновить.") sounded like an
	// error and was easy to misread as "the new rule failed
	// to add". The reality: a domain rule DNS-resolves into
	// /32 rules; the SECOND add of the same domain hits the
	// existing /32 dedup (because the /32 for the resolved
	// IP is already there from the first add). The new rule
	// was never created — the user is seeing the OLD rule
	// in the list, and the banner is just confirming "this
	// domain is already covered". Reworded to make that
	// clearer: "Domain already covered" + the existing rule
	// link, no scary "delete to update" hint (the autoupdater
	// handles updates; the user doesn't need to delete).
	"exit_rules.duplicate":          "Домен %s уже покрыт правилом — автообновление будет поддерживать его актуальность.",
	"exit_rules.duplicate_blocking": "Уже покрытый IP:",
	"exit_rules.duplicate_parent":   "Источник:",
	"exit_rules.duplicate_view":     "→ перейти к правилу #%d",
	"exit_rules.dns_pending":        "Домен добавлен, но DNS пока не отвечает: %s. Autoupdater попробует при следующем цикле (до 5 минут).",
	"exit_rules.deleted":            "Правило удалено",
	// 2026-08-06: preferred-mismatch cross-check (v0.33.1.16
	// Cloudflare CIDR debug). Surfaces the count of rules
	// that point at a non-preferred exit-node — those rules
	// are silently ignored by Tailscale.
	"exit_rules.preferred_mismatch_banner": "%d правил ссылаются на exit-node, который устройство не использует. Правила сохранены, но Tailscale их игнорирует.",
	"exit_rules.use_preferred_btn":         "Use preferred (%s)",
	// B277.3: bulk-apply the user's preferred exit-node to every
	// mismatched rule in one click. %d = mismatch count, %s = preferred.
	"exit_rules.apply_preferred_btn":      "Применить preferred (%s) к %d правил(ам)",
	"exit_rules.apply_preferred_confirm":  "Будет обновлено %d правил(а): их exit_node_id изменится на «%s». Продолжить?",
	"exit_rules.preferred_col":            "Preferred",
	"exit_rules.preferred_match_title":    "Rule's exit-node matches the device's preferred exit-node (%s) — rule will take effect.",
	"exit_rules.preferred_mismatch_title": "Rule's exit-node differs from the device's preferred exit-node (%s) — Tailscale will ignore this rule.",
	"exit_rules.preferred_none_title":     "No preferred exit-node set for this device — Tailscale picks by metrics, rule may or may not apply.",
	// B277.4: auto-mode status — the rule's exit_node_id is
	// empty, the engine picks a healthy relay on the next tick.
	// NOT a mismatch; the badge is informational ("the engine
	// will handle this").
	"exit_rules.auto_pending_title": "Правило в режиме auto — движок подберёт здоровый relay на следующем тике. Это не mismatch.",
	// v1.5.43: pagination.
	"exit_rules.prev_page":          "Предыдущая",
	"exit_rules.next_page":          "Следующая",
	"exit_rules.page_size":          "На странице:",
	"exit_rules.pagination_page_of": "Страница %d из %d",
	"exit_rules.pagination_total":   "всего %d правил",
	// 2026-08-25 (B182): user-scope mirror of the admin
	// B182 keys. ⏳ means the rule's target CIDR is NOT in
	// headscale ApprovedRoutes yet — the autoupdater will
	// push on the next 5-min tick. See the B182 commit
	// message for why this is a separate state from "✅
	// preferred matches" (B178 alone was misleading).
	"exit_rules.approved_in_headscale_title": "Target approved in headscale for %s — rule is working.",
	"exit_rules.pending_in_headscale_title":  "Rule's exit-node matches the device's preferred, but headscale has NOT approved %s (target %s) yet. The autoupdater will push on the next 5-min tick.",
	"exit_rules.device":                      "Устройство",
	"exit_rules.device_hint":                 "Устройство, для которого применяется правило. Видны только ваши устройства. Пункт «все мои устройства» создаёт то же правило для каждого вашего устройства.",
	"exit_rules.exit_node":                   "Exit node (выходной узел)",
	"exit_rules.exit_node_auto":              "авто — skygate выберет",
	"exit_rules.device_all":                  "все мои устройства",
	"exit_rules.all_devices_badge":           "все мои устройства",
	"exit_rules.all_devices_badge_tip":       "Правило сохранено для всех ваших устройств: skygate пересоздаёт его для каждого устройства, которое появляется у вас позже (и снимает вместе с правилом). Иначе правило действовало бы только на те устройства, что были у вас в момент сохранения.",
	// B276.2: dedicated ALL-DEVICES section on /my/exit-rules.
	"exit_rules.all_devices_section_title": "Правила для всех устройств",
	"exit_rules.all_devices_section_help":  "применяются ко всем вашим устройствам, включая те, что появятся позже",
	"exit_rules.all_devices_fanout_badge":  "применено к %d устройств(ам)",
	"exit_rules.all_devices_fanout_tip":    "Это правило развёрнуто на каждое ваше устройство (сейчас и в будущем) — копии хранятся в device_rules с разными device_id, но логически это одно правило.",
	"exit_rules.exit_node_hint":            "Необязательно. Не выбрано — skygate сам назначит exit-узел (по нагрузке) и покажет владельца префикса в /admin/exit-nodes, где его можно закрепить. Выбранный узел — пожелание: если сеть обслуживает другой узел, пин в ACL следует за владельцем, иначе сайт у устройства просто не откроется.",
	"exit_rules.action":                    "Действие",
	"exit_rules.action_accept":             "✅ Allow — разрешить доступ",
	"exit_rules.action_deny":               "🚫 Deny — отбрасывать трафик",
	"exit_rules.action_hint":               "Allow: трафик к цели идёт через exit-node. Deny: трафик к цели отбрасывается на уровне ACL.",
	"exit_rules.target_type":               "Тип цели",
	"exit_rules.target_type_ip":            "IP адрес (например 1.2.3.4)",
	"exit_rules.target_type_subnet":        "Подсеть (например 10.0.0.0/24)",
	"exit_rules.target_type_domain":        "Домен (например example.com)",
	"exit_rules.target_type_hint":          "IP/подсеть — участвуют в advertised-routes и работают для split-туннеля. Домен — только ACL (не влияет на маршрутизацию).",
	"exit_rules.target_value":              "Значение",
	"exit_rules.target_value_ph":           "1.2.3.4 или 10.0.0.0/24 или example.com",
	"exit_rules.submit":                    "Добавить правило",
	"exit_rules.clear":                     "Очистить",
	"exit_rules.no_devices":                "— нет устройств —",
	"exit_rules.no_exit_nodes":             "— нет exit nodes —",
	"exit_rules.scripts_title":             "Скрипты маршрутизации",
	"exit_rules.scripts_sub":               "Для Linux (резервный способ). Windows — используйте tailscale up --accept-routes.",
	"exit_rules.col_device":                "Устройство",
	"exit_rules.col_rules":                 "Правил",
	"exit_rules.col_linux_script":          "Linux скрипт",
	"exit_rules.col_restore":               "Откат",
	"exit_rules.current_rules":             "Текущие правила (%d)",
	"exit_rules.select_all":                "Выбрать все",
	"exit_rules.selected":                  "Выбрано:",
	"exit_rules.filter_type":               "Все типы",
	"exit_rules.filter_domain":             "Только домены",
	"exit_rules.filter_subnet":             "Только /32",
	"exit_rules.filter_ip":                 "Только IP",
	"exit_rules.search_ph":                 "Поиск по IP/домену...",
	"exit_rules.cascade_hint":              "Домен → каскад /32",
	"exit_rules.cascade_hint_title":        "Удаление домена каскадно удалит все связанные /32",
	"exit_rules.confirm_multi_delete":      "Удалить выбранные правила? Для доменов также удалятся все связанные /32, которые autoupdater создал.",
	"exit_rules.confirm_single_delete":     "Удалить правило?",
	"exit_rules.reset_filters":             "Сбросить фильтры",
	"exit_rules.delete_selected":           "Удалить выбранные",
	"exit_rules.user_facing":               "Мои правила: %d/%d",
	"exit_rules.user_facing_title":         "Только ваши правила (без учёта /32, которые autoupdater создаёт для доменов)",
	"exit_rules.system":                    "Системная: %d%% (%d/%d)",
	"exit_rules.system_title":              "Системный счётчик (по всем пользователям). Обычно это не требуется.",
	"exit_rules.how_title":                 "Как это работает",
	"exit_rules.how_li1":                   "Skygate хранит все правила в <code>device_rules</code> (одна запись = одна подсеть/домен/IP для одного устройства).",
	"exit_rules.how_li2":                   "При добавлении/удалении правила skygate автоматически пушит маршруты на выбранный exit-node (relay-1/2/3) через SSH + headscale API.",
	"exit_rules.how_li3":                   "Exit-node анонсирует свой полный набор CIDR-ов в headscale (<code>tailscale set --advertise-routes=...</code>). Headscale раздаёт их клиентам по ACL.",
	"exit_rules.how_li4":                   "Клиент только получает маршруты через <code>--accept-routes</code>. Никаких скриптов, <code>route add</code> или .bat/.sh на устройстве не нужно — Tailscale сам ставит маршруты на уровне ядра.",
	"exit_rules.how_li5":                   "Exit-node выбирается в трее Tailscale → Exit node → relay-1/2/3. Весь трафик до whitelist-подсетей идёт через выбранный узел, остальное — напрямую (split-tunnel).",
	"exit_rules.how_li3_win":               "Windows/Linux: tailscale up --accept-routes --accept-dns=false. Exit-node выбирается в Tailscale-меню, маршруты приходят автоматически.",
	"exit_rules.how_li3_mobile":            "Android/iOS: tailscale up --exit-node=<имя> (мобильные не поддерживают split-туннель)",
	"exit_rules.win_flow_title":            "Windows: 3 шага",
	"exit_rules.win_flow_li1":              "<b>На этой странице</b>: выберите устройство, exit-node (relay-1/2/3), тип (IP/подсеть/домен), значение → «Добавить».",
	"exit_rules.win_flow_li2":              "Skygate автоматически пушит маршрут на relay через SSH. Дальше relay анонсирует его в headscale (занимает ~5 сек).",
	"exit_rules.win_flow_li3":              "На Windows-устройстве: <code>tailscale up --login-server=https://head.example.com --authkey=tskey-auth-... --accept-routes --accept-dns=false</code> (authkey — в /my/preauth). Потом в трее Tailscale → Exit node → выберите relay. Готово.",
	"exit_rules.win_flow_no_scripts":       "Никаких <code>route add</code>, .bat/.sh или ручных манипуляций — Tailscale получает маршруты через netmap push и сам ставит их в Windows routing table.",
	"exit_rules.quick_title":               "Быстрый старт",
	"exit_rules.quick_li1":                 "Выберите устройство и exit-node",
	"exit_rules.quick_li2":                 "Укажите тип и значение цели",
	"exit_rules.quick_li3":                 "Нажмите «Добавить»",
	"exit_rules.quick_li4":                 "На устройстве: tailscale up --accept-routes --accept-dns=false (полный setup — см. /my/exit-rules/help, раздел Windows)",
	"exit_rules.client_title":              "Подключение клиента",
	"exit_rules.client_win_linux":          "Windows / Linux",
	"exit_rules.client_mobile":             "Android / iOS",
	"exit_rules.client_win_cmd":            "tailscale up --login-server=https://head.example.com --authkey=<key> --accept-routes --accept-dns=false",
	"exit_rules.client_win_cmd_after":      "tailscale up --accept-routes --accept-dns=false",
	"exit_rules.client_win_hint":           "<code>--authkey</code> берите в /my/preauth (одноразовый). После первой регистрации повторно <code>--authkey</code> не нужен — хватит короткой команды. Exit-node выбирается в трее Tailscale → Exit node. Маршруты приходят автоматически через headscale ACL.",
	"exit_rules.client_split_hint":         "Split-туннель: whitelist-подсети идут через exit-node, остальное — напрямую. Tailscale сам ставит per-CIDR маршруты на уровне ядра, никаких ручных <code>route add</code>.",
	"exit_rules.client_full_hint":          "Полный туннель: весь трафик (0.0.0.0/0) уходит на exit-node. Избирательная маршрутизация на мобильных не поддерживается.",
	"exit_rules.important":                 "Важно",
	"exit_rules.important_li1":             "IP/подсеть — работает для split-туннеля (Windows/Linux).",
	"exit_rules.important_li2":             "Домен — только ACL-правило, не влияет на маршрутизацию.",
	"exit_rules.important_li3":             "После перезапуска Tailscale (tailscale down/up) выполните --accept-routes заново.",
	"exit_rules.important_li4":             "Правила изолированы: каждый пользователь управляет только своими устройствами.",
	"exit_rules.bulk_title":                "Массовое добавление",
	"exit_rules.bulk_desc":                 "Используйте AI-помощника (Hermes, Cline) для массового создания правил:",
	"exit_rules.bulk_example":              "«Добавь правила для my-laptop (device_id=5) через exit-node node-name: подсети Telegram, YouTube, Google»",
	"exit_rules.privacy_title":             "Приватность",
	"exit_rules.privacy_li1":               "Правила видны только вам и администратору.",
	"exit_rules.privacy_li2":               "Другие пользователи не видят ваши устройства и правила.",
	"exit_rules.privacy_li3":               "ACL гарантирует что advertised-маршруты раздаются только вашим устройствам.",
	"exit_rules.col_action":                "Действие",
	"exit_rules.col_target":                "Цель",
	"exit_rules.rules_count_suffix":        " правил",
	"exit_rules.exit_nodes_suffix":         " exit-nodes",
	"exit_rules.usage_warn":                "%d/%d (%d%%) — больше половины лимита per-device использовано.",
	"exit_rules.usage_danger":              "%d/%d (%d%%) — близко к лимиту per-device. Удалите ненужные правила или обратитесь к админу.",
	"exit_rules.usage_ok":                  "%d/%d (%d%%) — лимит per-device в порядке.",
	"exit_rules.usage_default":             "Устройство, для которого применяется правило. Видны только ваши устройства.",
	"exit_rules_admin.title":               "Exit Rules (admin)",
	"exit_rules_admin.subtitle":            "Все правила всех пользователей",
	"exit_rules_admin.user":                "Пользователь",
	"exit_rules_admin.device":              "Устройство",
	"exit_rules_admin.exit_node":           "Exit node",
	"exit_rules_admin.node_load":           "Загрузка узлов",
	"exit_rules_admin.reapply":             "Пере-применить ACL",
	"exit_rules_admin.reapply_confirm":     "Пере-применить ACL? Политика будет пересобрана из текущего состояния БД и отправлена в headscale. Используйте после изменений в GenerateACL().",
	"exit_rules_admin.rolled_back":         "ACL откачен",
	"exit_rules_admin.reapplied":           "ACL пере-применён",
	"exit_rules_admin.system_load":         "Загрузка системы",
	"exit_rules_admin.all_rules":           "Все правила (%d)",
	"exit_rules_admin.rules_count":         "%d правил",
	"exit_rules_admin.no_rules":            "Нет правил",
	"exit_rules_admin.col_action":          "Действие",
	"exit_rules_admin.col_type":            "Тип",
	"exit_rules_admin.col_resource":        "Ресурс",
	"exit_rules_admin.col_parent":          "Родитель",
	// 2026-08-06: admin-side preferred column + mismatch banner
	// (mirror of the user-scope ones).
	"exit_rules_admin.col_preferred":            "Preferred",
	"exit_rules_admin.preferred_match_title":    "Matches the device's preferred exit-node (%s).",
	"exit_rules_admin.preferred_mismatch_title": "Differs from the device's preferred exit-node (%s) — Tailscale will ignore this rule.",
	"exit_rules_admin.preferred_none_title":     "No preferred exit-node set.",
	// 2026-08-25 (B182): the new two-state ✅ / ⏳
	// preferred-exit-node badge. ✅ = rule's target CIDR is
	// APPROVED in headscale ApprovedRoutes for this
	// exit-node (the rule is fully working). ⏳ = rule
	// matches the device's preferred exit-node but
	// headscale has NOT approved the rule's target yet —
	// the autoupdater will push on the next 5-min tick, or
	// hit "Пере-синхронизировать" on /admin/exit-nodes.
	"exit_rules_admin.approved_in_headscale_title": "Target approved in headscale for %s — rule is working.",
	"exit_rules_admin.pending_in_headscale_title":  "Rule's exit-node matches the device's preferred, but headscale has NOT approved %s (target %s) yet. The autoupdater will push on the next 5-min tick (or hit 'Пере-синхронизировать' on /admin/exit-nodes).",
	"exit_rules_admin.preferred_mismatch_banner":   "%d rules across all users reference a non-preferred exit-node. Check the 'Preferred' column.",
	"exit_rules_admin.dead_rules_count":            "%d dead rule(s)",
	"exit_rules_admin.dead_rules_count_title":      "%d device_rule(s) for this device reference a non-preferred exit-node. Tailscale will ignore them. Open /admin/exit-rules to see which.",
	"exit_rules_admin.device_filter_banner":        "Отфильтровано по устройству %s — показано %d правил",
	"exit_rules_admin.device_filter_show_all":      "Показать все",
	"exit_rules_admin.col_created":                 "Создано",
	"exit_rules_admin.auto_managed":                "Авто-сопровождение",
	"exit_rules_admin.delete_confirm":              "Удалить правило #%d?",
	"exit_rules_admin.acl_history":                 "История применения ACL",
	"exit_rules_admin.col_time":                    "Время",
	"exit_rules_admin.col_details":                 "Детали",
	"exit_rules_admin.no_records":                  "Нет записей",
	"exit_rules_admin.sync_section":                "Синхронизация advertised-routes",
	"exit_rules_admin.sync_help":                   "Обновляет --advertise-routes на всех exit-узлах согласно текущим правилам.",
	"exit_rules_admin.sync":                        "Синхронизировать",
	"exit_rules_admin.sync_running":                "Синхронизация…",
	"exit_rules_admin.sync_done":                   "✓ Готово",
	"exit_rules_admin.sync_error":                  "✗ Ошибка",
	"exit_rules_admin.rollback_section":            "Откат ACL",
	"exit_rules_admin.col_version":                 "Версия",
	"exit_rules_admin.col_by":                      "Кем",
	"exit_rules_admin.col_status":                  "Статус",
	"exit_rules_admin.status_ok":                   "OK",
	"exit_rules_admin.status_err":                  "ОШИБКА",
	"exit_rules_admin.rollback":                    "Откатить",
	"exit_rules_admin.rollback_confirm":            "Откатить ACL к версии %d?",
	"exit_rules_admin.no_snapshots":                "Нет снапшотов",
	// 2026-09-11 (Issue #2 closure): admin add form.
	"exit_rules_admin.add_form_title":        "Добавить правило для устройства пользователя",
	"exit_rules_admin.add_form_user_id":      "ID пользователя (portal_users.id)",
	"exit_rules_admin.add_form_device_id":    "ID устройства (headscale node_id)",
	"exit_rules_admin.add_form_exit_node":    "Exit-node",
	"exit_rules_admin.add_form_target_type":  "Тип цели",
	"exit_rules_admin.add_form_target_value": "Значение (IP/CIDR/домен)",
	"exit_rules_admin.add_form_action":       "Действие",
	"exit_rules_admin.add_form_submit":       "Добавить правило",
	"exit_rules_admin.add_form_help":         "Создаёт правило от имени выбранного пользователя. headscale ACL src остаётся = владелец устройства.",
	"exit_rules_admin.add_form_applied":      "Правило добавлено",
	"cleanup.title":                          "Очистка",
	"cleanup.subtitle":                       "Слияние дубликатов device_id и удаление orphaned /32",
	"cleanup.duplicates":                     "Дублирующиеся device_id",
	"cleanup.orphans":                        "Orphaned /32 правила",
	"cleanup.merge":                          "Слить",
	"cleanup.merge_confirm":                  "Слить %d дублей?",
	"cleanup.delete_orphans":                 "Удалить orphan-ы",
	"cleanup.delete_orphans_confirm":         "Удалить %d orphan-правил?",
	"cleanup.col_total_rules":                "Всего правил",
	"cleanup.col_distinct_device_id":         "Уникальных device_id",
	"cleanup.col_distinct_hostname":          "Уникальных hostname",
	"cleanup.col_to_merge":                   "К слиянию",
	"cleanup.col_to_backfill_device_ip":      "К заполнению device_ip",
	"cleanup.col_stale_device_id":            "Устаревших device_id",
	"cleanup.col_hostname":                   "Имя хоста",
	"cleanup.col_canonical_device_id":        "Канонический device_id",
	"cleanup.col_all_device_id_in_group":     "Все device_id в группе",
	"cleanup.col_rules":                      "Правил",
	// 2026-09-20 (i18n-audit, раздел 1): страница /admin/exit-rules/cleanup
	// была наполовину английской (заголовок, подзаголовок, кнопки и
	// подтверждение необратимого действия).
	"cleanup.page_subtitle":    "Объединяет дубликаты по device_id и заполняет device_ip. Идемпотентно.",
	"cleanup.applied_flash":    "Применено. Пересчитано: объединено=%d, заполнено IP=%d.",
	"cleanup.plan_title":       "План",
	"cleanup.groups_title":     "Группы по hostname",
	"cleanup.unknown_hostname": "неизвестно",
	"cleanup.apply_confirm":    "Применить очистку? Это изменит device_id и device_ip у части правил, и без бэкапа откатить это нельзя.",
	"cleanup.apply_btn":        "Применить",
	"cleanup.recompute_btn":    "Пересчитать",
	// 2026-08-18 (B143, v1.4.3): in-app smoke-mesh
	// cleanup scheduler. The /admin/system_tests
	// page (post-TD-8) renders these — the cleanup
	// itself runs as a Go goroutine in
	// mesh.StartCleanupScheduler and emits a single
	// audit_log line per tick via
	// db.AppendExitRuleLog.
	"cleanup_smoke.run_btn":        "Очистить smoke-mesh",
	"cleanup_smoke.run_btn_help":   "Удалить все строки meshes с именем smoke-mesh-* и без mesh_members. Запускается немедленно (тот же путь, что и in-app cron).",
	"cleanup_smoke.last_run":       "Последняя очистка: %s",
	"cleanup_smoke.last_run_never": "Никогда",
	"cleanup_smoke.removed":        "Удалено %d smoke-mesh строк",
	"cleanup_smoke.no_rows":        "Мусор не найден",
	"cleanup_smoke.failed":         "Очистка не удалась: %s",
	// 2026-09-07 (B237.22 / TD-11): UI-only CDN-grouping
	// for the rules list. The "X диапазонов" badge
	// appears in the per-(host, exitNode) section header
	// when one of the rules has a parent_domain marker
	// (e.g. "cdn:cloudflare:discordapp.com"). See
	// cdn_group.go for the grouping contract.
	"exit_rules.cdn_group_count":     "%d диапазонов",
	"exit_rules_nodes.title":         "Exit-узлы (синхронизация)",
	"exit_rules_nodes.subtitle":      "Sync advertised-routes на exit-узлах",
	"exit_rules_nodes.sync":          "Синхронизировать",
	"exit_rules_nodes.syncing":       "Синхронизация...",
	"exit_rules_nodes.last_sync":     "Последняя синхронизация: %s",
	"exit_rules_nodes.col_name":      "Имя",
	"exit_rules_nodes.col_rules":     "Правил",
	"exit_rules_nodes.col_load":      "Загрузка",
	"exit_rules_nodes.col_available": "Доступно",
	"exit_rules_nodes.col_approved":  "Одобрено",
	"exit_rules_nodes.col_last_sync": "Последний sync",
	// 2026-09-20 (i18n-audit, раздел 1): страница /admin/exit-rules/nodes
	// была целиком на английском. Значения с разметкой рендерятся через safeHTML.
	"exit_rules_nodes.dashboard_title":       "Дашборд загрузки узлов",
	"exit_rules_nodes.load_metrics_subtitle": "Метрики загрузки exit-узлов",
	"exit_rules_nodes.exit_rules_link":       "Exit-правила",
	"exit_rules_nodes.system_load":           "Общая загрузка",
	"exit_rules_nodes.limit_hint":            "Лимит: SKYGATE_MAX_TOTAL_RULES=%d. При превышении пользователи получают 403.",
	"exit_rules_nodes.nodes_title":           "Exit-узлы (%d)",
	"exit_rules_nodes.colors_legend":         "<b>Цвета:</b> <span class=\"tag tag-success\">зелёный &lt; 50%</span> <span class=\"tag tag-warn\">жёлтый 50-80%</span> <span class=\"tag tag-danger\">красный &gt; 80%</span>.",
	"exit_rules_nodes.load_formula":          "Нагрузка = rules_on_node / (MaxTotalRules / 5). Если нагрузка &gt; 80% — добавление новых правил на этот узел может замедлить синхронизацию.",
	"exit_rules_nodes.recommendations":       "Рекомендации",
	"exit_rules_nodes.rec_green":             "🟢 <b>Зелёный (&lt;50%):</b> норма. Можно свободно добавлять правила.",
	"exit_rules_nodes.rec_yellow":            "🟡 <b>Жёлтый (50-80%):</b> средняя нагрузка. Следите за задержкой синхронизации.",
	"exit_rules_nodes.rec_red":               "🔴 <b>Красный (&gt;80%):</b> высокая нагрузка. Подумайте о переносе части правил на другой exit-узел или об уменьшении числа доменов (автообновление разрешает много IP).",
	"exit_rules_nodes.rec_staggered":         "⏱️ <b>Поэтапная синхронизация:</b> автообновление обновляет IP порциями (SKYGATE_STAGGER_BATCH_SIZE) с интервалом (SKYGATE_STAGGER_INTERVAL) — это не перегружает approve-routes в headscale.",
	"exit_rules_nodes.rec_last_sync":         "🔄 <b>Последняя синхронизация:</b> последняя успешная синхронизация этого узла. Если «никогда» — автообновление до него ещё не дошло.",
}

var enExitRules = map[string]string{
	"exit_rules.title":                  "Exit rules",
	"exit_rules.subtitle":               "Selective traffic routing through Tailscale exit nodes",
	"exit_rules.dns_autoupdate":         "DNS auto-update",
	"exit_rules.dns_autoupdate_title":   "DNS auto-update every 5m",
	"exit_rules.api_help_btn":           "API / AI helper",
	"exit_rules.client_win_guide":       "Windows",
	"exit_rules.client_win_guide_title": "Full Tailscale-on-Windows setup guide (authkey, login-server, exit-node, route metrics)",
	"exit_rules.add_rule":               "Add rule",
	"exit_rules.add_rule_title":         "Add rule",
	"exit_rules.added_ok":               "Rule added — ACL updated, exit node synced",
	"exit_rules.partial":                "Some IPs were already in rules — only new ones were added",
	// 2026-09-07 (B237.19): form-error flash banner
	// shown above the form when the form's POST handler
	// rejects the values. EN copy.
	"exit_rules.form_error": "Could not add rule: %s",
	// 2026-09-07 (B237.19): the previous wording
	// ("A rule for X already exists — not duplicating. Remove
	//  the existing one to update.") sounded like an error
	// and was easy to misread as "the new rule failed to add".
	// A domain rule DNS-resolves into /32 rules; the SECOND
	// add of the same domain hits the existing /32 dedup.
	// Reworded: "Domain already covered" + the existing rule
	// link, no scary "delete to update" hint (the autoupdater
	// handles updates; the user doesn't need to delete).
	"exit_rules.duplicate":          "Domain %s is already covered by an existing rule — the autoupdater will keep it current.",
	"exit_rules.duplicate_blocking": "Already-covered IP:",
	"exit_rules.duplicate_parent":   "Source:",
	"exit_rules.duplicate_view":     "→ jump to rule #%d",
	"exit_rules.dns_pending":        "Domain added, but DNS is not responding yet: %s. Autoupdater will retry on the next cycle (up to 5 minutes).",
	"exit_rules.deleted":            "Rule deleted",
	// 2026-08-06: preferred-mismatch cross-check (mirror of the
	// RU keys above).
	"exit_rules.preferred_mismatch_banner": "%d rules reference an exit-node that the device does not use. The rules are saved, but Tailscale ignores them.",
	"exit_rules.use_preferred_btn":         "Use preferred (%s)",
	// B277.3: bulk-apply the user's preferred exit-node to every
	// mismatched rule in one click. %d = mismatch count, %s = preferred.
	"exit_rules.apply_preferred_btn":      "Apply preferred (%s) to %d rule(s)",
	"exit_rules.apply_preferred_confirm":  "About to update %d rule(s): their exit_node_id will change to '%s'. Continue?",
	"exit_rules.preferred_col":            "Preferred",
	"exit_rules.preferred_match_title":    "Rule's exit-node matches the device's preferred exit-node (%s) — rule will take effect.",
	"exit_rules.preferred_mismatch_title": "Rule's exit-node differs from the device's preferred exit-node (%s) — Tailscale will ignore this rule.",
	"exit_rules.preferred_none_title":     "No preferred exit-node set for this device — Tailscale picks by metrics, rule may or may not apply.",
	// B277.4: auto-mode status — the rule's exit_node_id is
	// empty, the engine picks a healthy relay on the next tick.
	// NOT a mismatch; the badge is informational ("the engine
	// will handle this").
	"exit_rules.auto_pending_title": "Rule is in auto mode — the engine will pick a healthy relay on the next reconcile tick. Not a mismatch.",
	// v1.5.43: pagination.
	"exit_rules.prev_page":          "Previous",
	"exit_rules.next_page":          "Next",
	"exit_rules.page_size":          "Per page:",
	"exit_rules.pagination_page_of": "Page %d of %d",
	"exit_rules.pagination_total":   "total %d rules",
	// 2026-08-25 (B182): user-scope mirror of the admin
	// B182 keys. ⏳ means the rule's target CIDR is NOT in
	// headscale ApprovedRoutes yet — the autoupdater will
	// push on the next 5-min tick. See the B182 commit
	// message for why this is a separate state from "✅
	// preferred matches" (B178 alone was misleading).
	"exit_rules.approved_in_headscale_title": "Target approved in headscale for %s — rule is working.",
	"exit_rules.pending_in_headscale_title":  "Rule's exit-node matches the device's preferred, but headscale has NOT approved %s (target %s) yet. The autoupdater will push on the next 5-min tick.",
	"exit_rules.device":                      "Device",
	"exit_rules.device_hint":                 "The device this rule applies to. Only your devices are visible. \"All my devices\" creates the same rule for every device you own.",
	"exit_rules.exit_node":                   "Exit node",
	"exit_rules.exit_node_auto":              "auto — skygate picks",
	"exit_rules.device_all":                  "all my devices",
	"exit_rules.all_devices_badge":           "all my devices",
	"exit_rules.all_devices_badge_tip":       "Saved for all of your devices: skygate re-creates it on every device you register later (and removes it with the rule). Without this the rule would only cover the devices you owned when it was saved.",
	// B276.2: dedicated ALL-DEVICES section on /my/exit-rules.
	"exit_rules.all_devices_section_title": "Rules for all my devices",
	"exit_rules.all_devices_section_help":  "applied to every device you own now and to every device you register later",
	"exit_rules.all_devices_fanout_badge":  "applied to %d device(s)",
	"exit_rules.all_devices_fanout_tip":    "This rule is fanned out to every device you own (now and in the future) — the copies live in device_rules with different device_ids, but logically it is one rule.",
	"exit_rules.exit_node_hint":            "Optional. Left empty, skygate assigns the exit node itself (by load) and shows the prefix owner on /admin/exit-nodes, where it can be pinned. A selected node is a preference: if another node serves the network, the ACL pin follows the owner — otherwise the site simply would not open on that device.",
	"exit_rules.action":                    "Action",
	"exit_rules.action_accept":             "✅ Allow — permit access",
	"exit_rules.action_deny":               "🚫 Deny — drop traffic",
	"exit_rules.action_hint":               "Allow: traffic to the target goes through the exit node. Deny: traffic to the target is dropped at ACL level.",
	"exit_rules.target_type":               "Target type",
	"exit_rules.target_type_ip":            "IP address (e.g. 1.2.3.4)",
	"exit_rules.target_type_subnet":        "Subnet (e.g. 10.0.0.0/24)",
	"exit_rules.target_type_domain":        "Domain (e.g. example.com)",
	"exit_rules.target_type_hint":          "IP/subnet participate in advertised-routes and work for split-tunnel. Domain is ACL-only (does not affect routing).",
	"exit_rules.target_value":              "Value",
	"exit_rules.target_value_ph":           "1.2.3.4 or 10.0.0.0/24 or example.com",
	"exit_rules.submit":                    "Add rule",
	"exit_rules.clear":                     "Clear",
	"exit_rules.no_devices":                "— no devices —",
	"exit_rules.no_exit_nodes":             "— no exit nodes —",
	"exit_rules.scripts_title":             "Routing scripts",
	"exit_rules.scripts_sub":               "For Linux (fallback). On Windows use tailscale up --accept-routes.",
	"exit_rules.col_device":                "Device",
	"exit_rules.col_rules":                 "Rules",
	"exit_rules.col_linux_script":          "Linux script",
	"exit_rules.col_restore":               "Restore",
	"exit_rules.current_rules":             "Current rules (%d)",
	"exit_rules.select_all":                "Select all",
	"exit_rules.selected":                  "Selected:",
	"exit_rules.filter_type":               "All types",
	"exit_rules.filter_domain":             "Domains only",
	"exit_rules.filter_subnet":             "/32 only",
	"exit_rules.filter_ip":                 "IP only",
	"exit_rules.search_ph":                 "Search by IP/domain...",
	"exit_rules.cascade_hint":              "Domain → cascade /32",
	"exit_rules.cascade_hint_title":        "Deleting a domain cascades to all related /32",
	"exit_rules.confirm_multi_delete":      "Delete the selected rules? For domains, all related /32 created by autoupdater will also be removed.",
	"exit_rules.confirm_single_delete":     "Delete this rule?",
	"exit_rules.reset_filters":             "Reset filters",
	"exit_rules.delete_selected":           "Delete selected",
	"exit_rules.user_facing":               "My rules: %d/%d",
	"exit_rules.user_facing_title":         "Only your rules (excluding /32 that autoupdater creates for domains)",
	"exit_rules.system":                    "System: %d%% (%d/%d)",
	"exit_rules.system_title":              "System-wide counter (all users). Normally you don't need this.",
	"exit_rules.how_title":                 "How it works",
	"exit_rules.how_li1":                   "Skygate stores every rule in <code>device_rules</code> (one row = one subnet/domain/IP for one device).",
	"exit_rules.how_li2":                   "On add/remove skygate auto-pushes the route set to the chosen exit-node (relay-1/2/3) via SSH + headscale API.",
	"exit_rules.how_li3":                   "The exit-node advertises its full CIDR set to headscale (<code>tailscale set --advertise-routes=...</code>). Headscale distributes per ACL.",
	"exit_rules.how_li4":                   "The client only receives routes via <code>--accept-routes</code>. No client-side script, no <code>route add</code>, no .bat/.sh — Tailscale installs the routes at the kernel level.",
	"exit_rules.how_li5":                   "Pick an exit-node in Tailscale tray → Exit node → relay-1/2/3. Whitelisted destinations route through the chosen node, the rest goes direct (split-tunnel).",
	"exit_rules.how_li3_win":               "Windows/Linux: tailscale up --accept-routes --accept-dns=false. Exit-node is picked in the Tailscale menu; routes arrive automatically.",
	"exit_rules.how_li3_mobile":            "Android/iOS: tailscale up --exit-node=<name> (mobile does not support split-tunnel)",
	"exit_rules.win_flow_title":            "Windows: 3 steps",
	"exit_rules.win_flow_li1":              "<b>On this page</b>: pick the device, exit-node (relay-1/2/3), type (IP/subnet/domain), value → \"Add\".",
	"exit_rules.win_flow_li2":              "Skygate auto-pushes the route set to the relay over SSH. The relay advertises it to headscale (≈5s).",
	"exit_rules.win_flow_li3":              "On the Windows device: <code>tailscale up --login-server=https://head.example.com --authkey=tskey-auth-... --accept-routes --accept-dns=false</code> (authkey from /my/preauth). Then Tailscale tray → Exit node → relay. Done.",
	"exit_rules.win_flow_no_scripts":       "No <code>route add</code>, no .bat/.sh, no manual route manipulation — Tailscale receives routes via netmap push and installs them in the Windows routing table automatically.",
	"exit_rules.quick_title":               "Quick start",
	"exit_rules.quick_li1":                 "Pick a device and an exit node",
	"exit_rules.quick_li2":                 "Specify the target type and value",
	"exit_rules.quick_li3":                 "Click 'Add'",
	"exit_rules.quick_li4":                 "On the device: tailscale up --accept-routes --accept-dns=false (full setup — see /my/exit-rules/help, Windows section)",
	"exit_rules.client_title":              "Client setup",
	"exit_rules.client_win_linux":          "Windows / Linux",
	"exit_rules.client_mobile":             "Android / iOS",
	"exit_rules.client_win_cmd":            "tailscale up --login-server=https://head.example.com --authkey=<key> --accept-routes --accept-dns=false",
	"exit_rules.client_win_cmd_after":      "tailscale up --accept-routes --accept-dns=false",
	"exit_rules.client_win_hint":           "<code>--authkey</code> comes from /my/preauth (single-use). After first registration, <code>--authkey</code> is no longer needed — the short form is enough. Exit-node is selected in Tailscale tray → Exit node. Routes arrive automatically via headscale ACL.",
	"exit_rules.client_split_hint":         "Split-tunnel: whitelisted subnets route through the exit node, the rest goes direct. Tailscale installs per-CIDR routes at the kernel level — no manual <code>route add</code> needed.",
	"exit_rules.client_full_hint":          "Full tunnel: all traffic (0.0.0.0/0) goes through the exit node. Mobile does not support selective routing.",
	"exit_rules.important":                 "Important",
	"exit_rules.important_li1":             "IP/subnet — works for split-tunnel (Windows/Linux).",
	"exit_rules.important_li2":             "Domain — ACL rule only, does not affect routing.",
	"exit_rules.important_li3":             "After restarting Tailscale (tailscale down/up) re-run --accept-routes.",
	"exit_rules.important_li4":             "Rules are isolated: each user manages only their own devices.",
	"exit_rules.bulk_title":                "Bulk add",
	"exit_rules.bulk_desc":                 "Use an AI assistant (Hermes, Cline) to bulk-create rules:",
	"exit_rules.bulk_example":              "\"Add rules for my-laptop (device_id=5) through exit-node node-name: Telegram, YouTube, Google subnets\"",
	"exit_rules.privacy_title":             "Privacy",
	"exit_rules.privacy_li1":               "Rules are visible only to you and the administrator.",
	"exit_rules.privacy_li2":               "Other users don't see your devices or rules.",
	"exit_rules.privacy_li3":               "ACL guarantees advertised routes are only distributed to your devices.",
	"exit_rules.col_action":                "Action",
	"exit_rules.col_target":                "Target",
	"exit_rules.rules_count_suffix":        " rules",
	"exit_rules.exit_nodes_suffix":         " exit nodes",
	"exit_rules.usage_warn":                "%d/%d (%d%%) — more than half of the per-device limit is used.",
	"exit_rules.usage_danger":              "%d/%d (%d%%) — close to the per-device limit. Remove unused rules or contact the admin.",
	"exit_rules.usage_ok":                  "%d/%d (%d%%) — per-device limit is fine.",
	"exit_rules.usage_default":             "The device this rule applies to. Only your devices are visible.",
	"exit_rules_admin.title":               "Exit rules (admin)",
	"exit_rules_admin.subtitle":            "All rules across all users",
	"exit_rules_admin.user":                "User",
	"exit_rules_admin.device":              "Device",
	"exit_rules_admin.exit_node":           "Exit node",
	"exit_rules_admin.node_load":           "Node Load",
	"exit_rules_admin.reapply":             "Re-apply ACL",
	"exit_rules_admin.reapply_confirm":     "Re-apply ACL? This regenerates the policy from current DB state and pushes to headscale. Use after changes to GenerateACL().",
	"exit_rules_admin.rolled_back":         "ACL rolled back",
	"exit_rules_admin.reapplied":           "ACL re-applied",
	"exit_rules_admin.system_load":         "System load",
	"exit_rules_admin.all_rules":           "All rules (%d)",
	"exit_rules_admin.rules_count":         "%d rules",
	"exit_rules_admin.no_rules":            "No rules",
	"exit_rules_admin.col_action":          "Action",
	"exit_rules_admin.col_type":            "Type",
	"exit_rules_admin.col_resource":        "Resource",
	"exit_rules_admin.col_parent":          "Parent",
	// 2026-08-06: admin-side EN mirror.
	"exit_rules_admin.col_preferred":            "Preferred",
	"exit_rules_admin.preferred_match_title":    "Matches the device's preferred exit-node (%s).",
	"exit_rules_admin.preferred_mismatch_title": "Differs from the device's preferred exit-node (%s) — Tailscale will ignore this rule.",
	"exit_rules_admin.preferred_none_title":     "No preferred exit-node set.",
	// 2026-08-25 (B182): the new two-state ✅ / ⏳
	// preferred-exit-node badge. ✅ = rule's target CIDR is
	// APPROVED in headscale ApprovedRoutes for this
	// exit-node (the rule is fully working). ⏳ = rule
	// matches the device's preferred exit-node but
	// headscale has NOT approved the rule's target yet —
	// the autoupdater will push on the next 5-min tick, or
	// hit "Пере-синхронизировать" on /admin/exit-nodes.
	"exit_rules_admin.approved_in_headscale_title": "Target approved in headscale for %s — rule is working.",
	"exit_rules_admin.pending_in_headscale_title":  "Rule's exit-node matches the device's preferred, but headscale has NOT approved %s (target %s) yet. The autoupdater will push on the next 5-min tick (or hit 'Пере-синхронизировать' on /admin/exit-nodes).",
	"exit_rules_admin.preferred_mismatch_banner":   "%d rules across all users reference a non-preferred exit-node. Check the 'Preferred' column.",
	"exit_rules_admin.dead_rules_count":            "%d dead rule(s)",
	"exit_rules_admin.dead_rules_count_title":      "%d device_rule(s) for this device reference a non-preferred exit-node. Tailscale will ignore them. Open /admin/exit-rules to see which.",
	"exit_rules_admin.device_filter_banner":        "Filtered to device %s — %d rule(s) shown",
	"exit_rules_admin.device_filter_show_all":      "Show all",
	"exit_rules_admin.col_created":                 "Created",
	"exit_rules_admin.auto_managed":                "Auto-managed",
	"exit_rules_admin.delete_confirm":              "Delete rule #%d?",
	"exit_rules_admin.acl_history":                 "ACL application history",
	"exit_rules_admin.col_time":                    "Time",
	"exit_rules_admin.col_details":                 "Details",
	"exit_rules_admin.no_records":                  "No records",
	"exit_rules_admin.sync_section":                "Advertised-routes sync",
	"exit_rules_admin.sync_help":                   "Updates --advertise-routes on all exit-nodes according to the current rules.",
	"exit_rules_admin.sync":                        "Sync",
	"exit_rules_admin.sync_running":                "Syncing…",
	"exit_rules_admin.sync_done":                   "✓ Done",
	"exit_rules_admin.sync_error":                  "✗ Error",
	"exit_rules_admin.rollback_section":            "ACL rollback",
	"exit_rules_admin.col_version":                 "Version",
	"exit_rules_admin.col_by":                      "By",
	"exit_rules_admin.col_status":                  "Status",
	"exit_rules_admin.status_ok":                   "OK",
	"exit_rules_admin.status_err":                  "ERR",
	"exit_rules_admin.rollback":                    "Roll back",
	"exit_rules_admin.rollback_confirm":            "Roll back ACL to version %d?",
	"exit_rules_admin.no_snapshots":                "No snapshots",
	// 2026-09-11 (Issue #2 closure): admin add form.
	"exit_rules_admin.add_form_title":        "Add rule for another user's device",
	"exit_rules_admin.add_form_user_id":      "User ID (portal_users.id)",
	"exit_rules_admin.add_form_device_id":    "Device ID (headscale node_id)",
	"exit_rules_admin.add_form_exit_node":    "Exit node",
	"exit_rules_admin.add_form_target_type":  "Target type",
	"exit_rules_admin.add_form_target_value": "Target value (IP/CIDR/domain)",
	"exit_rules_admin.add_form_action":       "Action",
	"exit_rules_admin.add_form_submit":       "Add rule",
	"exit_rules_admin.add_form_help":         "Adds a rule on behalf of the selected user. headscale ACL src stays = device owner.",
	"exit_rules_admin.add_form_applied":      "Rule added",
	"cleanup.title":                          "Cleanup",
	"cleanup.subtitle":                       "Merge duplicate device_id and remove orphaned /32",
	"cleanup.duplicates":                     "Duplicate device_id",
	"cleanup.orphans":                        "Orphaned /32 rules",
	"cleanup.merge":                          "Merge",
	"cleanup.merge_confirm":                  "Merge %d duplicates?",
	"cleanup.delete_orphans":                 "Delete orphans",
	"cleanup.delete_orphans_confirm":         "Delete %d orphan rules?",
	"cleanup.col_total_rules":                "Total rules",
	"cleanup.col_distinct_device_id":         "Distinct device_id",
	"cleanup.col_distinct_hostname":          "Distinct hostname",
	"cleanup.col_to_merge":                   "To merge",
	"cleanup.col_to_backfill_device_ip":      "To backfill device_ip",
	"cleanup.col_stale_device_id":            "Stale device_id",
	"cleanup.col_hostname":                   "Hostname",
	"cleanup.col_canonical_device_id":        "Canonical device_id",
	"cleanup.col_all_device_id_in_group":     "All device_id in group",
	"cleanup.col_rules":                      "Rules",
	// 2026-09-20 (i18n-audit, section 1) — /admin/exit-rules/cleanup.
	"cleanup.page_subtitle":    "Merge duplicates by device_id and backfill device_ip. Idempotent.",
	"cleanup.applied_flash":    "Applied. Recomputed: merged=%d, resolved_ips=%d.",
	"cleanup.plan_title":       "Plan",
	"cleanup.groups_title":     "Groups by hostname",
	"cleanup.unknown_hostname": "unknown",
	"cleanup.apply_confirm":    "Apply cleanup? This will change device_id and device_ip for some rules and is irreversible without a backup.",
	"cleanup.apply_btn":        "Apply",
	"cleanup.recompute_btn":    "Recompute",
	// 2026-08-18 (B143, v1.4.3): in-app smoke-mesh
	// cleanup scheduler — see ru side for the full
	// contract.
	"cleanup_smoke.run_btn":        "Clean up smoke-meshes",
	"cleanup_smoke.run_btn_help":   "Delete all meshes rows with name smoke-mesh-* and no mesh_members. Runs immediately (same path as the in-app cron).",
	"cleanup_smoke.last_run":       "Last cleanup: %s",
	"cleanup_smoke.last_run_never": "Never",
	"cleanup_smoke.removed":        "Removed %d smoke-mesh rows",
	"cleanup_smoke.no_rows":        "No cruft found",
	"cleanup_smoke.failed":         "Cleanup failed: %s",
	// 2026-09-07 (B237.22 / TD-11): same key as RU — see
	// the RU comment for the contract.
	"exit_rules.cdn_group_count":     "%d ranges",
	"exit_rules_nodes.title":         "Exit nodes (sync)",
	"exit_rules_nodes.subtitle":      "Sync advertised-routes to exit nodes",
	"exit_rules_nodes.sync":          "Sync",
	"exit_rules_nodes.syncing":       "Syncing...",
	"exit_rules_nodes.last_sync":     "Last sync: %s",
	"exit_rules_nodes.col_name":      "Name",
	"exit_rules_nodes.col_rules":     "Rules",
	"exit_rules_nodes.col_load":      "Load",
	"exit_rules_nodes.col_available": "Available",
	"exit_rules_nodes.col_approved":  "Approved",
	"exit_rules_nodes.col_last_sync": "Last sync",
	// 2026-09-20 (i18n-audit, section 1) — /admin/exit-rules/nodes.
	"exit_rules_nodes.dashboard_title":       "Node Load Dashboard",
	"exit_rules_nodes.load_metrics_subtitle": "Exit-node load metrics",
	"exit_rules_nodes.exit_rules_link":       "Exit Rules",
	"exit_rules_nodes.system_load":           "System load",
	"exit_rules_nodes.limit_hint":            "Limit: SKYGATE_MAX_TOTAL_RULES=%d. When exceeded, users get 403.",
	"exit_rules_nodes.nodes_title":           "Exit-nodes (%d)",
	"exit_rules_nodes.colors_legend":         "<b>Colors:</b> <span class=\"tag tag-success\">green &lt; 50%</span> <span class=\"tag tag-warn\">yellow 50-80%</span> <span class=\"tag tag-danger\">red &gt; 80%</span>.",
	"exit_rules_nodes.load_formula":          "Load = rules_on_node / (MaxTotalRules / 5). If load &gt; 80% — adding new rules on this node may slow down sync.",
	"exit_rules_nodes.recommendations":       "Recommendations",
	"exit_rules_nodes.rec_green":             "🟢 <b>Green (&lt;50%):</b> normal. Add rules freely.",
	"exit_rules_nodes.rec_yellow":            "🟡 <b>Yellow (50-80%):</b> medium load. Watch sync latency.",
	"exit_rules_nodes.rec_red":               "🔴 <b>Red (&gt;80%):</b> high load. Consider moving some rules to another exit-node or reducing the number of domains (autoupdater resolves many IPs).",
	"exit_rules_nodes.rec_staggered":         "⏱️ <b>Staggered sync:</b> autoupdater updates IPs in batches (SKYGATE_STAGGER_BATCH_SIZE) with an interval (SKYGATE_STAGGER_INTERVAL) — does not overload headscale approve-routes.",
	"exit_rules_nodes.rec_last_sync":         "🔄 <b>Last sync:</b> last successful sync for this node. If \"never\" — autoupdater hasn't reached it yet.",
}
