// Code generated by split_i18n.py — refactor-v0.30 Phase C.
// DO NOT EDIT THIS FILE BY HAND — run scripts/split_i18n.py to
// regenerate from the source-of-truth (catalog_common.go etc.)
//
// Per-feature i18n keys for the Modules admin feature
// (B-mod-admin, 2026-09-10). Keys are declared as
// package-level maps; the glue file (catalog.go) merges
// them in New().
//
// Top-level prefixes: modules

package i18n

// modules feature — 18 ru keys, 18 en keys (B-mod-admin 2026-09-10).
// Mirrors the sub-feature names + lifecycle verbs in
// internal/module/tailscale/ so the operator can see the
// same labels in /admin/modules/{name} as in
// /admin/tailscale (the legacy per-feature page).

var ruModules = map[string]string{
	// /admin/modules list page
	"modules.title":            "Модули",
	"modules.subtitle":         "Управление модулями skygate (Tailscale, cluster, telegram, derp, exit). Каждый модуль имеет lifecycle: install → start → stop, плюс opt-in sub-features.",
	"modules.name":             "Модуль",
	"modules.state":            "Состояние",
	"modules.install_mode":     "Режим установки",
	"modules.installed_at":     "Установлен",
	"modules.started_at":       "Запущен",
	"modules.actions":          "Действия",
	"modules.install":          "Установить",
	"modules.start":            "Запустить",
	"modules.stop":             "Остановить",
	"modules.enable":           "Включить",
	"modules.disable":          "Выключить",
	"modules.subfeatures":      "Sub-features",
	"modules.detail":           "Детали",
	"modules.not_registered":   "Модуль не зарегистрирован (возможно, B-mod-core wiring revertнут — см. 82c74b38).",
	"modules.install_mode_os":  "OS-level (apt + systemd)",
	"modules.install_mode_in":  "Container (docker sidecar)",
	"modules.install_mode_at":  "Attach (хост tailscaled уже запущен)",

	// /admin/modules/{name} detail page
	"modules.detail_title":         "Модуль: %s",
	"modules.detail_subtitle":      "Состояние, sub-features, audit history.",
	"modules.health_heading":       "Здоровье (последняя проверка)",
	"modules.health_ok":            "OK",
	"modules.health_failed":        "DEGRADED",
	"modules.subfeatures_heading":  "Sub-features (%d)",
	"modules.subfeature_enable":    "Включить",
	"modules.subfeature_disable":   "Выключить",
	"modules.subfeature_requires":  "Требует: %s (включите сначала)",
	"modules.subfeature_impact":    "Эффект: %s",
	"modules.audit_heading":        "Audit history (последние 20)",
	"modules.no_audit":             "пока нет audit rows",
	"modules.confirm_install":      "Установить модуль %s? (нужен root или docker)",
	"modules.confirm_stop":         "Остановить модуль %s? tailscaled НЕ будет остановлен (его используют другие модули).",
	"modules.flash_installed":      "Модуль %s установлен (режим: %s)",
	"modules.flash_started":        "Модуль %s запущен",
	"modules.flash_stopped":        "Модуль %s остановлен",
	"modules.flash_subfeature_on":  "Sub-feature %s включена",
	"modules.flash_subfeature_off": "Sub-feature %s выключена",
	"modules.flash_error":          "Ошибка: %s",
}

var enModules = map[string]string{
	// /admin/modules list page
	"modules.title":            "Modules",
	"modules.subtitle":         "Manage skygate modules (Tailscale, cluster, telegram, derp, exit). Each module has a lifecycle: install → start → stop, plus opt-in sub-features.",
	"modules.name":             "Module",
	"modules.state":            "State",
	"modules.install_mode":     "Install mode",
	"modules.installed_at":     "Installed at",
	"modules.started_at":       "Started at",
	"modules.actions":          "Actions",
	"modules.install":          "Install",
	"modules.start":            "Start",
	"modules.stop":             "Stop",
	"modules.enable":           "Enable",
	"modules.disable":          "Disable",
	"modules.subfeatures":      "Sub-features",
	"modules.detail":           "Details",
	"modules.not_registered":   "Module not registered (B-mod-core wiring may be reverted — see 82c74b38).",
	"modules.install_mode_os":  "OS-level (apt + systemd)",
	"modules.install_mode_in":  "Container (docker sidecar)",
	"modules.install_mode_at":  "Attach (host tailscaled already running)",

	// /admin/modules/{name} detail page
	"modules.detail_title":         "Module: %s",
	"modules.detail_subtitle":      "State, sub-features, audit history.",
	"modules.health_heading":       "Health (last check)",
	"modules.health_ok":            "OK",
	"modules.health_failed":        "DEGRADED",
	"modules.subfeatures_heading":  "Sub-features (%d)",
	"modules.subfeature_enable":    "Enable",
	"modules.subfeature_disable":   "Disable",
	"modules.subfeature_requires":  "Requires: %s (enable it first)",
	"modules.subfeature_impact":    "Impact: %s",
	"modules.audit_heading":        "Audit history (last 20)",
	"modules.no_audit":             "no audit rows yet",
	"modules.confirm_install":      "Install module %s? (requires root or docker)",
	"modules.confirm_stop":         "Stop module %s? tailscaled will NOT be stopped (other modules depend on it).",
	"modules.flash_installed":      "Module %s installed (mode: %s)",
	"modules.flash_started":        "Module %s started",
	"modules.flash_stopped":        "Module %s stopped",
	"modules.flash_subfeature_on":  "Sub-feature %s enabled",
	"modules.flash_subfeature_off": "Sub-feature %s disabled",
	"modules.flash_error":          "Error: %s",
}
