// Code generated by split_i18n.py — refactor-v0.30 Phase C.
// DO NOT EDIT THIS FILE BY HAND — run scripts/split_i18n.py to
// regenerate from the source-of-truth (catalog_common.go etc.)
//
// Per-feature i18n keys for the Modules admin feature
// (B-mod-admin, 2026-09-10). Keys are declared as
// package-level maps; the glue file (catalog.go) merges
// them in New().
//
// Top-level prefixes: modules

package i18n

// modules feature — 18 ru keys, 18 en keys (B-mod-admin 2026-09-10).
// Mirrors the sub-feature names + lifecycle verbs in
// internal/module/tailscale/ so the operator can see the
// same labels in /admin/modules/{name} as in
// /admin/tailscale (the legacy per-feature page).

var ruModules = map[string]string{
	// /admin/modules list page
	"modules.title":                 "Модули",
	"modules.subtitle":              "Управление модулями skygate (Tailscale, cluster, telegram, derp, exit). Каждый модуль имеет lifecycle: install → start → stop, плюс opt-in sub-features.",
	"modules.name":                  "Модуль",
	"modules.state":                 "Состояние",
	"modules.install_mode":          "Режим установки",
	"modules.installed_at":          "Установлен",
	"modules.started_at":            "Запущен",
	"modules.actions":               "Действия",
	"modules.install":               "Установить",
	"modules.test":                  "Проверить",
	"modules.test_section":          "Модули проекта",
	"modules.test_help":             "Запустить проверку модуля (состояние + здоровье) и отправить результат в мониторинг",
	"modules.start":                 "Запустить",
	"modules.stop":                  "Остановить",
	"modules.enable":                "Включить",
	"modules.disable":               "Выключить",
	"modules.subfeatures":           "Подфункции",
	"modules.detail":                "Детали",
	"modules.not_registered":        "Модуль не зарегистрирован (возможно, B-mod-core wiring revertнут — см. 82c74b38).",
	"modules.manager_not_wired":     "Менеджер модулей не подключён.",
	"modules.no_modules_registered": "Модули не зарегистрированы.",
	"modules.install_mode_os":       "На уровне ОС (apt + systemd)",
	"modules.install_mode_in":       "Контейнер (docker-сайдкар)",
	"modules.install_mode_at":       "Attach (хост tailscaled уже запущен)",

	// /admin/modules/{name} detail page
	"modules.detail_title":         "Модуль: %s",
	"modules.detail_subtitle":      "Состояние, под-функции, история аудита.",
	"modules.health_heading":       "Здоровье (последняя проверка)",
	"modules.health_ok":            "OK",
	"modules.health_failed":        "ДЕГРАДАЦИЯ",
	"modules.subfeatures_heading":  "Подфункции (%d)",
	"modules.subfeature_enable":    "Включить",
	"modules.subfeature_disable":   "Выключить",
	"modules.subfeature_requires":  "Требует: %s (включите сначала)",
	"modules.subfeature_impact":    "Эффект: %s",
	"modules.audit_heading":        "История аудита (последние 20)",
	"modules.no_audit":             "пока нет строк аудита",
	"modules.confirm_install":      "Установить модуль %s? (нужен root или docker)",
	"modules.confirm_stop":         "Остановить модуль %s? tailscaled НЕ будет остановлен (его используют другие модули).",
	"modules.flash_installed":      "Модуль %s установлен (режим: %s)",
	"modules.flash_started":        "Модуль %s запущен",
	"modules.flash_stopped":        "Модуль %s остановлен",
	"modules.flash_subfeature_on":  "Sub-feature %s включена",
	"modules.flash_subfeature_off": "Sub-feature %s выключена",
	"modules.flash_error":          "Ошибка: %s",
	"module_detail.col_when_utc":   "Когда (UTC)",
	"module_detail.col_action":     "Действие",
	"module_detail.col_by":         "Кем",
	"module_detail.col_detail":     "Детали",
	// 2026-09-20 (i18n-audit, раздел 1): /admin/modules/{name} был наполовину
	// английским (State, mode/installed/started, Health, Requires/Impact,
	// Enable/Disable). «Sub-features», «Audit history» и «no audit rows»
	// переиспользуют ключи modules.* — они подходят по смыслу.
	"module_detail.back_to_modules":     "← назад к модулям",
	"module_detail.state":               "Состояние",
	"module_detail.mode_label":          " · режим: ",
	"module_detail.installed_label":     " · установлен: ",
	"module_detail.started_label":       " · запущен: ",
	"module_detail.health_heading":      "Здоровье (%s)",
	"module_detail.health_ok":           "OK",
	"module_detail.health_fail":         "СБОЙ",
	"module_detail.last_error":          "последняя ошибка: ",
	"module_detail.subfeature_on":       "[вкл]",
	"module_detail.subfeature_off":      "[выкл]",
	"module_detail.subfeature_requires": "Требует: ",
	"module_detail.subfeature_impact":   "Эффект: ",
	"module_detail.subfeature_enable":   "Включить",
	"module_detail.subfeature_disable":  "Выключить",
	"module_detail.by_system":           "система",
}

var enModules = map[string]string{
	// /admin/modules list page
	"modules.title":                 "Modules",
	"modules.subtitle":              "Manage skygate modules (Tailscale, cluster, telegram, derp, exit). Each module has a lifecycle: install → start → stop, plus opt-in sub-features.",
	"modules.name":                  "Module",
	"modules.state":                 "State",
	"modules.install_mode":          "Install mode",
	"modules.installed_at":          "Installed at",
	"modules.started_at":            "Started at",
	"modules.actions":               "Actions",
	"modules.install":               "Install",
	"modules.test":                  "Check",
	"modules.test_section":          "Project modules",
	"modules.test_help":             "Run the module check (state + health) and record the result in monitoring",
	"modules.start":                 "Start",
	"modules.stop":                  "Stop",
	"modules.enable":                "Enable",
	"modules.disable":               "Disable",
	"modules.subfeatures":           "Sub-features",
	"modules.detail":                "Details",
	"modules.not_registered":        "Module not registered (B-mod-core wiring may be reverted — see 82c74b38).",
	"modules.manager_not_wired":     "Manager not wired.",
	"modules.no_modules_registered": "No modules registered.",
	"modules.install_mode_os":       "OS-level (apt + systemd)",
	"modules.install_mode_in":       "Container (docker sidecar)",
	"modules.install_mode_at":       "Attach (host tailscaled already running)",

	// /admin/modules/{name} detail page
	"modules.detail_title":         "Module: %s",
	"modules.detail_subtitle":      "State, sub-features, audit history.",
	"modules.health_heading":       "Health (last check)",
	"modules.health_ok":            "OK",
	"modules.health_failed":        "DEGRADED",
	"modules.subfeatures_heading":  "Sub-features (%d)",
	"modules.subfeature_enable":    "Enable",
	"modules.subfeature_disable":   "Disable",
	"modules.subfeature_requires":  "Requires: %s (enable it first)",
	"modules.subfeature_impact":    "Impact: %s",
	"modules.audit_heading":        "Audit history (last 20)",
	"modules.no_audit":             "no audit rows yet",
	"modules.confirm_install":      "Install module %s? (requires root or docker)",
	"modules.confirm_stop":         "Stop module %s? tailscaled will NOT be stopped (other modules depend on it).",
	"modules.flash_installed":      "Module %s installed (mode: %s)",
	"modules.flash_started":        "Module %s started",
	"modules.flash_stopped":        "Module %s stopped",
	"modules.flash_subfeature_on":  "Sub-feature %s enabled",
	"modules.flash_subfeature_off": "Sub-feature %s disabled",
	"modules.flash_error":          "Error: %s",
	"module_detail.col_when_utc":   "When (UTC)",
	"module_detail.col_action":     "Action",
	"module_detail.col_by":         "By",
	"module_detail.col_detail":     "Detail",
	// 2026-09-20 (i18n-audit, section 1) — see the RU block above.
	"module_detail.back_to_modules":     "← back to modules",
	"module_detail.state":               "State",
	"module_detail.mode_label":          " · mode: ",
	"module_detail.installed_label":     " · installed: ",
	"module_detail.started_label":       " · started: ",
	"module_detail.health_heading":      "Health (%s)",
	"module_detail.health_ok":           "OK",
	"module_detail.health_fail":         "FAIL",
	"module_detail.last_error":          "last error: ",
	"module_detail.subfeature_on":       "[on]",
	"module_detail.subfeature_off":      "[off]",
	"module_detail.subfeature_requires": "Requires: ",
	"module_detail.subfeature_impact":   "Impact: ",
	"module_detail.subfeature_enable":   "Enable",
	"module_detail.subfeature_disable":  "Disable",
	"module_detail.by_system":           "system",
}
