"""
SQLite → PostgreSQL data migration for skygate.

Reads the live SQLite skygate.db (from the old VM), generates
PG-compatible INSERT statements, and writes them to a .sql
file that can be applied via `psql -f` to the new VM's PG.

Conversion rules:
  - All `?` placeholders (none — this is pure data) → use explicit
    column lists, no placeholders
  - INTEGER PRIMARY KEY AUTOINCREMENT → use the schema's BIGSERIAL;
    in the INSERT we supply explicit IDs (so the PG sequences
    get out of sync — fixed by `setval()` calls after each
    table's INSERTs)
  - TEXT → TEXT (no change)
  - INTEGER (Unix epoch) → BIGINT (no change)
  - BOOLEAN 0/1 → kept as 0/1 (the schema column is BIGINT)

Sequence fixup: after each table's data INSERTs, we emit
`SELECT setval('<table>_id_seq', MAX(id), true) FROM <table>;`
to bring the BIGSERIAL sequence in line with the imported IDs.

Tables to migrate (in dependency order — parents first):
  1. portal_users                 (root, FK target)
  2. preauth_keys                 (FK → portal_users)
  3. devices                      (FK → portal_users)
  4. audit_log                    (FK → portal_users, no CASCADE)
  5. node_owner_map               (PK = node_id, TEXT)
  6. exit_servers                 (PK = node_id, TEXT)
  7. device_rules                 (FK → portal_users)
  8. acl_snapshots                (no FK)
  9. exit_rule_logs               (no FK)
 10. global_settings              (PK = key, TEXT)
 11. personal_api_tokens          (FK → portal_users)
 12. telegram_alerts              (no FK)
 13. telegram_bindings            (FK → portal_users)
 14. telegram_login_tokens        (no FK)
 15. telegram_rate_limit          (no FK)
 16. exit_node_health             (PK = node_id, TEXT)
 17. exit_node_state_changes      (no FK)
 18. user_subnets                 (FK → portal_users)
 19. user_subnet_shares           (FK → portal_users)
 20. headscale_releases           (no FK)
 21. invite_codes                 (no FK)
 22. meshes                       (no FK)
 23. mesh_members                 (FK → meshes, portal_users)

Output: PG_INSERTs with explicit IDs + setval() fixups.
"""
import sqlite3
import sys
from pathlib import Path

# Order matters: parents first, then children.
TABLES = [
    "portal_users",
    "preauth_keys",
    "devices",
    "audit_log",
    "node_owner_map",
    "exit_servers",
    "device_rules",
    "acl_snapshots",
    "exit_rule_logs",
    "global_settings",
    "personal_api_tokens",
    "telegram_alerts",
    "telegram_bindings",
    "telegram_login_tokens",
    "telegram_rate_limit",
    "exit_node_health",
    "exit_node_state_changes",
    "user_subnets",
    "user_subnet_shares",
    "headscale_releases",
    "invite_codes",
    "meshes",
    "mesh_members",
]

# Columns that exist in the live SQLite DB but NOT in the current
# v0.27.0 PG schema. The most common reason is a migration that
# was later reverted (e.g. v0.19.0's "preferred_exit_node_id") or
# a column that's only present in newer production deploys.
# We filter these out so the dump is PG-compatible.
COLUMNS_TO_SKIP = {
    "user_subnets": {"preferred_exit_node_id"},
}


def quote_value(v, is_int_pk=False):
    """Format a value for a PG INSERT statement.

    - None → NULL
    - bytes → '\\x' + hex
    - bool → 0/1 (PG stores as BIGINT)
    - int → str(v)  (no quotes; let PG infer the type)
    - str → quoted with single-quote escaping
    """
    if v is None:
        return "NULL"
    if isinstance(v, (int,)):
        return str(v)
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, bytes):
        return "'\\x" + v.hex() + "'"
    if isinstance(v, (int, float)):
        return str(v)
    # String
    s = str(v).replace("'", "''")
    return f"'{s}'"


def escape_identifier(s):
    return '"' + s.replace('"', '""') + '"'


def main(sqlite_path, output_path):
    con = sqlite3.connect(sqlite_path)
    con.row_factory = sqlite3.Row
    cur = con.cursor()

    out = []
    out.append("-- Auto-generated by dump_sqlite.py")
    out.append("-- Source: " + str(sqlite_path))
    out.append("-- DO NOT EDIT by hand. Apply via: psql -f <this_file>")
    out.append("")
    out.append("BEGIN;")
    out.append("")

    total_rows = 0
    for table in TABLES:
        # Get column list
        cur.execute(f"PRAGMA table_info({table})")
        cols = [row["name"] for row in cur.fetchall()]
        if not cols:
            out.append(f"-- SKIP: table {table} not found in source")
            continue
        # Filter out columns that don't exist in the PG schema.
        skip = COLUMNS_TO_SKIP.get(table, set())
        if skip:
            cols = [c for c in cols if c not in skip]
            out.append(f"-- (dropped columns not in PG schema: {sorted(skip)})")

        # Get row count
        cur.execute(f"SELECT COUNT(*) FROM {table}")
        n = cur.fetchone()[0]

        out.append(f"-- Table: {table} ({n} rows)")
        out.append(f"TRUNCATE TABLE {escape_identifier(table)} CASCADE;")
        # Stream rows in batches of 500 to keep memory bounded.
        BATCH = 500
        offset = 0
        while offset < n:
            cur.execute(
                f"SELECT * FROM {table} ORDER BY rowid LIMIT ? OFFSET ?",
                (BATCH, offset),
            )
            rows = cur.fetchall()
            if not rows:
                break
            for row in rows:
                vals = [quote_value(row[c]) for c in cols]
                col_list = ", ".join(escape_identifier(c) for c in cols)
                val_list = ", ".join(vals)
                out.append(
                    f"INSERT INTO {escape_identifier(table)} ({col_list}) VALUES ({val_list});"
                )
            offset += len(rows)
        out.append("")

        # Sequence fixup: if the table has a BIGSERIAL 'id' column,
        # advance the sequence to the max imported id.
        if "id" in cols:
            out.append(
                f"SELECT setval("
                f"pg_get_serial_sequence('{escape_identifier(table)}', 'id'),"
                f" COALESCE((SELECT MAX(id) FROM {escape_identifier(table)}), 1),"
                f" true);"
            )
            out.append("")
        total_rows += n
        out.append("")

    out.append("COMMIT;")
    out.append(f"-- Total rows imported: {total_rows}")
    out.append("")

    Path(output_path).write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {output_path} ({total_rows} rows across {len(TABLES)} tables)")


if __name__ == "__main__":
    sqlite_path = sys.argv[1] if len(sys.argv) > 1 else r"C:\Temp\skygate-cleanup-2026-07-22\skygate.db"
    output_path = sys.argv[2] if len(sys.argv) > 2 else r"C:\Temp\skygate-cleanup-2026-07-22\skygate_pg_dump.sql"
    main(sqlite_path, output_path)
