// driver_sqlite.go — SQLite backend (B-mod-sqlite-pg-bidi v1.5.4).
//
// Sister file to driver_postgres.go. The PG migration set has been
// the canonical one since v1.3.0 (B-mod-db-retry); B-mod-sqlite-pg-bidi
// restores explicit SQLite support by running the same migration
// numbers through the SQLite migration functions in
// migrations_sqlite.go (generated by scripts/port_migrations_sqlite.py
// via reverse-substitution from the PG source).
//
// Why a separate file (not just shadow-files):
//
// The PG and SQLite migration SETS have parallel structure (same
// version numbers, same metadata) but the DDL is dialect-specific
// (BIGSERIAL vs INTEGER PK AUTOINCREMENT, EXTRACT(EPOCH) vs
// strftime('%s'), INSERT OR IGNORE vs ON CONFLICT, etc.). Putting
// the registry + Run loop in the same file as the migration
// functions would couple them too tightly. The PG side stays in
// driver_postgres.go (existing); the SQLite side gets a parallel
// driver_sqlite.go that mirrors the structure.
//
// sqliteMigrations mirrors pgMigrations: same version numbers, same
// Name strings, same SourceFile pointers (so the B198 audit
// `applied_migrations.source_file` column shows the same Go file
// regardless of which DB applied the migration — the migration
// AUTHORSHIP is shared, only the DDL differs).
package db

import (
	"database/sql"
	"fmt"
	"log"
)

// sqliteMigrations is the ordered list of all SQLite migrations
// the current skygate binary knows about. Mirrors pgMigrations in
// driver_postgres.go — same version numbers, same Name strings,
// same SourceFile pointers. The DDL inside migrateVxxxSQLite
// differs (BIGSERIAL → INTEGER PK AUTOINCREMENT, EXTRACT(EPOCH)
// → strftime, etc.) but the migration AUTHORSHIP (which Go file
// defined the schema shape) is the same.
//
// Ordering: V025 runs first because V020+ have FOREIGN KEY →
// portal_users (which V025 creates). The rest are in numeric
// order with the historical V040 / V052 / V062 / V064 gaps
// preserved (those numbers were used for hotfixes that were
// rolled into other migrations).
var sqliteMigrations = []MigrationEntry{
	{25, "v0.25 (B0): portal_users + auth tables", "migrations_pg.go", migrateV025SQLite},
	{20, "v0.20 (B0): exit_servers", "migrations_pg.go", migrateV020SQLite},
	{21, "v0.21 (B0): device_rules action", "migrations_pg.go", migrateV021SQLite},
	{22, "v0.22 (B0): device_rules fix", "migrations_pg.go", migrateV022SQLite},
	{23, "v0.23 (B0): device_rules + portal_users", "migrations_pg.go", migrateV023SQLite},
	{24, "v0.24 (B0): exit_servers.ssh_target", "migrations_pg.go", migrateV024SQLite},
	{26, "v0.26 (B0): exit_servers.accept_routes", "migrations_pg.go", migrateV026SQLite},
	{27, "v0.27 (B0): telegram_alerts", "migrations_pg.go", migrateV027SQLite},
	{28, "v0.28 (B0): device_rules.parent_domain", "migrations_pg.go", migrateV028SQLite},
	{29, "v0.29 (B0): telegram_bindings", "migrations_pg.go", migrateV029SQLite},
	{30, "v0.30 (B0): portal_users.default_device_node_id", "migrations_pg.go", migrateV030SQLite},
	{31, "v0.31 (B0): telegram_login_tokens", "migrations_pg.go", migrateV031SQLite},
	{32, "v0.32 (B0): telegram_rate_limit", "migrations_pg.go", migrateV032SQLite},
	{33, "v0.33 (B0): telegram_bindings.lang", "migrations_pg.go", migrateV033SQLite},
	{34, "v0.34 (B0): node_owner_map.hostname", "migrations_pg.go", migrateV034SQLite},
	{35, "v0.35 (B0): portal_users.headscale_url", "migrations_pg.go", migrateV035SQLite},
	{36, "v0.36 (B0): exit-node health monitor", "migrations_pg.go", migrateV036SQLite},
	{37, "v0.37 (B0): personal_api_tokens.expires_at", "migrations_pg.go", migrateV037SQLite},
	{38, "v0.38 (B0): user_subnets", "migrations_pg.go", migrateV038SQLite},
	{39, "v0.39 (B0): user_subnets constraints", "migrations_pg.go", migrateV039SQLite},
	{41, "v0.41 (B0): ACL + backfill", "migrations_pg.go", migrateV041SQLite},
	{42, "v0.42 (B0): user_subnets schema", "migrations_pg.go", migrateV042SQLite},
	{43, "v0.43 (B0):", "migrations_pg.go", migrateV043SQLite},
	{44, "v0.44 (B0):", "migrations_pg.go", migrateV044SQLite},
	{45, "v0.45 (B0): device_rules cleanup", "migrations_pg.go", migrateV045SQLite},
	{46, "v0.46 (B0): exit_node_prefs backfill", "migrations_pg.go", migrateV046SQLite},
	{47, "v0.47 (B0): ACL backfill (skipped — see migrations_v0_47_test.go)", "migrations_pg.go", migrateV047SQLite},
	{48, "v0.48 (B0):", "migrations_pg.go", migrateV048SQLite},
	{49, "v0.49 (B0): applied_migrations tracking table", "migrations_pg.go", migrateV049SQLite},
	{50, "v0.50 (B0):", "migrations_pg.go", migrateV050SQLite},
	{51, "v0.51 (B0):", "migrations_pg.go", migrateV051SQLite},
	{53, "v0.53 (B0): exit_servers.ssh_port", "migrations_pg.go", migrateV053SQLite},
	{54, "v0.54 (B0):", "migrations_pg.go", migrateV054SQLite},
	{55, "v0.55 (B0):", "migrations_pg.go", migrateV055SQLite},
	{56, "v0.56 (B0):", "migrations_pg.go", migrateV056SQLite},
	{57, "v0.57 (B0):", "migrations_pg.go", migrateV057SQLite},
	{58, "v0.58 (B0):", "migrations_pg.go", migrateV058SQLite},
	{59, "v0.59 (B0):", "migrations_pg.go", migrateV059SQLite},
	{60, "v0.60 (B183): Telegram + audit_log", "migrations_v0_60_b183_test.go", migrateV060SQLite},
	{61, "v0.61 (B188): dev-tag owner_map", "migrations_v0_61_b188_test.go", migrateV061SQLite},
	{62, "v0.62 (B194):", "migrations_v0_62_b194.go", migrateV062SQLite},
	{63, "v0.63 (B194):", "migrations_v0_63_b194.go", migrateV063SQLite},
	{64, "v0.64 (B195): cluster_* tables (cluster / cluster_node / cluster_database / cluster_migration / cluster_invite / cluster_audit)", "migrations_v0_64_b195.go", migrateV064SQLite},
	{65, "v0.65 (B198): dbmigrate_run + dbmigrate_step", "migrations_v0_65_b198.go", migrateV065SQLite},
	{66, "v0.66 (B211): cluster_node UNIQUE (cluster_id, hostname)", "migrations_v0_66_b211.go", migrateV066SQLite},
	{67, "v0.67 (B221): audit_log.target_type + target_id (Phase 4.1 generic audit log)", "migrations_v0_67_b221.go", migrateV067SQLite},
	{68, "v0.68 (B232): repair device_rules_natural_key_uniq shape drift (B188.2 ON CONFLICT 6-col)", "migrations_v0_68_b232.go", migrateV068SQLite},
	{69, "v0.69 (B235.3): derp_health.name column for the B235 .Name short-label pill", "migrations_v0_69_b235_3.go", migrateV069SQLite},
	{70, "v0.70 (B236): portal_users AFTER UPDATE audit trigger (catches out-of-band password_hash rotations)", "migrations_v0_70_b238.go", migrateV070SQLite},
	// 2026-09-18: V071 was missing entirely, so the SQLite chain stopped at
	// V070 and derp_cert_sync was never created. Two bugs fixed here: the
	// entry is added, and its SourceFile now names the file that actually
	// defines migrateV070SQLite (migrations_v0_70_b238.go — the old
	// "migrations_v0_70_b236.go" does not exist in the tree).
	{71, "v0.71 (B252): derp_cert_sync table (cert auto-renewal state for bundled derper)", "migrations_v0_71_derp_cert_sync.go", migrateV071SQLite},
	{72, "v0.72 (B264): portal_users.is_primary — the immutable primary admin (partial UNIQUE index + backfill)", "migrations_v0_72_admin_primary.go", migrateV072SQLite},
	{73, "v0.73 (B275): prefix_owner — the prefix-to-relay assignment table (one advertising relay per prefix)", "migrations_v0_73_prefix_owner.go", migrateV073SQLite},
	{74, "v0.74 (B276.1): device_rules.all_devices — 'all my devices' as a live intent the propagation pass re-materialises", "migrations_v0_74_all_devices.go", migrateV074SQLite},
	{75, "v0.75 (B-oidc-setup): oidc_settings — DB-backed OIDC config so the admin web UI can enable / configure OIDC without env-var edits", "migrations_v0_75_oidc_settings.go", migrateV075SQLite},
	{76, "v0.76 (B305): monitor_events — the operator monitoring inbox (severity + dedup by fingerprint + ack/resolve)", "migrations_v0_76_monitor_events.go", migrateV076SQLite},
}

// SQLiteMigrations returns the list of migrations the current
// skygate binary knows about for the SQLite backend. Used by
// `skygate migrate status` (B213 CLI) and the audit page.
func SQLiteMigrations() []MigrationEntry {
	out := make([]MigrationEntry, len(sqliteMigrations))
	copy(out, sqliteMigrations)
	return out
}

// MigrateSQLite runs every SQLite migration in version order,
// records each successful application in applied_migrations
// (idempotent — first-write-wins on the version primary key), and
// returns the first error encountered. The migration state is
// whatever the DB was left in.
//
// Mirror of MigratePostgres in driver_postgres.go. The two
// functions MUST stay in lock-step — same metadata, same Run
// ordering, same bookkeeping. Only the DDL inside the migrateVxxx
// functions differs.
func MigrateSQLite(d *sql.DB) error {
	// Ensure the applied_migrations tracking table exists BEFORE
	// we try to write to it. ensureMigrationTrackingTable is
	// dialect-aware (Task 6: it dispatches on BackendOf(d)).
	if err := ensureMigrationTrackingTable(d); err != nil {
		return fmt.Errorf("ensure applied_migrations table: %w", err)
	}
	for _, e := range sqliteMigrations {
		if err := e.Run(d); err != nil {
			return fmt.Errorf("migration v%d (%s): %w", e.Version, e.Name, err)
		}
		versionStr := fmt.Sprintf("v0.%d", e.Version)
		if err := RecordMigrationApplied(d, e.Version, "", e.SourceFile, versionStr); err != nil {
			// Mirror the PG-side policy: log + continue. The
			// migration already ran, so the schema is correct;
			// the bookkeeping is out of sync. Re-running on
			// next boot would re-apply the migration (idempotent
			// IF NOT EXISTS guards) and re-attempt the
			// bookkeeping insert.
			log.Printf("migrate: WARNING: record v%d (%s) failed: %v (continuing — schema is correct, bookkeeping is out of sync)", e.Version, e.Name, err)
		}
	}
	return nil
}

// ApplyMigrations runs the dialect-appropriate migration chain
// against the given *sql.DB. Dispatches on `kind`:
//
//   - DialectSQLite: MigrateSQLite
//   - DialectPostgres: MigratePostgres
//   - DialectUnknown: error
//
// The kind argument is the canonical "which migration set to run"
// value. The *sql.DB's actual backend (BackendOf(db)) is NOT
// consulted here — caller is responsible for ensuring the kind
// matches the DB (the typical case is DetectDSN → OpenWithDialect
// which returns both the kind and the open *sql.DB).
//
// Use this function when you have a *sql.DB and want to ensure
// the schema is fully migrated. Use the dialect-specific
// MigrateSQLite / MigratePostgres when you already know the kind.
func ApplyMigrations(db *sql.DB, kind DialectKind) error {
	switch kind {
	case DialectSQLite:
		return MigrateSQLite(db)
	case DialectPostgres:
		return MigratePostgres(db)
	default:
		return fmt.Errorf("db.ApplyMigrations: unknown dialect kind %v", kind)
	}
}
