// Code generated by port_migrations_sqlite.py; DO NOT EDIT.
// This is a mechanical reverse-port of the PostgreSQL migrations to SQLite.
// Review the file and resolve any TODO comments by hand.
//
// Pre-v1.5.4 (B-mod-db-retry era) skygate was PG-only; the SQLite migration
// files were deleted in v1.3.0. B-mod-sqlite-pg-bidi restores SQLite support
// by re-deriving the SQLite migration set from the (still-present) PG files
// via reverse substitution:
//   BIGSERIAL -> INTEGER PRIMARY KEY AUTOINCREMENT
//   EXTRACT(EPOCH FROM x)::bigint -> strftime('%s', x)
//   ON CONFLICT (cols) DO NOTHING -> INSERT OR IGNORE INTO ... (suffix stripped)
//   JSONB / BOOLEAN / TIMESTAMPTZ / bytea -> TEXT / INTEGER / INTEGER / BLOB
//   $N placeholders -> ?

package db

import (
	"database/sql"
	"fmt"
)

// migrateV020SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV020PG.
func migrateV020SQLite(d *sql.DB) error {


			queries := []string{
				`CREATE TABLE IF NOT EXISTS exit_servers (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					node_id TEXT NOT NULL UNIQUE,
					hostname TEXT NOT NULL,
					tailscale_ip TEXT NOT NULL DEFAULT '',
					description TEXT DEFAULT '',
					enabled INTEGER DEFAULT 1,
					created_at INTEGER DEFAULT (strftime('%s', 'now'))
				)`,
				`CREATE TABLE IF NOT EXISTS device_rules (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					user_id INTEGER NOT NULL,
					device_id INTEGER NOT NULL,
					exit_node_id TEXT NOT NULL,
					target_type TEXT NOT NULL DEFAULT 'domain',
					target_value TEXT NOT NULL,
					enabled INTEGER DEFAULT 1,
					created_at INTEGER DEFAULT (strftime('%s', 'now')),
					FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
				)`,
				`CREATE TABLE IF NOT EXISTS acl_snapshots (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					version INTEGER NOT NULL,
					config TEXT NOT NULL,
					created_by TEXT NOT NULL,
					applied_success INTEGER DEFAULT NULL,
					error_msg TEXT DEFAULT '',
					created_at INTEGER DEFAULT (strftime('%s', 'now'))
				)`,
				`CREATE TABLE IF NOT EXISTS exit_rule_logs (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					version INTEGER NOT NULL,
					action TEXT NOT NULL,
					detail TEXT DEFAULT '',
					created_at INTEGER DEFAULT (strftime('%s', 'now'))
				)`,
			}
			for _, q := range queries {
				if _, err := d.Exec(q); err != nil {
					return err
				}
			}
			return nil
}

// migrateV021SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV021PG.
func migrateV021SQLite(d *sql.DB) error {


			queries := []string{
				`ALTER TABLE device_rules ADD COLUMN action TEXT NOT NULL DEFAULT 'accept'`,
				`CREATE TABLE IF NOT EXISTS global_settings (
					key TEXT PRIMARY KEY,
					value TEXT NOT NULL DEFAULT '',
					updated_at INTEGER DEFAULT (strftime('%s', 'now'))
				)`,
				`INSERT OR IGNORE INTO global_settings (key, value) VALUES ('exit_policy', 'allow_all')`,
			}
			for _, q := range queries {
				if _, err := d.Exec(q); err != nil {
					// ALTER TABLE ADD COLUMN may fail if column exists — ignore
					continue
				}
			}
			return nil
}

// migrateV022SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV022PG.
func migrateV022SQLite(d *sql.DB) error {


			// 2026-07-11: Этап 9 part 2 — the original 2026-07-09 statement had
			// `DEFAULT ` with no value, which is a syntax error. The function
			// ignored the error so the migration silently no-op'd, leaving
			// device_rules without device_ip on fresh DBs. Fixed.
			_, err := d.Exec("ALTER TABLE device_rules ADD COLUMN IF NOT EXISTS device_ip TEXT NOT NULL DEFAULT ''")
			if err != nil { return nil } // column exists
			return nil
}

// migrateV023SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV023PG.
func migrateV023SQLite(d *sql.DB) error {


			// 2026-07-09: refactor v0.6.0 — original statement had a syntax error
			// (`DEFAULT ,` with no value) which made the table creation silently
			// fail — the function was invoked without an err check so the migration
			// was a no-op. Production tables were created out-of-band and exist
			// today, but fresh deployments lost this table. Fixed below.
			const q = `CREATE TABLE IF NOT EXISTS personal_api_tokens (
				id INTEGER PRIMARY KEY AUTOINCREMENT,
				user_id INTEGER NOT NULL,
				token_hash TEXT NOT NULL UNIQUE,
				label TEXT NOT NULL DEFAULT '',
				last_used_at INTEGER DEFAULT 0,
				created_at INTEGER DEFAULT (strftime('%s', 'now')),
				FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
			)`
			if _, err := d.Exec(q); err != nil {
				return err
			}
			return nil
}

// migrateV024SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV024PG.
func migrateV024SQLite(d *sql.DB) error {


			queries := []string{
				"ALTER TABLE exit_servers ADD COLUMN IF NOT EXISTS ssh_target TEXT NOT NULL DEFAULT ''",
				"ALTER TABLE exit_servers ADD COLUMN IF NOT EXISTS ssh_key_path TEXT NOT NULL DEFAULT ''",
			}
			for _, q := range queries {
				d.Exec(q) // ignore errors (column may exist)
			}
			return nil
}

// migrateV025SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV025PG.
func migrateV025SQLite(d *sql.DB) error {


			queries := []string{
				`CREATE TABLE IF NOT EXISTS portal_users (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					username TEXT UNIQUE NOT NULL,
					password_hash TEXT NOT NULL,
					is_admin INTEGER NOT NULL DEFAULT 0,
					headscale_user_id INTEGER,
					created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
					theme TEXT NOT NULL DEFAULT 'linear'
				)`,
				`CREATE TABLE IF NOT EXISTS preauth_keys (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					user_id INTEGER NOT NULL,
					key TEXT NOT NULL UNIQUE,
					headscale_preauth_id TEXT DEFAULT '',
					reusable INTEGER NOT NULL DEFAULT 0,
					used INTEGER NOT NULL DEFAULT 0,
					expires_at INTEGER DEFAULT 0,
					created_at INTEGER DEFAULT (strftime('%s', 'now')),
					FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
				)`,
				`CREATE TABLE IF NOT EXISTS devices (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					user_id INTEGER NOT NULL,
					hostname TEXT NOT NULL,
					node_id TEXT DEFAULT '',
					headscale_node_id TEXT DEFAULT '',
					ip_addresses TEXT DEFAULT '',
					os TEXT DEFAULT '',
					last_seen INTEGER DEFAULT 0,
					online INTEGER DEFAULT 0,
					created_at INTEGER DEFAULT (strftime('%s', 'now')),
					FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
				)`,
				`CREATE TABLE IF NOT EXISTS audit_log (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					user_id INTEGER DEFAULT 0,
					username TEXT DEFAULT '',
					action TEXT NOT NULL,
					detail TEXT DEFAULT '',
					ip_address TEXT DEFAULT '',
					created_at INTEGER DEFAULT (strftime('%s', 'now'))
				)`,
				`CREATE TABLE IF NOT EXISTS node_owner_map (
					node_id TEXT PRIMARY KEY,
					headscale_user_id INTEGER NOT NULL DEFAULT 0,
					username TEXT NOT NULL DEFAULT '',
					tag TEXT NOT NULL DEFAULT '',
					tagged_by_user_id INTEGER NOT NULL DEFAULT 0,
					tagged_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
					hostname TEXT NOT NULL DEFAULT ''
				)`,
			}
			for _, q := range queries {
				if _, err := d.Exec(q); err != nil {
					return err
				}
			}
			return nil
}

// migrateV026SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV026PG.
func migrateV026SQLite(d *sql.DB) error {


			stmts := []string{
				"ALTER TABLE exit_servers ADD COLUMN IF NOT EXISTS accept_routes INTEGER NOT NULL DEFAULT 0",
			}
			for _, q := range stmts {
				if _, err := d.Exec(q); err != nil {
					// ignore: column may already exist on a re-run
					continue
				}
			}
			return nil
}

// migrateV027SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV027PG.
func migrateV027SQLite(d *sql.DB) error {


			stmts := []string{
				`CREATE TABLE IF NOT EXISTS telegram_alerts (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					body TEXT NOT NULL,
					sent_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
					acked_at INTEGER NOT NULL DEFAULT 0,
					acked_by TEXT NOT NULL DEFAULT ''
				)`,
				`CREATE INDEX IF NOT EXISTS idx_telegram_alerts_unacked
					ON telegram_alerts(id) WHERE acked_at = 0`,
			}
			for _, q := range stmts {
				if _, err := d.Exec(q); err != nil {
					return err
				}
			}
			return nil
}

// migrateV028SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV028PG.
func migrateV028SQLite(d *sql.DB) error {


			stmts := []string{
				`ALTER TABLE device_rules ADD COLUMN parent_domain TEXT NOT NULL DEFAULT ''`,
				`ALTER TABLE node_owner_map ADD COLUMN username TEXT NOT NULL DEFAULT ''`,
				`ALTER TABLE node_owner_map ADD COLUMN headscale_user_id INTEGER NOT NULL DEFAULT 0`,
				`ALTER TABLE node_owner_map ADD COLUMN tag TEXT NOT NULL DEFAULT ''`,
				`ALTER TABLE node_owner_map ADD COLUMN tagged_by_user_id INTEGER NOT NULL DEFAULT 0`,
				`ALTER TABLE node_owner_map ADD COLUMN tag TEXT NOT NULL DEFAULT ''`, // safe no-op if V028 ran twice
				// 2026-07-15: v0.14.1 — the original V028 ALTER list
				// forgot tagged_at. Production DBs got the column
				// out-of-band (commit a8b07f8 added INSERT OR REPLACE
				// before V028 ran, so a manual ALTER was the only way
				// for a fresh install to work), but the v0.25
				// CREATE+ALTER chain + the v0.14.1 test suite
				// exposed the gap: db.UpsertNodeOwner panics on a
				// fresh DB with "no column named tagged_at". Adding
				// the ALTER here closes the gap for new installs;
				// the _, _ = d.Exec(q) below swallows the "duplicate
				// column" error so the migration stays idempotent on
				// existing installs.
				`ALTER TABLE node_owner_map ADD COLUMN tagged_at INTEGER NOT NULL DEFAULT 0`,
				`ALTER TABLE preauth_keys ADD COLUMN headscale_preauth_id TEXT NOT NULL DEFAULT ''`,
			}
			for _, q := range stmts {
				// SQLite ALTER TABLE ADD COLUMN fails if the column already
				// exists — that's the case on live DBs (the column was
				// created out-of-band). We swallow the error so the
				// migration is idempotent.
				_, _ = d.Exec(q)
			}
			return nil
}

// migrateV029SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV029PG.
func migrateV029SQLite(d *sql.DB) error {


			stmts := []string{
				`CREATE TABLE IF NOT EXISTS telegram_bindings (
					chat_id          INTEGER PRIMARY KEY,
					portal_user_id   INTEGER NOT NULL,
					is_admin         INTEGER NOT NULL DEFAULT 0,
					bound_at         INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
					bound_by_user_id INTEGER NOT NULL DEFAULT 0
				)`,
				`CREATE INDEX IF NOT EXISTS idx_telegram_bindings_user
					ON telegram_bindings(portal_user_id)`,
			}
			for _, q := range stmts {
				if _, err := d.Exec(q); err != nil {
					return err
				}
			}
			return nil
}

// migrateV030SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV030PG.
func migrateV030SQLite(d *sql.DB) error {


			stmts := []string{
				`ALTER TABLE portal_users ADD COLUMN default_device_node_id TEXT NOT NULL DEFAULT ''`,
				`ALTER TABLE portal_users ADD COLUMN default_exit_node_id    TEXT NOT NULL DEFAULT ''`,
			}
			for _, q := range stmts {
				// ALTER TABLE ADD COLUMN returns an error if the column
				// already exists; that's the "migration already applied"
				// signal and we swallow it (same idiom as v0.21/v0.22).
				_, _ = d.Exec(q)
			}
			return nil
}

// migrateV031SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV031PG.
func migrateV031SQLite(d *sql.DB) error {


			stmts := []string{
				`CREATE TABLE IF NOT EXISTS telegram_login_tokens (
					token            TEXT PRIMARY KEY,
					portal_user_id   INTEGER NOT NULL,
					created_at       INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
					expires_at       INTEGER NOT NULL,
					used_at          INTEGER NOT NULL DEFAULT 0,
					used_by_chat_id  INTEGER NOT NULL DEFAULT 0,
					request_ip       TEXT    NOT NULL DEFAULT ''
				)`,
				`CREATE INDEX IF NOT EXISTS idx_telegram_login_tokens_user
					ON telegram_login_tokens(portal_user_id)`,
				`CREATE INDEX IF NOT EXISTS idx_telegram_login_tokens_expiry
					ON telegram_login_tokens(expires_at)`,
				// Default strict_mode = 0 (off) so the migration doesn't
				// surprise existing single-admin-chat deploys. New deploys
				// that want strict mode flip it via /admin/telegram.
				// We use INSERT OR IGNORE so re-running the migration is a
				// no-op (the row already exists from a previous run).
				`INSERT OR IGNORE INTO global_settings (key, value, updated_at)
					VALUES ('telegram.strict_mode', '0', strftime('%s', 'now'))`,
				// Default token TTL = 300s (5 min). Operators can tune via
				// /admin/telegram UI or by editing the global_settings row
				// directly. Stored as a string to keep the schema uniform
				// (all global_settings values are TEXT).
				`INSERT OR IGNORE INTO global_settings (key, value, updated_at)
					VALUES ('telegram.login_token_ttl_seconds', '300', strftime('%s', 'now'))`,
			}
			for _, q := range stmts {
				if _, err := d.Exec(q); err != nil {
					return err
				}
			}
			return nil
}

// migrateV032SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV032PG.
func migrateV032SQLite(d *sql.DB) error {


			stmts := []string{
				`CREATE TABLE IF NOT EXISTS telegram_rate_limit (
					key    TEXT NOT NULL,
					action TEXT NOT NULL DEFAULT '',
					ts     INTEGER NOT NULL
				)`,
				`CREATE INDEX IF NOT EXISTS idx_telegram_rate_limit_lookup
					ON telegram_rate_limit(key, ts)`,
				`CREATE INDEX IF NOT EXISTS idx_telegram_rate_limit_prune
					ON telegram_rate_limit(ts)`,
			}
			for _, q := range stmts {
				if _, err := d.Exec(q); err != nil {
					return err
				}
			}
			return nil
}

// migrateV033SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV033PG.
func migrateV033SQLite(d *sql.DB) error {


			stmts := []string{
				`ALTER TABLE telegram_bindings ADD COLUMN lang TEXT NOT NULL DEFAULT 'en'`,
			}
			for _, q := range stmts {
				// ALTER TABLE ADD COLUMN with a DEFAULT is idempotent
				// in our model: if the column already exists, the
				// statement returns an error and we move on. Fresh
				// DBs get the column with the default; existing DBs
				// silently no-op. Same pattern as the v0.21 ALTER
				// for device_rules.action.
				if _, err := d.Exec(q); err != nil {
					// Column already exists — that's the expected
					// "already migrated" path. Continue.
					continue
				}
			}
			return nil
}

// migrateV034SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV034PG.
func migrateV034SQLite(d *sql.DB) error {


			stmts := []string{
				`ALTER TABLE node_owner_map ADD COLUMN hostname TEXT NOT NULL DEFAULT ''`,
				`CREATE INDEX IF NOT EXISTS idx_node_owner_map_hostname ON node_owner_map (hostname) WHERE hostname != ''`,
			}
			for _, q := range stmts {
				if _, err := d.Exec(q); err != nil {
					// Column / index already exists — that's the
					// "already migrated" path. Continue.
					continue
				}
			}
			return nil
}

// migrateV035SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV035PG.
func migrateV035SQLite(d *sql.DB) error {


			stmts := []string{
				`ALTER TABLE portal_users ADD COLUMN headscale_url TEXT NOT NULL DEFAULT ''`,
				`ALTER TABLE portal_users ADD COLUMN headscale_api_key_enc TEXT NOT NULL DEFAULT ''`,
				`CREATE INDEX IF NOT EXISTS idx_portal_users_hs_url ON portal_users (headscale_url) WHERE headscale_url != ''`,
			}
			for _, q := range stmts {
				if _, err := d.Exec(q); err != nil {
					// Column / index already exists — that's the
					// "already migrated" path. Continue.
					continue
				}
			}
			return nil
}

// migrateV036SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV036PG.
func migrateV036SQLite(d *sql.DB) error {


			stmts := []string{
				// 2026-07-15: v0.13.0 — exit-node health snapshot.
				// `state` is one of: unknown | online | offline | degraded.
				// `degraded` = online + has the tag but routes are not
				// approved (e.g. admin ran --advertise-routes but forgot
				// to approve on headscale, or the approval was rolled
				// back). `healthy` is the combined boolean that the
				// /admin/exit-nodes page renders as a green/red dot.
				`CREATE TABLE IF NOT EXISTS exit_node_health (
					node_id TEXT PRIMARY KEY,
					hostname TEXT NOT NULL DEFAULT '',
					online INTEGER NOT NULL DEFAULT 0,
					last_seen TEXT NOT NULL DEFAULT '',
					advertised_routes_ok INTEGER NOT NULL DEFAULT 0,
					has_exit_tag INTEGER NOT NULL DEFAULT 0,
					state TEXT NOT NULL DEFAULT 'unknown',
					healthy INTEGER NOT NULL DEFAULT 0,
					last_check_at INTEGER NOT NULL DEFAULT 0,
					last_state_change_at INTEGER NOT NULL DEFAULT 0,
					consecutive_failures INTEGER NOT NULL DEFAULT 0
				)`,
				`CREATE INDEX IF NOT EXISTS idx_exit_node_health_state
					ON exit_node_health (state, healthy)`,
				// 2026-07-15: v0.13.0 — state-transition log.
				// Inserted by the monitor on detected transitions
				// (online→offline, offline→online). `alerted_at` is
				// updated to a unix timestamp once the Telegram alert
				// has been queued. The dispatch loop queries
				// `WHERE alerted_at = 0` to find pending alerts.
				`CREATE TABLE IF NOT EXISTS exit_node_state_changes (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					node_id TEXT NOT NULL,
					hostname TEXT NOT NULL DEFAULT '',
					from_state TEXT NOT NULL,
					to_state TEXT NOT NULL,
					detected_at INTEGER NOT NULL,
					alerted_at INTEGER NOT NULL DEFAULT 0,
					note TEXT NOT NULL DEFAULT ''
				)`,
				`CREATE INDEX IF NOT EXISTS idx_exit_node_state_changes_pending
					ON exit_node_state_changes (alerted_at, detected_at)`,
				`CREATE INDEX IF NOT EXISTS idx_exit_node_state_changes_node
					ON exit_node_state_changes (node_id, detected_at DESC)`,
			}
			for _, q := range stmts {
				if _, err := d.Exec(q); err != nil {
					// CREATE IF NOT EXISTS already covers the
					// "already migrated" path; the if-guard is
					// belt-and-suspenders.
					continue
				}
			}
			return nil
}

// migrateV037SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV037PG.
func migrateV037SQLite(d *sql.DB) error {


			stmts := []string{
				`ALTER TABLE personal_api_tokens ADD COLUMN expires_at INTEGER NOT NULL DEFAULT 0`,
				`ALTER TABLE personal_api_tokens ADD COLUMN auto_rotate INTEGER NOT NULL DEFAULT 0`,
				`CREATE INDEX IF NOT EXISTS idx_personal_api_tokens_expires
					ON personal_api_tokens (expires_at)`,
			}
			for _, q := range stmts {
				if _, err := d.Exec(q); err != nil {
					// ALTER TABLE ADD COLUMN fails with "duplicate
					// column" on a re-run; ignore that case (the
					// column already exists, which is fine).
					// CREATE INDEX IF NOT EXISTS is a no-op on
					// re-run, so it shouldn't hit this branch.
					continue
				}
			}
			return nil
}

// migrateV038SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV038PG.
func migrateV038SQLite(d *sql.DB) error {


			stmts := []string{
				// New table: user_subnets. The unique constraints
				// on user_id and cidr let the allocator rely on
				// the DB to prevent duplicate allocations (a
				// second AllocateCIDR call for the same user_id
				// hits the UNIQUE(user_id) and the manager can
				// detect "already allocated" via the error).
				`CREATE TABLE IF NOT EXISTS user_subnets (
					id INTEGER PRIMARY KEY,
					user_id INTEGER NOT NULL UNIQUE,
					cidr TEXT NOT NULL UNIQUE,
					subnet_bits INTEGER NOT NULL DEFAULT 24,
					control_plane_url TEXT NOT NULL DEFAULT '',
					status TEXT NOT NULL DEFAULT 'pending',
					router_node_id TEXT NOT NULL DEFAULT '',
					router_container_id TEXT NOT NULL DEFAULT '',
					router_hostname TEXT NOT NULL DEFAULT '',
					created_at INTEGER NOT NULL,
					updated_at INTEGER NOT NULL,
					FOREIGN KEY (user_id) REFERENCES portal_users(id) ON DELETE CASCADE
				)`,
				// Indexes: the (cidr) UNIQUE in the table definition
				// already creates a unique index; we add plain
				// indexes for the (status) and (control_plane_url)
				// lookups that the manager / bot / admin pages do.
				`CREATE INDEX IF NOT EXISTS idx_user_subnets_status
					ON user_subnets (status)`,
				`CREATE INDEX IF NOT EXISTS idx_user_subnets_plane
					ON user_subnets (control_plane_url)`,
				// Denormalized columns on portal_users. The 3
				// queries that read these columns are:
				//   1. /mysubnet: SELECT subnet_cidr, subnet_status,
				//      subnet_router_node_id FROM portal_users WHERE id = ?
				//   2. /myexitnodes: JOIN against user_subnets via
				//      portal_users.subnet_cidr (for "your default
				//      exit-node can route through your personal
				//      subnet" hint, v0.17.0+)
				//   3. /admin/users/{id} admin page: shows the
				//      subnet_status next to the username
				// Keeping these in portal_users saves a JOIN on the
				// hot path. The user_subnets table is the source
				// of truth; the portal_users columns are kept in
				// sync by the manager (internal/subnet/manager.go).
				`ALTER TABLE portal_users ADD COLUMN subnet_cidr TEXT NOT NULL DEFAULT ''`,
				`ALTER TABLE portal_users ADD COLUMN subnet_status TEXT NOT NULL DEFAULT 'none'`,
				`ALTER TABLE portal_users ADD COLUMN subnet_router_node_id TEXT NOT NULL DEFAULT ''`,
				`CREATE INDEX IF NOT EXISTS idx_portal_users_subnet_status
					ON portal_users (subnet_status)`,
			}
			for _, q := range stmts {
				if _, err := d.Exec(q); err != nil {
					// ALTER TABLE ADD COLUMN fails with "duplicate
					// column" on a re-run; ignore that case (the
					// column already exists, which is fine).
					// CREATE TABLE / INDEX IF NOT EXISTS is a no-op
					// on re-run, so it shouldn't hit this branch.
					continue
				}
			}
			return nil
}

// migrateV039SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV039PG.
func migrateV039SQLite(d *sql.DB) error {


			stmts := []string{
				// The shares table. grantor is the user whose
				// subnet is being shared; grantee is the user
				// who gets access to grantor's subnet.
				`CREATE TABLE IF NOT EXISTS user_subnet_shares (
					grantor_user_id INTEGER NOT NULL,
					grantee_user_id INTEGER NOT NULL,
					created_at INTEGER NOT NULL DEFAULT 0,
					PRIMARY KEY (grantor_user_id, grantee_user_id),
					FOREIGN KEY (grantor_user_id) REFERENCES portal_users(id) ON DELETE CASCADE,
					FOREIGN KEY (grantee_user_id) REFERENCES portal_users(id) ON DELETE CASCADE
				)`,
				// Index on grantee — the ACL builder iterates
				// "for each user, what subnets are shared with
				// them" which is a scan by grantee. The
				// PRIMARY KEY index covers grantor lookups
				// (grantor-side); the grantee-side needs its
				// own index.
				`CREATE INDEX IF NOT EXISTS idx_user_subnet_shares_grantee
					ON user_subnet_shares (grantee_user_id)`,
			}
			for _, s := range stmts {
				if _, err := d.Exec(s); err != nil {
					return err
				}
			}
			return nil
}

// migrateV041SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV041PG.
func migrateV041SQLite(d *sql.DB) error {


			stmts := []string{
				`CREATE TABLE IF NOT EXISTS headscale_releases (
					version TEXT PRIMARY KEY,
					published_at INTEGER NOT NULL DEFAULT 0,
					first_seen_at INTEGER NOT NULL DEFAULT 0,
					html_url TEXT NOT NULL DEFAULT '',
					name TEXT NOT NULL DEFAULT '',
					body TEXT NOT NULL DEFAULT '',
					is_breaking INTEGER NOT NULL DEFAULT 0,
					notified INTEGER NOT NULL DEFAULT 0
				)`,
				// Index on published_at DESC for the
				// /admin/headscale "history" view (newest
				// first). The PRIMARY KEY covers exact
				// lookups; the index covers the range scan
				// the page renders.
				`CREATE INDEX IF NOT EXISTS idx_headscale_releases_published
					ON headscale_releases (published_at DESC)`,
			}
			for _, s := range stmts {
				if _, err := d.Exec(s); err != nil {
					return err
				}
			}
			return nil
}

// migrateV042SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV042PG.
func migrateV042SQLite(d *sql.DB) error {


			stmts := []string{
				`CREATE TABLE IF NOT EXISTS invite_codes (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					code TEXT NOT NULL UNIQUE,
					grantor_user_id INTEGER NOT NULL,
					grantee_username TEXT NOT NULL,
					status TEXT NOT NULL DEFAULT 'active',
					created_at INTEGER NOT NULL DEFAULT 0,
					expires_at INTEGER NOT NULL DEFAULT 0,
					consumed_at INTEGER NOT NULL DEFAULT 0,
					consumed_by_user_id INTEGER NOT NULL DEFAULT 0,
					audit_message TEXT NOT NULL DEFAULT '',
					FOREIGN KEY (grantor_user_id) REFERENCES portal_users(id) ON DELETE CASCADE
				)`,
				// Note: consumed_by_user_id does NOT have
				// an FK because the user may not exist at
				// generation time (we store grantee by
				// username, resolved to id at consume).
				// At consume time the consuming user IS
				// known (they have to be authenticated to
				// reach /accept), so we add a partial FK
				// to gate "consumed but user_id is now
				// gone" cases. Setting to ON DELETE SET
				// DEFAULT 0 keeps the audit trail even if
				// the consumer is later deleted.
				`CREATE INDEX IF NOT EXISTS idx_invite_codes_grantor
					ON invite_codes (grantor_user_id)`,
				`CREATE INDEX IF NOT EXISTS idx_invite_codes_status_expires
					ON invite_codes (status, expires_at)`,
				// Also: lookup by grantee_username (the
				// "show me invites for me" query — the
				// consume path joins on this).
				`CREATE INDEX IF NOT EXISTS idx_invite_codes_grantee
					ON invite_codes (grantee_username)`,
			}
			for _, s := range stmts {
				if _, err := d.Exec(s); err != nil {
					return err
				}
			}
			return nil
}

// migrateV043SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV043PG.
func migrateV043SQLite(d *sql.DB) error {


			stmts := []string{
				`CREATE TABLE IF NOT EXISTS meshes (
					id INTEGER PRIMARY KEY AUTOINCREMENT,
					code TEXT NOT NULL UNIQUE,
					name TEXT NOT NULL DEFAULT '',
					creator_user_id INTEGER NOT NULL,
					status TEXT NOT NULL DEFAULT 'active',
					created_at INTEGER NOT NULL DEFAULT 0,
					dissolved_at INTEGER NOT NULL DEFAULT 0,
					FOREIGN KEY (creator_user_id) REFERENCES portal_users(id) ON DELETE CASCADE
				)`,
				`CREATE TABLE IF NOT EXISTS mesh_members (
					mesh_id INTEGER NOT NULL,
					user_id INTEGER NOT NULL,
					joined_at INTEGER NOT NULL DEFAULT 0,
					PRIMARY KEY (mesh_id, user_id),
					FOREIGN KEY (mesh_id) REFERENCES meshes(id) ON DELETE CASCADE,
					FOREIGN KEY (user_id) REFERENCES portal_users(id) ON DELETE CASCADE
				)`,
				// Lookups:
				//   - "which meshes does user U belong to" → idx_mesh_members_user
				//   - "which users are in mesh M" → idx_mesh_members_mesh (PK already covers)
				//   - "find a mesh by its code" → UNIQUE on meshes.code (PK-like)
				`CREATE INDEX IF NOT EXISTS idx_mesh_members_user
					ON mesh_members (user_id)`,
			}
			for _, s := range stmts {
				if _, err := d.Exec(s); err != nil {
					return err
				}
			}
			return nil
}

// migrateV044SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV044PG.
func migrateV044SQLite(d *sql.DB) error {


			// PG 9.6+ supports ADD COLUMN IF NOT EXISTS natively,
			// which is the atomic way to make this idempotent. The
			// pre-v0.32.24 code used a PRAGMA table_info-based
			// `hasColumn` check (a SQLite idiom that didn't work on
			// PG); v0.32.24 replaces it with IF NOT EXISTS.
			if _, err := d.Exec(`ALTER TABLE device_rules ADD COLUMN user_name TEXT NOT NULL DEFAULT ''`); err != nil {
				return fmt.Errorf("v0.44 add user_name: %w", err)
			}
			if _, err := d.Exec(`ALTER TABLE device_rules ADD COLUMN device_hostname TEXT NOT NULL DEFAULT ''`); err != nil {
				return fmt.Errorf("v0.44 add device_hostname: %w", err)
			}
			// Backfill user_name from portal_users. Every
			// device_rules row has a non-zero user_id (the FK
			// is NOT NULL); the portal_users row might be gone
			// in pathological cleanup cases, in which case we
			// leave user_name empty and the ACL builder falls
			// back to device_ip.
			if _, err := d.Exec(`
				`); err != nil {
				return fmt.Errorf("v0.44 backfill user_name: %w", err)
			}
			// device_hostname is NOT backfilled here — node_owner_map
			// has no tailscale_ip column to JOIN on. The runtime
			// backfill happens in handlers.backfillNodeOwnership
			// on the next /my/devices load (the function knows the
			// device hostname from headscale's list response).
			// For pre-v0.28.0 rules, the ACL builder falls back to
			// src=device_ip until the runtime backfill lands, so
			// the rules are live immediately and switch to the
			// tag-based src transparently on the next /my/devices
			// load.
			return nil
}

// migrateV045SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV045PG.
func migrateV045SQLite(d *sql.DB) error {


			// 2026-07-24: v0.28.1 — user_exit_node_prefs table.
			// One row per user (PK on user_id). Cascade on user
			// delete is intentional: a deleted user has no
			// preference. exit_node_tag is the headscale tag
			// (e.g. "tag:exit-relay-1") — NOT the hostname, NOT
			// the node id. The tag is what `grants[].via` takes.
			const q = `CREATE TABLE IF NOT EXISTS user_exit_node_prefs (
				user_id INTEGER NOT NULL PRIMARY KEY,
				exit_node_tag TEXT NOT NULL,
				set_by_user_id INTEGER NOT NULL DEFAULT 0,
				updated_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
				FOREIGN KEY (user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`
			if _, err := d.Exec(q); err != nil {
				return err
			}
			return nil
}

// migrateV046SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV046PG.
func migrateV046SQLite(d *sql.DB) error {


			// 2026-07-25: v0.28.4 — device_exit_node_prefs table.
			// One row per (user_id, device_hostname). Composite
			// primary key enforces uniqueness. Cascade on user
			// delete is intentional: a deleted user has no
			// device prefs (their devices are also gone).
			//
			// device_hostname is the lowercase form (matches the
			// v0.28.0 backfill's tag:dev-<user>-<device> naming).
			// The UI normalizes input to lowercase before the
			// INSERT so case differences don't create duplicate
			// rows for the same device.
			//
			// exit_node_tag is the headscale tag (e.g.
			// "tag:exit-relay-3") — NOT the hostname, NOT the
			// node id. The tag is what `grants[].via` takes.
			const q = `CREATE TABLE IF NOT EXISTS device_exit_node_prefs (
				user_id INTEGER NOT NULL,
				device_hostname TEXT NOT NULL,
				exit_node_tag TEXT NOT NULL,
				set_by_user_id INTEGER NOT NULL DEFAULT 0,
				updated_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
				PRIMARY KEY (user_id, device_hostname),
				FOREIGN KEY (user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`
			if _, err := d.Exec(q); err != nil {
				return err
			}
			return nil
}

// migrateV047SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV047PG.
func migrateV047SQLite(d *sql.DB) error {


			// v0.32.24: on PG, ALTER TABLE ADD COLUMN IF NOT EXISTS
			// is the atomic way to add a column idempotently.
			// The pre-fix code used the SQLite-style "try ALTER
			// and catch the duplicate-column error" pattern
			// via the shared `addViaEnabledUserPrefSQL` const
			// (in migrations_v0.47.go) + `isSQLiteDuplicateColumnError`
			// helper — both SQLite-isms that don't work on PG
			// (PG returns SQLSTATE 42701 not a string message).
			// We inline the IF NOT EXISTS form here so the
			// freshlyAdded heuristic isn't needed.
			//
			// For the backfill logic: if the column already exists
			// (IF NOT EXISTS makes the ALTER a no-op), we still
			// run the backfill ONLY on the first deploy — see
			// the freshlyAdded check below. We detect "already
			// existed" via information_schema instead of error
			// matching.
			colExists := func(table, col string) bool {
				// 2026-09-18: this used to query
				// `information_schema.columns` — a POSTGRESQL catalog
				// — from inside the SQLITE migration chain. The scan
				// error was swallowed (`return false`), so colExists
				// always reported "does not exist" and the
				// freshlyAdded heuristic was permanently true.
				//
				// This file only ever runs against SQLite, so the
				// correct probe is PRAGMA table_info. The table name is
				// a hardcoded literal at every call site (no user
				// input), so the interpolation is safe.
				rows, err := d.Query(`PRAGMA table_info(` + table + `)`)
				if err != nil {
					return false
				}
				defer rows.Close()
				for rows.Next() {
					var cid, notnull, pk int
					var name, ctype string
					var dflt any
					if err := rows.Scan(&cid, &name, &ctype, &notnull, &dflt, &pk); err != nil {
						return false
					}
					if name == col {
						return true
					}
				}
				return false
			}
			freshlyAdded := !colExists("user_exit_node_prefs", "via_enabled")
			if _, err := d.Exec(`ALTER TABLE user_exit_node_prefs ADD COLUMN via_enabled INTEGER NOT NULL DEFAULT 0`); err != nil {
				return err
			}
			if !colExists("device_exit_node_prefs", "via_enabled") && freshlyAdded {
				freshlyAdded = true
			}
			if _, err := d.Exec(`ALTER TABLE device_exit_node_prefs ADD COLUMN via_enabled INTEGER NOT NULL DEFAULT 0`); err != nil {
				return err
			}
			// Backfill ONLY on the first-time migration. On
			// every subsequent startup, skip the UPDATE so
			// the operator's via_enabled=0 (un-pinned) is
			// preserved across restarts.
			if !freshlyAdded {
				return nil
			}
			// Backfill existing rows: every row that was
			// created under v0.28.1 / v0.28.4 had the
			// pinning enforced. Preserve that behavior on
			// upgrade (the operator has to explicitly flip
			// the flag to un-pin). The UPDATE is a no-op on
			// a fresh install (column defaults to 0).
			if _, err := d.Exec(`UPDATE user_exit_node_prefs SET via_enabled = 1 WHERE via_enabled = 0`); err != nil {
				return err
			}
			if _, err := d.Exec(`UPDATE device_exit_node_prefs SET via_enabled = 1 WHERE via_enabled = 0`); err != nil {
				return err
			}
			return nil
}

// migrateV048SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV048PG.
func migrateV048SQLite(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE node_owner_map ADD COLUMN os TEXT NOT NULL DEFAULT 'unknown'`,
			`ALTER TABLE node_owner_map ADD COLUMN device_type TEXT NOT NULL DEFAULT 'unknown'`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.48: %w", err)
			}
		}
		return nil
}

// migrateV049SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV049PG.
func migrateV049SQLite(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS applied_migrations (
				version     INTEGER PRIMARY KEY,
				sha256      TEXT    NOT NULL,
				source_file TEXT    NOT NULL DEFAULT '',
				applied_at  INTEGER  NOT NULL DEFAULT (strftime('%s', 'now')),
				first_seen  TEXT    NOT NULL DEFAULT ''
			)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.49: %w", err)
			}
		}
		return nil
}

// migrateV050SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV050PG.
func migrateV050SQLite(d *sql.DB) error {

		stmts := []string{
			``,
			`CREATE TABLE IF NOT EXISTS headscale_acl_rules (
				id                  TEXT    PRIMARY KEY,
				rule_json           TEXT    NOT NULL,
				fingerprint         TEXT    NOT NULL,
				label               TEXT    NOT NULL DEFAULT '',
				created_at          INTEGER  NOT NULL DEFAULT (strftime('%s', 'now')),
				created_by_user_id  INTEGER NOT NULL DEFAULT 0,
				enabled             INTEGER NOT NULL DEFAULT 1,
				UNIQUE(fingerprint, enabled)
			)`,
			`CREATE INDEX IF NOT EXISTS idx_headscale_acl_enabled
				ON headscale_acl_rules(enabled, created_at DESC)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.50: %w", err)
			}
		}
		return nil
}

// migrateV051SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV051PG.
func migrateV051SQLite(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS system_tests_runs (
				id                     INTEGER PRIMARY KEY AUTOINCREMENT,
				started_at             INTEGER  NOT NULL DEFAULT (strftime('%s', 'now')),
				finished_at            INTEGER  NOT NULL DEFAULT 0,
				duration_ms            INTEGER  NOT NULL DEFAULT 0,
				results_json           TEXT    NOT NULL DEFAULT '{}',
				pass_count             INTEGER NOT NULL DEFAULT 0,
				fail_count             INTEGER NOT NULL DEFAULT 0,
				skip_count             INTEGER NOT NULL DEFAULT 0,
				triggered_by_user_id   INTEGER NOT NULL DEFAULT 0
			)`,
			`CREATE INDEX IF NOT EXISTS idx_system_tests_runs_started
				ON system_tests_runs(started_at DESC)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.51: %w", err)
			}
		}
		return nil
}

// migrateV053SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV053PG.
func migrateV053SQLite(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE exit_servers ADD COLUMN ssh_port TEXT NOT NULL DEFAULT ''`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.53: %w", err)
			}
		}
		return nil
}

// migrateV054SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV054PG.
func migrateV054SQLite(d *sql.DB) error {

		var n int
		if err := d.QueryRow(
			`SELECT count(*) FROM portal_users WHERE username = ?`,
			"infra",
		).Scan(&n); err != nil {
			return fmt.Errorf("v0.54: check infra: %w", err)
		}
		if n > 0 {
			return nil
		}
		// bcrypt hash of the literal "infra-never-logs-in-via-web-2026-08-10"
		// — pre-computed so we don't pull golang.org/x/crypto/bcrypt
		// into the PG build path. The 'infra' user is never meant
		// to log in; the hash just ensures bcrypt comparison fails
		// fast if anyone tries.
		const infraHash = "$2a$10$xe4ygoIks1PTpz0aO1jhKeUWTvj2bYQRgoSZE9fyKp6GR8dx7d8oa"
		if _, err := d.Exec(
			`INSERT OR IGNORE INTO portal_users (id, username, password_hash, is_admin) VALUES (99, ?, ?, 0)`,
			"infra", infraHash,
		); err != nil {
			return fmt.Errorf("v0.54: insert infra: %w", err)
		}
		return nil
}

// migrateV055SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV055PG.
func migrateV055SQLite(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS derp_relays (
				id INTEGER PRIMARY KEY AUTOINCREMENT,
				hostname TEXT NOT NULL,
				url TEXT NOT NULL,
				region_id INTEGER NOT NULL DEFAULT 900,
				region_code TEXT NOT NULL DEFAULT '',
				region_name TEXT NOT NULL DEFAULT '',
				is_bundled INTEGER NOT NULL DEFAULT 0,
				enabled INTEGER NOT NULL DEFAULT 1,
				sort_order INTEGER NOT NULL DEFAULT 100,
				notes TEXT NOT NULL DEFAULT '',
				created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
				updated_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
			)`,
			`CREATE UNIQUE INDEX IF NOT EXISTS derp_relays_url_uniq
				ON derp_relays(url)`,
			`CREATE INDEX IF NOT EXISTS derp_relays_enabled_idx
				ON derp_relays(enabled)`,
			`CREATE INDEX IF NOT EXISTS derp_relays_is_bundled_idx
				ON derp_relays(is_bundled) WHERE is_bundled = 1`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.55 derp_relays: %w", err)
			}
		}
		return nil
}

// migrateV056SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV056PG.
func migrateV056SQLite(d *sql.DB) error {

		stmts := []string{
			`CREATE UNIQUE INDEX IF NOT EXISTS device_rules_natural_key_uniq
				ON device_rules(user_id, device_id, exit_node_id, target_type, target_value, parent_domain)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.56 device_rules UNIQUE INDEX: %w", err)
			}
		}
		return nil
}

// migrateV057SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV057PG.
func migrateV057SQLite(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE portal_users ADD COLUMN font_family TEXT NOT NULL DEFAULT 'manrope'`,
			`ALTER TABLE portal_users ADD COLUMN font_scale INTEGER NOT NULL DEFAULT 0`,
			`ALTER TABLE portal_users ADD COLUMN selection_bg TEXT NOT NULL DEFAULT ''`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.57 portal_users display prefs: %w", err)
			}
		}
		return nil
}

// migrateV058SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV058PG.
func migrateV058SQLite(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE preauth_keys ADD COLUMN notified_at INTEGER NOT NULL DEFAULT 0`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.58 preauth_keys notified_at: %w", err)
			}
		}
		return nil
}

// migrateV059SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV059PG.
func migrateV059SQLite(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS notifications (
				id INTEGER PRIMARY KEY AUTOINCREMENT,
				user_id INTEGER NOT NULL,
				type TEXT NOT NULL,
				severity TEXT NOT NULL DEFAULT 'info',
				title TEXT NOT NULL,
				body TEXT NOT NULL DEFAULT '',
				link TEXT NOT NULL DEFAULT '',
				created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
				read_at INTEGER NOT NULL DEFAULT 0,
				FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
			)`,
			`CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
				ON notifications(user_id, read_at)`,
			`CREATE INDEX IF NOT EXISTS idx_notifications_user_created
				ON notifications(user_id, created_at DESC)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.59 notifications: %w", err)
			}
		}
		return nil
}

// migrateV060SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV060PG.
func migrateV060SQLite(d *sql.DB) error {

		stmts := []string{
			// Step 1: dedup existing rows by natural key. The
			// ORDER BY picks the winner — cdn: prefix first
			// (most informative), then most recent id.
			// The DELETE removes all losers (rn > 1).
			`DELETE FROM device_rules
			 WHERE id IN (
			   SELECT id FROM (
			     SELECT id,
			       ROW_NUMBER() OVER (
			         PARTITION BY user_id, device_id, exit_node_id, target_type, target_value
			         ORDER BY
			           CASE WHEN parent_domain LIKE 'cdn:%' THEN 0 ELSE 1 END,
			           id DESC
			       ) AS rn
			     FROM device_rules
			   ) ranked
			   WHERE rn > 1
			 )`,
			// Step 2: drop the old 6-column index
			`DROP INDEX IF EXISTS device_rules_natural_key_uniq`,
			// Step 3: create the new 5-column index (without
			// parent_domain). Same name so ON CONFLICT clauses
			// can target it by name if needed.
			`CREATE UNIQUE INDEX IF NOT EXISTS device_rules_natural_key_uniq
				ON device_rules(user_id, device_id, exit_node_id, target_type, target_value)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.60 device_rules natural-key drop parent_domain: %w", err)
			}
		}
		return nil
}

// migrateV061SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV061PG.
func migrateV061SQLite(d *sql.DB) error {

		// Step 1: user_exit_node_prefs backfill.
		// We can't use a simple JOIN+UPDATE in PG (UPDATE
		// ... FROM is allowed, but the read-side aliasing
		// for the tag rewrite is more readable as two
		// SELECTs). Walk every legacy row, compute the
		// canonical tag, and UPDATE if the lookup
		// succeeded. Rows where the hostname doesn't
		// resolve to a node_owner_map entry are skipped
		// (they keep the legacy tag; the operator can
		// clean up via SQL).
		if _, err := d.Exec(`
			`); err != nil {
			return fmt.Errorf("v0.61 user_exit_node_prefs tag backfill: %w", err)
		}
		// Step 2: device_exit_node_prefs backfill (same
		// logic, different table).
		if _, err := d.Exec(`
			`); err != nil {
			return fmt.Errorf("v0.61 device_exit_node_prefs tag backfill: %w", err)
		}
		// Step 3: re-enable via pinning for rows whose
		// tag is a real headscale tag (tag:dev-infra-*
		// is the post-B118 convention; tag:exit-node is
		// the static catch-all that doesn't need via
		// because it's not a per-host pin).
		//
		// Only flip rows that:
		//   - currently have via_enabled=0 (don't
		//     disturb rows the operator explicitly
		//     opted out of post-B188)
		//   - point at a real headscale tag (the
		//     policy parser will reject any other
		//     form, so we leave them un-pinned)
		if _, err := d.Exec(`
			UPDATE user_exit_node_prefs
			   SET via_enabled = 1
			 WHERE via_enabled = 0
			   AND exit_node_tag LIKE 'tag:dev-infra-%'
		`); err != nil {
			return fmt.Errorf("v0.61 user_exit_node_prefs via_enabled backfill: %w", err)
		}
		if _, err := d.Exec(`
			UPDATE device_exit_node_prefs
			   SET via_enabled = 1
			 WHERE via_enabled = 0
			   AND exit_node_tag LIKE 'tag:dev-infra-%'
		`); err != nil {
			return fmt.Errorf("v0.61 device_exit_node_prefs via_enabled backfill: %w", err)
		}
		return nil
}

// migrateV062SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV062PG.
func migrateV062SQLite(d *sql.DB) error {

		if _, err := d.Exec(`
			CREATE TABLE IF NOT EXISTS derp_health (
				region_id     INTEGER PRIMARY KEY,
				is_own        INTEGER NOT NULL DEFAULT 0,
				host          TEXT    NOT NULL DEFAULT '',
				url           TEXT    NOT NULL DEFAULT '',
				region_code   TEXT    NOT NULL DEFAULT '',
				region_name   TEXT    NOT NULL DEFAULT '',
				locality      TEXT    NOT NULL DEFAULT '',
				country       TEXT    NOT NULL DEFAULT '',
				latency_ms    INTEGER,
				last_check    INTEGER NOT NULL DEFAULT 0,
				healthy       INTEGER NOT NULL DEFAULT 0,
				last_error    TEXT    NOT NULL DEFAULT '',
				probes_total  INTEGER NOT NULL DEFAULT 0,
				probes_failed INTEGER NOT NULL DEFAULT 0
			)
		`); err != nil {
			return fmt.Errorf("v0.62 derp_health table: %w", err)
		}
		return nil
}

// migrateV063SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV063PG.
func migrateV063SQLite(d *sql.DB) error {

		queries := []string{
			`CREATE TABLE IF NOT EXISTS deploy_runs (
				id          INTEGER PRIMARY KEY AUTOINCREMENT,
				type        TEXT NOT NULL,
				status      TEXT NOT NULL,
				started_at  INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
				finished_at INTEGER,
				operator    TEXT NOT NULL DEFAULT '',
				form_data   TEXT NOT NULL DEFAULT '',
				hostname    TEXT NOT NULL DEFAULT '',
				error       TEXT
			)`,
			`CREATE TABLE IF NOT EXISTS deploy_run_steps (
				id          INTEGER PRIMARY KEY AUTOINCREMENT,
				run_id      INTEGER NOT NULL REFERENCES deploy_runs(id) ON DELETE CASCADE,
				step_name   TEXT NOT NULL,
				ordinal     INT  NOT NULL,
				status      TEXT NOT NULL,
				started_at  INTEGER,
				finished_at INTEGER,
				duration_ms INTEGER NOT NULL DEFAULT 0,
				logs        TEXT NOT NULL DEFAULT '[]',
				error       TEXT,
				metadata    TEXT,
				UNIQUE(run_id, step_name)
			)`,
			`CREATE INDEX IF NOT EXISTS idx_deploy_runs_started ON deploy_runs(started_at DESC)`,
			`CREATE INDEX IF NOT EXISTS idx_deploy_runs_hostname ON deploy_runs(hostname)`,
			`CREATE INDEX IF NOT EXISTS idx_deploy_run_steps_run ON deploy_run_steps(run_id, ordinal)`,
		}
		for _, q := range queries {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV064SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV064PG.
func migrateV064SQLite(d *sql.DB) error {

		queries := []string{
			// cluster — definition of one cluster
			`CREATE TABLE IF NOT EXISTS cluster (
				id          TEXT PRIMARY KEY,
				name        TEXT NOT NULL DEFAULT '',
				chain       TEXT NOT NULL DEFAULT '[]',
				created_at  INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
				updated_at  INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
			)`,

			// cluster_node — one node in a cluster
			`CREATE TABLE IF NOT EXISTS cluster_node (
				id              TEXT PRIMARY KEY,
				cluster_id      TEXT NOT NULL REFERENCES cluster(id) ON DELETE CASCADE,
				hostname        TEXT NOT NULL DEFAULT '',
				tailscale_ip    TEXT,
				roles           TEXT[] NOT NULL DEFAULT '{}',
				state           TEXT NOT NULL DEFAULT 'pending',
				skygate_version TEXT NOT NULL DEFAULT '',
				joined_at       INTEGER,
				last_seen_at    INTEGER,
				created_at      INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
				updated_at      INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
			)`,
			`CREATE INDEX IF NOT EXISTS idx_cluster_node_cluster ON cluster_node(cluster_id)`,
			`CREATE INDEX IF NOT EXISTS idx_cluster_node_state ON cluster_node(state) WHERE state IN ('pending', 'draining', 'failed')`,

			// cluster_database — one DB cluster, with primary + replicas
			`CREATE TABLE IF NOT EXISTS cluster_database (
				id                TEXT PRIMARY KEY,
				cluster_id        TEXT NOT NULL REFERENCES cluster(id) ON DELETE CASCADE,
				primary_node_id   TEXT REFERENCES cluster_node(id) ON DELETE SET NULL,
				replica_node_ids   TEXT[] NOT NULL DEFAULT '{}',
				dsn_template      TEXT NOT NULL DEFAULT '',
				dbname            TEXT NOT NULL DEFAULT '',
				username          TEXT NOT NULL DEFAULT '',
				sslmode           TEXT NOT NULL DEFAULT 'disable',
				current_dsn       TEXT NOT NULL DEFAULT '',
				updated_by        TEXT NOT NULL DEFAULT '',
				created_at        INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
				updated_at        INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
			)`,
			`CREATE INDEX IF NOT EXISTS idx_cluster_database_cluster ON cluster_database(cluster_id)`,
			`CREATE INDEX IF NOT EXISTS idx_cluster_database_primary ON cluster_database(primary_node_id) WHERE primary_node_id IS NOT NULL`,

			// cluster_migration — DDL migration history (D6)
			`CREATE TABLE IF NOT EXISTS cluster_migration (
				id              INTEGER PRIMARY KEY AUTOINCREMENT,
				cluster_id      TEXT NOT NULL REFERENCES cluster(id) ON DELETE CASCADE,
				database_id     TEXT NOT NULL REFERENCES cluster_database(id) ON DELETE CASCADE,
				version         TEXT NOT NULL,
				description     TEXT NOT NULL DEFAULT '',
				applied_at      INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
				applied_by_node TEXT NOT NULL DEFAULT '',
				checksum        TEXT NOT NULL DEFAULT '',
				duration_ms     INTEGER NOT NULL DEFAULT 0,
				UNIQUE (database_id, version)
			)`,
			`CREATE INDEX IF NOT EXISTS idx_cluster_migration_db ON cluster_migration(database_id, applied_at DESC)`,

			// cluster_invite — pending node invites (D4)
			`CREATE TABLE IF NOT EXISTS cluster_invite (
				id              TEXT PRIMARY KEY,
				cluster_id      TEXT NOT NULL REFERENCES cluster(id) ON DELETE CASCADE,
				role            TEXT NOT NULL DEFAULT '',
				target_hostname TEXT NOT NULL DEFAULT '',
				issued_at       INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
				expires_at      INTEGER NOT NULL,
				used_at         INTEGER,
				used_by_node_id TEXT,
				signature       TEXT NOT NULL DEFAULT '',
				status          TEXT NOT NULL DEFAULT 'pending'
			)`,
			`CREATE INDEX IF NOT EXISTS idx_cluster_invite_status ON cluster_invite(status, expires_at)`,

			// cluster_audit — admin actions log
			`CREATE TABLE IF NOT EXISTS cluster_audit (
				id              INTEGER PRIMARY KEY AUTOINCREMENT,
				cluster_id      TEXT NOT NULL DEFAULT '',
				actor           TEXT NOT NULL DEFAULT 'system',
				action          TEXT NOT NULL,
				target_node_id  TEXT NOT NULL DEFAULT '',
				detail          TEXT,
				result          TEXT NOT NULL DEFAULT 'ok',
				error_message   TEXT NOT NULL DEFAULT '',
				created_at      INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
			)`,
			`CREATE INDEX IF NOT EXISTS idx_cluster_audit_cluster_time ON cluster_audit(cluster_id, created_at DESC)`,
			`CREATE INDEX IF NOT EXISTS idx_cluster_audit_action ON cluster_audit(action, created_at DESC)`,
		}
		for _, q := range queries {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV065SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV065PG.
func migrateV065SQLite(d *sql.DB) error {

		queries := []string{
			`CREATE TABLE IF NOT EXISTS dbmigrate_run (
				id          INTEGER PRIMARY KEY AUTOINCREMENT,
				cluster_id  TEXT NOT NULL DEFAULT 'skygate-staging',
				source_dsn  TEXT NOT NULL DEFAULT '',
				target_dsn  TEXT NOT NULL DEFAULT '',
				operator    TEXT NOT NULL DEFAULT '',
				status      TEXT NOT NULL DEFAULT 'pending',
				started_at  INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
				finished_at INTEGER,
				error       TEXT NOT NULL DEFAULT '',
				created_at  INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
			)`,
			`CREATE INDEX IF NOT EXISTS idx_dbmigrate_run_started ON dbmigrate_run(started_at DESC)`,
			`CREATE INDEX IF NOT EXISTS idx_dbmigrate_run_status ON dbmigrate_run(status)`,
			`CREATE TABLE IF NOT EXISTS dbmigrate_step (
				id          INTEGER PRIMARY KEY AUTOINCREMENT,
				run_id      INTEGER NOT NULL REFERENCES dbmigrate_run(id) ON DELETE CASCADE,
				step_name   TEXT NOT NULL,
				ordinal     INT NOT NULL,
				status      TEXT NOT NULL DEFAULT 'pending',
				started_at  INTEGER,
				finished_at INTEGER,
				duration_ms INTEGER NOT NULL DEFAULT 0,
				logs        TEXT NOT NULL DEFAULT '[]',
				error       TEXT NOT NULL DEFAULT '',
				metadata    TEXT,
				UNIQUE(run_id, step_name)
			)`,
			`CREATE INDEX IF NOT EXISTS idx_dbmigrate_step_run ON dbmigrate_step(run_id, ordinal)`,
		}
		for _, q := range queries {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV066SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV066PG.
func migrateV066SQLite(d *sql.DB) error {

		stmts := []string{
			// 1. The UNIQUE constraint itself, idempotent.
			``,
			// 2. The matching index (PG creates one
			//    automatically for the UNIQUE constraint
			//    above, but we add a separate CREATE
			//    IF NOT EXISTS so a DB that was created
			//    with a column-list UNIQUE in the CREATE
			//    TABLE (B195) and now has both an
			//    automatically-named index AND this
			//    constraint won't see a duplicate-index
			//    error). The IF NOT EXISTS is a no-op
			//    when PG already has the constraint's
			//    backing index.
			`CREATE UNIQUE INDEX IF NOT EXISTS idx_cluster_node_cluster_hostname
			   ON cluster_node (cluster_id, hostname)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return err
			}
		}
		return nil
}

// migrateV067SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV067PG.
func migrateV067SQLite(d *sql.DB) error {

		stmts := []string{
			// target_type: discriminator (e.g.
			// "cluster_node", "cluster_invite",
			// "cluster_database", "device",
			// "acl", "user"). Empty for the
			// pre-B221 rows.
			`ALTER TABLE audit_log ADD COLUMN target_type TEXT DEFAULT ''`,
			// target_id: the entity id (hostname for
			// cluster_node, invite_id for
			// cluster_invite, cluster_id for
			// cluster_database, user_id for
			// portal_users, etc.). Empty for
			// pre-B221 rows.
			`ALTER TABLE audit_log ADD COLUMN target_id TEXT DEFAULT ''`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return err
			}
		}
		return nil
}

// migrateV068SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV068PG.
func migrateV068SQLite(d *sql.DB) error {

		// Step 1: pre-flight duplicate check on the 6-tuple
		// (the V056 contract). If any (user, device, exit,
		// type, value, parent) appears more than once, refuse
		// to DROP the index — the CREATE would fail anyway,
		// and the operator should clean up duplicates first.
		var dupCount int
		if err := d.QueryRow(`
			SELECT COUNT(*) FROM (
				SELECT 1
				  FROM device_rules
				 GROUP BY user_id, device_id, exit_node_id,
				          target_type, target_value, parent_domain
				HAVING COUNT(*) > 1
				 LIMIT 1
			) AS dup
		`).Scan(&dupCount); err != nil {
			return fmt.Errorf("v0.68 (B232) pre-flight duplicate check: %w", err)
		}
		if dupCount > 0 {
			return fmt.Errorf("v0.68 (B232) pre-flight FAILED: device_rules has 6-tuple duplicates. Run scripts/check_b125.sh for the cleanup audit; deduplicate before re-running migrateV068PG")
		}

		// Step 2: DROP + recreate. CREATE UNIQUE INDEX IF NOT
		// EXISTS is a no-op when the index name exists with
		// a different shape, so we must DROP first. The
		// pre-flight check above ensures the CREATE will
		// succeed (no duplicates on the 6-tuple).
		stmts := []string{
			`DROP INDEX IF EXISTS device_rules_natural_key_uniq`,
			`CREATE UNIQUE INDEX device_rules_natural_key_uniq
				ON device_rules(user_id, device_id, exit_node_id,
				                target_type, target_value, parent_domain)`,
			`ANALYZE device_rules`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return fmt.Errorf("v0.68 (B232) stmt %q: %w", s[:60], err)
			}
		}
		return nil
}

// migrateV069SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV069PG.
func migrateV069SQLite(d *sql.DB) error {

		// Step 1: add the `name` column. NOT NULL with
		// DEFAULT '' so existing rows are valid without
		// backfill — the next ProbeAll tick will populate
		// it from FetchPublicDERPs.
		if _, err := d.Exec(`
			ALTER TABLE derp_health ADD COLUMN name TEXT NOT NULL DEFAULT ''
		`); err != nil {
			return err
		}
		return nil
}

// migrateV070SQLite is the SQLite reverse-port of the PG migration.
// Generated by port_migrations_sqlite.py from migrateV070PG.
func migrateV070SQLite(d *sql.DB) error {

		// 1. Create-or-replace the trigger function. Runs
		//    on each AFTER UPDATE of portal_users. Skips
		//    rows where password_hash is unchanged (e.g.
		//    updating only is_admin / username / theme)
		//    so the audit_log stays focused on actual
		//    credential changes.
		if _, err := d.Exec(`

		`); err != nil {
			return err
		}
		// 2. Drop + recreate the trigger. DROP IF EXISTS
		//    makes the migration idempotent (re-running
		//    re-attaches the trigger with the latest
		//    function body).
		if _, err := d.Exec(`

		`); err != nil {
			return err
		}
		if _, err := d.Exec(`

		`); err != nil {
			return err
		}
		return nil
}
