// Code generated by port_migrations_pg.py; DO NOT EDIT.
// This is a mechanical port of the SQLite migrations to PostgreSQL.
// Review the file and resolve any TODO comments by hand.

package db

import "database/sql"

// migrateV020PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV020PG(d *sql.DB) error {

		queries := []string{
			`CREATE TABLE IF NOT EXISTS exit_servers (
				id BIGSERIAL PRIMARY KEY,
				node_id TEXT NOT NULL UNIQUE,
				hostname TEXT NOT NULL,
				tailscale_ip TEXT NOT NULL DEFAULT '',
				description TEXT DEFAULT '',
				enabled INTEGER DEFAULT 1,
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
			)`,
			`CREATE TABLE IF NOT EXISTS device_rules (
				id BIGSERIAL PRIMARY KEY,
				user_id INTEGER NOT NULL,
				device_id INTEGER NOT NULL,
				exit_node_id TEXT NOT NULL,
				target_type TEXT NOT NULL DEFAULT 'domain',
				target_value TEXT NOT NULL,
				enabled INTEGER DEFAULT 1,
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
			)`,
			`CREATE TABLE IF NOT EXISTS acl_snapshots (
				id BIGSERIAL PRIMARY KEY,
				version INTEGER NOT NULL,
				config TEXT NOT NULL,
				created_by TEXT NOT NULL,
				applied_success INTEGER DEFAULT NULL,
				error_msg TEXT DEFAULT '',
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
			)`,
			`CREATE TABLE IF NOT EXISTS exit_rule_logs (
				id BIGSERIAL PRIMARY KEY,
				version INTEGER NOT NULL,
				action TEXT NOT NULL,
				detail TEXT DEFAULT '',
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
			)`,
		}
		for _, q := range queries {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV021PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV021PG(d *sql.DB) error {

		queries := []string{
			`ALTER TABLE device_rules ADD COLUMN action TEXT NOT NULL DEFAULT 'accept'`,
			`CREATE TABLE IF NOT EXISTS global_settings (
				key TEXT PRIMARY KEY,
				value TEXT NOT NULL DEFAULT '',
				updated_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
			)`,
			`INSERT INTO global_settings (key, value) VALUES ('exit_policy', 'allow_all') ON CONFLICT (key) DO NOTHING`,
		}
		for _, q := range queries {
			if _, err := d.Exec(q); err != nil {
				// ALTER TABLE ADD COLUMN may fail if column exists — ignore
				continue
			}
		}
		return nil
}

// migrateV022PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV022PG(d *sql.DB) error {

		// 2026-07-11: Этап 9 part 2 — the original 2026-07-09 statement had
		// `DEFAULT ` with no value, which is a syntax error. The function
		// ignored the error so the migration silently no-op'd, leaving
		// device_rules without device_ip on fresh DBs. Fixed.
		_, err := d.Exec("ALTER TABLE device_rules ADD COLUMN device_ip TEXT NOT NULL DEFAULT ''")
		if err != nil { return nil } // column exists
		return nil
}

// migrateV023PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV023PG(d *sql.DB) error {

		// 2026-07-09: refactor v0.6.0 — original statement had a syntax error
		// (`DEFAULT ,` with no value) which made the table creation silently
		// fail — the function was invoked without an err check so the migration
		// was a no-op. Production tables were created out-of-band and exist
		// today, but fresh deployments lost this table. Fixed below.
		const q = `CREATE TABLE IF NOT EXISTS personal_api_tokens (
			id BIGSERIAL PRIMARY KEY,
			user_id INTEGER NOT NULL,
			token_hash TEXT NOT NULL UNIQUE,
			label TEXT NOT NULL DEFAULT '',
			last_used_at INTEGER DEFAULT 0,
			created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
			FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
		)`
		if _, err := d.Exec(q); err != nil {
			return err
		}
		return nil
}

// migrateV024PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV024PG(d *sql.DB) error {

		queries := []string{
			"ALTER TABLE exit_servers ADD COLUMN ssh_target TEXT NOT NULL DEFAULT ''",
			"ALTER TABLE exit_servers ADD COLUMN ssh_key_path TEXT NOT NULL DEFAULT ''",
		}
		for _, q := range queries {
			d.Exec(q) // ignore errors (column may exist)
		}
		return nil
}

// migrateV025PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV025PG(d *sql.DB) error {

		queries := []string{
			`CREATE TABLE IF NOT EXISTS portal_users (
				id BIGSERIAL PRIMARY KEY,
				username TEXT UNIQUE NOT NULL,
				password_hash TEXT NOT NULL,
				is_admin INTEGER NOT NULL DEFAULT 0,
				headscale_user_id INTEGER,
				created_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				theme TEXT NOT NULL DEFAULT 'linear'
			)`,
			`CREATE TABLE IF NOT EXISTS preauth_keys (
				id BIGSERIAL PRIMARY KEY,
				user_id INTEGER NOT NULL,
				key TEXT NOT NULL UNIQUE,
				headscale_preauth_id TEXT DEFAULT '',
				reusable INTEGER NOT NULL DEFAULT 0,
				used INTEGER NOT NULL DEFAULT 0,
				expires_at INTEGER DEFAULT 0,
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
			)`,
			`CREATE TABLE IF NOT EXISTS devices (
				id BIGSERIAL PRIMARY KEY,
				user_id INTEGER NOT NULL,
				hostname TEXT NOT NULL,
				node_id TEXT DEFAULT '',
				headscale_node_id TEXT DEFAULT '',
				ip_addresses TEXT DEFAULT '',
				os TEXT DEFAULT '',
				last_seen INTEGER DEFAULT 0,
				online INTEGER DEFAULT 0,
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
			)`,
			`CREATE TABLE IF NOT EXISTS audit_log (
				id BIGSERIAL PRIMARY KEY,
				user_id INTEGER DEFAULT 0,
				username TEXT DEFAULT '',
				action TEXT NOT NULL,
				detail TEXT DEFAULT '',
				ip_address TEXT DEFAULT '',
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
			)`,
			`CREATE TABLE IF NOT EXISTS node_owner_map (
				node_id TEXT PRIMARY KEY,
				headscale_user_id INTEGER NOT NULL DEFAULT 0,
				username TEXT NOT NULL DEFAULT '',
				tag TEXT NOT NULL DEFAULT '',
				tagged_by_user_id INTEGER NOT NULL DEFAULT 0,
				tagged_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				hostname TEXT NOT NULL DEFAULT ''
			)`,
		}
		for _, q := range queries {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV026PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV026PG(d *sql.DB) error {

		stmts := []string{
			"ALTER TABLE exit_servers ADD COLUMN accept_routes INTEGER NOT NULL DEFAULT 0",
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// ignore: column may already exist on a re-run
				continue
			}
		}
		return nil
}

// migrateV027PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV027PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS telegram_alerts (
				id BIGSERIAL PRIMARY KEY,
				body TEXT NOT NULL,
				sent_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				acked_at INTEGER NOT NULL DEFAULT 0,
				acked_by TEXT NOT NULL DEFAULT ''
			)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_alerts_unacked
				ON telegram_alerts(id) WHERE acked_at = 0`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV028PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV028PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE device_rules ADD COLUMN parent_domain TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE node_owner_map ADD COLUMN username TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE node_owner_map ADD COLUMN headscale_user_id INTEGER NOT NULL DEFAULT 0`,
			`ALTER TABLE node_owner_map ADD COLUMN tag TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE node_owner_map ADD COLUMN tagged_by_user_id INTEGER NOT NULL DEFAULT 0`,
			`ALTER TABLE node_owner_map ADD COLUMN tag TEXT NOT NULL DEFAULT ''`, // safe no-op if V028 ran twice
			// 2026-07-15: v0.14.1 — the original V028 ALTER list
			// forgot tagged_at. Production DBs got the column
			// out-of-band (commit a8b07f8 added INSERT OR REPLACE
			// before V028 ran, so a manual ALTER was the only way
			// for a fresh install to work), but the v0.25
			// CREATE+ALTER chain + the v0.14.1 test suite
			// exposed the gap: db.UpsertNodeOwner panics on a
			// fresh DB with "no column named tagged_at". Adding
			// the ALTER here closes the gap for new installs;
			// the _, _ = d.Exec(q) below swallows the "duplicate
			// column" error so the migration stays idempotent on
			// existing installs.
			`ALTER TABLE node_owner_map ADD COLUMN tagged_at INTEGER NOT NULL DEFAULT 0`,
			`ALTER TABLE preauth_keys ADD COLUMN headscale_preauth_id TEXT NOT NULL DEFAULT ''`,
		}
		for _, q := range stmts {
			// SQLite ALTER TABLE ADD COLUMN fails if the column already
			// exists — that's the case on live DBs (the column was
			// created out-of-band). We swallow the error so the
			// migration is idempotent.
			_, _ = d.Exec(q)
		}
		return nil
}

// migrateV029PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV029PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS telegram_bindings (
				chat_id          INTEGER PRIMARY KEY,
				portal_user_id   INTEGER NOT NULL,
				is_admin         INTEGER NOT NULL DEFAULT 0,
				bound_at         INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				bound_by_user_id INTEGER NOT NULL DEFAULT 0
			)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_bindings_user
				ON telegram_bindings(portal_user_id)`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV030PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV030PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE portal_users ADD COLUMN default_device_node_id TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE portal_users ADD COLUMN default_exit_node_id    TEXT NOT NULL DEFAULT ''`,
		}
		for _, q := range stmts {
			// ALTER TABLE ADD COLUMN returns an error if the column
			// already exists; that's the "migration already applied"
			// signal and we swallow it (same idiom as v0.21/v0.22).
			_, _ = d.Exec(q)
		}
		return nil
}

// migrateV031PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV031PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS telegram_login_tokens (
				token            TEXT PRIMARY KEY,
				portal_user_id   INTEGER NOT NULL,
				created_at       INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				expires_at       INTEGER NOT NULL,
				used_at          INTEGER NOT NULL DEFAULT 0,
				used_by_chat_id  INTEGER NOT NULL DEFAULT 0,
				request_ip       TEXT    NOT NULL DEFAULT ''
			)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_login_tokens_user
				ON telegram_login_tokens(portal_user_id)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_login_tokens_expiry
				ON telegram_login_tokens(expires_at)`,
			// Default strict_mode = 0 (off) so the migration doesn't
			// surprise existing single-admin-chat deploys. New deploys
			// that want strict mode flip it via /admin/telegram.
			// We use INSERT ... ON CONFLICT DO NOTHING so re-running
			// the migration is a no-op (the row already exists from
			// a previous run). v0.27.0: switched from SQLite's
			// INSERT OR IGNORE to PG-compatible ON CONFLICT.
			`INSERT INTO global_settings(key, value, updated_at)
				VALUES ('telegram.strict_mode', '0', EXTRACT(EPOCH FROM now())::bigint)
				ON CONFLICT (key) DO NOTHING`,
			// Default token TTL = 300s (5 min). Operators can tune via
			// /admin/telegram UI or by editing the global_settings row
			// directly. Stored as a string to keep the schema uniform
			// (all global_settings values are TEXT).
			`INSERT INTO global_settings(key, value, updated_at)
				VALUES ('telegram.login_token_ttl_seconds', '300', EXTRACT(EPOCH FROM now())::bigint)
				ON CONFLICT (key) DO NOTHING`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV032PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV032PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS telegram_rate_limit (
				key    TEXT NOT NULL,
				action TEXT NOT NULL DEFAULT '',
				ts     INTEGER NOT NULL
			)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_rate_limit_lookup
				ON telegram_rate_limit(key, ts)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_rate_limit_prune
				ON telegram_rate_limit(ts)`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV033PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV033PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE telegram_bindings ADD COLUMN lang TEXT NOT NULL DEFAULT 'en'`,
		}
		for _, q := range stmts {
			// ALTER TABLE ADD COLUMN with a DEFAULT is idempotent
			// in our model: if the column already exists, the
			// statement returns an error and we move on. Fresh
			// DBs get the column with the default; existing DBs
			// silently no-op. Same pattern as the v0.21 ALTER
			// for device_rules.action.
			if _, err := d.Exec(q); err != nil {
				// Column already exists — that's the expected
				// "already migrated" path. Continue.
				continue
			}
		}
		return nil
}

// migrateV034PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV034PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE node_owner_map ADD COLUMN hostname TEXT NOT NULL DEFAULT ''`,
			`CREATE INDEX IF NOT EXISTS idx_node_owner_map_hostname ON node_owner_map (hostname) WHERE hostname != ''`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// Column / index already exists — that's the
				// "already migrated" path. Continue.
				continue
			}
		}
		return nil
}

// migrateV035PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV035PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE portal_users ADD COLUMN headscale_url TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE portal_users ADD COLUMN headscale_api_key_enc TEXT NOT NULL DEFAULT ''`,
			`CREATE INDEX IF NOT EXISTS idx_portal_users_hs_url ON portal_users (headscale_url) WHERE headscale_url != ''`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// Column / index already exists — that's the
				// "already migrated" path. Continue.
				continue
			}
		}
		return nil
}

// migrateV036PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV036PG(d *sql.DB) error {

		stmts := []string{
			// 2026-07-15: v0.13.0 — exit-node health snapshot.
			// `state` is one of: unknown | online | offline | degraded.
			// `degraded` = online + has the tag but routes are not
			// approved (e.g. admin ran --advertise-routes but forgot
			// to approve on headscale, or the approval was rolled
			// back). `healthy` is the combined boolean that the
			// /admin/exit-nodes page renders as a green/red dot.
			`CREATE TABLE IF NOT EXISTS exit_node_health (
				node_id TEXT PRIMARY KEY,
				hostname TEXT NOT NULL DEFAULT '',
				online INTEGER NOT NULL DEFAULT 0,
				last_seen TEXT NOT NULL DEFAULT '',
				advertised_routes_ok INTEGER NOT NULL DEFAULT 0,
				has_exit_tag INTEGER NOT NULL DEFAULT 0,
				state TEXT NOT NULL DEFAULT 'unknown',
				healthy INTEGER NOT NULL DEFAULT 0,
				last_check_at INTEGER NOT NULL DEFAULT 0,
				last_state_change_at INTEGER NOT NULL DEFAULT 0,
				consecutive_failures INTEGER NOT NULL DEFAULT 0
			)`,
			`CREATE INDEX IF NOT EXISTS idx_exit_node_health_state
				ON exit_node_health (state, healthy)`,
			// 2026-07-15: v0.13.0 — state-transition log.
			// Inserted by the monitor on detected transitions
			// (online→offline, offline→online). `alerted_at` is
			// updated to a unix timestamp once the Telegram alert
			// has been queued. The dispatch loop queries
			// `WHERE alerted_at = 0` to find pending alerts.
			`CREATE TABLE IF NOT EXISTS exit_node_state_changes (
				id BIGSERIAL PRIMARY KEY,
				node_id TEXT NOT NULL,
				hostname TEXT NOT NULL DEFAULT '',
				from_state TEXT NOT NULL,
				to_state TEXT NOT NULL,
				detected_at INTEGER NOT NULL,
				alerted_at INTEGER NOT NULL DEFAULT 0,
				note TEXT NOT NULL DEFAULT ''
			)`,
			`CREATE INDEX IF NOT EXISTS idx_exit_node_state_changes_pending
				ON exit_node_state_changes (alerted_at, detected_at)`,
			`CREATE INDEX IF NOT EXISTS idx_exit_node_state_changes_node
				ON exit_node_state_changes (node_id, detected_at DESC)`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// CREATE IF NOT EXISTS already covers the
				// "already migrated" path; the if-guard is
				// belt-and-suspenders.
				continue
			}
		}
		return nil
}

// migrateV037PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV037PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE personal_api_tokens ADD COLUMN expires_at INTEGER NOT NULL DEFAULT 0`,
			`ALTER TABLE personal_api_tokens ADD COLUMN auto_rotate INTEGER NOT NULL DEFAULT 0`,
			`CREATE INDEX IF NOT EXISTS idx_personal_api_tokens_expires
				ON personal_api_tokens (expires_at)`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// ALTER TABLE ADD COLUMN fails with "duplicate
				// column" on a re-run; ignore that case (the
				// column already exists, which is fine).
				// CREATE INDEX IF NOT EXISTS is a no-op on
				// re-run, so it shouldn't hit this branch.
				continue
			}
		}
		return nil
}

// migrateV038PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV038PG(d *sql.DB) error {

		stmts := []string{
			// New table: user_subnets. The unique constraints
			// on user_id and cidr let the allocator rely on
			// the DB to prevent duplicate allocations (a
			// second AllocateCIDR call for the same user_id
			// hits the UNIQUE(user_id) and the manager can
			// detect "already allocated" via the error).
			`CREATE TABLE IF NOT EXISTS user_subnets (
				id INTEGER PRIMARY KEY,
				user_id INTEGER NOT NULL UNIQUE,
				cidr TEXT NOT NULL UNIQUE,
				subnet_bits INTEGER NOT NULL DEFAULT 24,
				control_plane_url TEXT NOT NULL DEFAULT '',
				status TEXT NOT NULL DEFAULT 'pending',
				router_node_id TEXT NOT NULL DEFAULT '',
				router_container_id TEXT NOT NULL DEFAULT '',
				router_hostname TEXT NOT NULL DEFAULT '',
				created_at INTEGER NOT NULL,
				updated_at INTEGER NOT NULL,
				FOREIGN KEY (user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`,
			// Indexes: the (cidr) UNIQUE in the table definition
			// already creates a unique index; we add plain
			// indexes for the (status) and (control_plane_url)
			// lookups that the manager / bot / admin pages do.
			`CREATE INDEX IF NOT EXISTS idx_user_subnets_status
				ON user_subnets (status)`,
			`CREATE INDEX IF NOT EXISTS idx_user_subnets_plane
				ON user_subnets (control_plane_url)`,
			// Denormalized columns on portal_users. The 3
			// queries that read these columns are:
			//   1. /mysubnet: SELECT subnet_cidr, subnet_status,
			//      subnet_router_node_id FROM portal_users WHERE id = ?
			//   2. /myexitnodes: JOIN against user_subnets via
			//      portal_users.subnet_cidr (for "your default
			//      exit-node can route through your personal
			//      subnet" hint, v0.17.0+)
			//   3. /admin/users/{id} admin page: shows the
			//      subnet_status next to the username
			// Keeping these in portal_users saves a JOIN on the
			// hot path. The user_subnets table is the source
			// of truth; the portal_users columns are kept in
			// sync by the manager (internal/subnet/manager.go).
			`ALTER TABLE portal_users ADD COLUMN subnet_cidr TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE portal_users ADD COLUMN subnet_status TEXT NOT NULL DEFAULT 'none'`,
			`ALTER TABLE portal_users ADD COLUMN subnet_router_node_id TEXT NOT NULL DEFAULT ''`,
			`CREATE INDEX IF NOT EXISTS idx_portal_users_subnet_status
				ON portal_users (subnet_status)`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// ALTER TABLE ADD COLUMN fails with "duplicate
				// column" on a re-run; ignore that case (the
				// column already exists, which is fine).
				// CREATE TABLE / INDEX IF NOT EXISTS is a no-op
				// on re-run, so it shouldn't hit this branch.
				continue
			}
		}
		return nil
}

// migrateV039PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV039PG(d *sql.DB) error {

		stmts := []string{
			// The shares table. grantor is the user whose
			// subnet is being shared; grantee is the user
			// who gets access to grantor's subnet.
			`CREATE TABLE IF NOT EXISTS user_subnet_shares (
				grantor_user_id INTEGER NOT NULL,
				grantee_user_id INTEGER NOT NULL,
				created_at INTEGER NOT NULL DEFAULT 0,
				PRIMARY KEY (grantor_user_id, grantee_user_id),
				FOREIGN KEY (grantor_user_id) REFERENCES portal_users(id) ON DELETE CASCADE,
				FOREIGN KEY (grantee_user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`,
			// Index on grantee — the ACL builder iterates
			// "for each user, what subnets are shared with
			// them" which is a scan by grantee. The
			// PRIMARY KEY index covers grantor lookups
			// (grantor-side); the grantee-side needs its
			// own index.
			`CREATE INDEX IF NOT EXISTS idx_user_subnet_shares_grantee
				ON user_subnet_shares (grantee_user_id)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return err
			}
		}
		return nil
}

// migrateV041PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV041PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS headscale_releases (
				version TEXT PRIMARY KEY,
				published_at INTEGER NOT NULL DEFAULT 0,
				first_seen_at INTEGER NOT NULL DEFAULT 0,
				html_url TEXT NOT NULL DEFAULT '',
				name TEXT NOT NULL DEFAULT '',
				body TEXT NOT NULL DEFAULT '',
				is_breaking INTEGER NOT NULL DEFAULT 0,
				notified INTEGER NOT NULL DEFAULT 0
			)`,
			// Index on published_at DESC for the
			// /admin/headscale "history" view (newest
			// first). The PRIMARY KEY covers exact
			// lookups; the index covers the range scan
			// the page renders.
			`CREATE INDEX IF NOT EXISTS idx_headscale_releases_published
				ON headscale_releases (published_at DESC)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return err
			}
		}
		return nil
}

// migrateV042PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV042PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS invite_codes (
				id BIGSERIAL PRIMARY KEY,
				code TEXT NOT NULL UNIQUE,
				grantor_user_id INTEGER NOT NULL,
				grantee_username TEXT NOT NULL,
				status TEXT NOT NULL DEFAULT 'active',
				created_at INTEGER NOT NULL DEFAULT 0,
				expires_at INTEGER NOT NULL DEFAULT 0,
				consumed_at INTEGER NOT NULL DEFAULT 0,
				consumed_by_user_id INTEGER NOT NULL DEFAULT 0,
				audit_message TEXT NOT NULL DEFAULT '',
				FOREIGN KEY (grantor_user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`,
			// Note: consumed_by_user_id does NOT have
			// an FK because the user may not exist at
			// generation time (we store grantee by
			// username, resolved to id at consume).
			// At consume time the consuming user IS
			// known (they have to be authenticated to
			// reach /accept), so we add a partial FK
			// to gate "consumed but user_id is now
			// gone" cases. Setting to ON DELETE SET
			// DEFAULT 0 keeps the audit trail even if
			// the consumer is later deleted.
			`CREATE INDEX IF NOT EXISTS idx_invite_codes_grantor
				ON invite_codes (grantor_user_id)`,
			`CREATE INDEX IF NOT EXISTS idx_invite_codes_status_expires
				ON invite_codes (status, expires_at)`,
			// Also: lookup by grantee_username (the
			// "show me invites for me" query — the
			// consume path joins on this).
			`CREATE INDEX IF NOT EXISTS idx_invite_codes_grantee
				ON invite_codes (grantee_username)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return err
			}
		}
		return nil
}

// migrateV043PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV043PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS meshes (
				id BIGSERIAL PRIMARY KEY,
				code TEXT NOT NULL UNIQUE,
				name TEXT NOT NULL DEFAULT '',
				creator_user_id INTEGER NOT NULL,
				status TEXT NOT NULL DEFAULT 'active',
				created_at INTEGER NOT NULL DEFAULT 0,
				dissolved_at INTEGER NOT NULL DEFAULT 0,
				FOREIGN KEY (creator_user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`,
			`CREATE TABLE IF NOT EXISTS mesh_members (
				mesh_id INTEGER NOT NULL,
				user_id INTEGER NOT NULL,
				joined_at INTEGER NOT NULL DEFAULT 0,
				PRIMARY KEY (mesh_id, user_id),
				FOREIGN KEY (mesh_id) REFERENCES meshes(id) ON DELETE CASCADE,
				FOREIGN KEY (user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`,
			// Lookups:
			//   - "which meshes does user U belong to" → idx_mesh_members_user
			//   - "which users are in mesh M" → idx_mesh_members_mesh (PK already covers)
			//   - "find a mesh by its code" → UNIQUE on meshes.code (PK-like)
			`CREATE INDEX IF NOT EXISTS idx_mesh_members_user
				ON mesh_members (user_id)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return err
			}
		}
		return nil
}
