// Code generated by port_migrations_pg.py; DO NOT EDIT.
// This is a mechanical port of the SQLite migrations to PostgreSQL.
// Review the file and resolve any TODO comments by hand.

package db

import (
	"database/sql"
	"fmt"
)

// migrateV020PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV020PG(d *sql.DB) error {

		queries := []string{
			`CREATE TABLE IF NOT EXISTS exit_servers (
				id BIGSERIAL PRIMARY KEY,
				node_id TEXT NOT NULL UNIQUE,
				hostname TEXT NOT NULL,
				tailscale_ip TEXT NOT NULL DEFAULT '',
				description TEXT DEFAULT '',
				enabled INTEGER DEFAULT 1,
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
			)`,
			`CREATE TABLE IF NOT EXISTS device_rules (
				id BIGSERIAL PRIMARY KEY,
				user_id INTEGER NOT NULL,
				device_id INTEGER NOT NULL,
				exit_node_id TEXT NOT NULL,
				target_type TEXT NOT NULL DEFAULT 'domain',
				target_value TEXT NOT NULL,
				enabled INTEGER DEFAULT 1,
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
			)`,
			`CREATE TABLE IF NOT EXISTS acl_snapshots (
				id BIGSERIAL PRIMARY KEY,
				version INTEGER NOT NULL,
				config TEXT NOT NULL,
				created_by TEXT NOT NULL,
				applied_success INTEGER DEFAULT NULL,
				error_msg TEXT DEFAULT '',
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
			)`,
			`CREATE TABLE IF NOT EXISTS exit_rule_logs (
				id BIGSERIAL PRIMARY KEY,
				version INTEGER NOT NULL,
				action TEXT NOT NULL,
				detail TEXT DEFAULT '',
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
			)`,
		}
		for _, q := range queries {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV021PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV021PG(d *sql.DB) error {

		queries := []string{
			`ALTER TABLE device_rules ADD COLUMN IF NOT EXISTS action TEXT NOT NULL DEFAULT 'accept'`,
			`CREATE TABLE IF NOT EXISTS global_settings (
				key TEXT PRIMARY KEY,
				value TEXT NOT NULL DEFAULT '',
				updated_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
			)`,
			`INSERT INTO global_settings (key, value) VALUES ('exit_policy', 'allow_all') ON CONFLICT (key) DO NOTHING`,
		}
		for _, q := range queries {
			if _, err := d.Exec(q); err != nil {
				// ALTER TABLE ADD COLUMN may fail if column exists — ignore
				continue
			}
		}
		return nil
}

// migrateV022PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV022PG(d *sql.DB) error {

		// 2026-07-11: Этап 9 part 2 — the original 2026-07-09 statement had
		// `DEFAULT ` with no value, which is a syntax error. The function
		// ignored the error so the migration silently no-op'd, leaving
		// device_rules without device_ip on fresh DBs. Fixed.
		_, err := d.Exec("ALTER TABLE device_rules ADD COLUMN IF NOT EXISTS device_ip TEXT NOT NULL DEFAULT ''")
		if err != nil { return nil } // column exists
		return nil
}

// migrateV023PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV023PG(d *sql.DB) error {

		// 2026-07-09: refactor v0.6.0 — original statement had a syntax error
		// (`DEFAULT ,` with no value) which made the table creation silently
		// fail — the function was invoked without an err check so the migration
		// was a no-op. Production tables were created out-of-band and exist
		// today, but fresh deployments lost this table. Fixed below.
		const q = `CREATE TABLE IF NOT EXISTS personal_api_tokens (
			id BIGSERIAL PRIMARY KEY,
			user_id INTEGER NOT NULL,
			token_hash TEXT NOT NULL UNIQUE,
			label TEXT NOT NULL DEFAULT '',
			last_used_at INTEGER DEFAULT 0,
			created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
			FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
		)`
		if _, err := d.Exec(q); err != nil {
			return err
		}
		return nil
}

// migrateV024PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV024PG(d *sql.DB) error {

		queries := []string{
			"ALTER TABLE exit_servers ADD COLUMN IF NOT EXISTS ssh_target TEXT NOT NULL DEFAULT ''",
			"ALTER TABLE exit_servers ADD COLUMN IF NOT EXISTS ssh_key_path TEXT NOT NULL DEFAULT ''",
		}
		for _, q := range queries {
			d.Exec(q) // ignore errors (column may exist)
		}
		return nil
}

// migrateV025PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV025PG(d *sql.DB) error {

		queries := []string{
			`CREATE TABLE IF NOT EXISTS portal_users (
				id BIGSERIAL PRIMARY KEY,
				username TEXT UNIQUE NOT NULL,
				password_hash TEXT NOT NULL,
				is_admin INTEGER NOT NULL DEFAULT 0,
				headscale_user_id INTEGER,
				created_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				theme TEXT NOT NULL DEFAULT 'linear'
			)`,
			`CREATE TABLE IF NOT EXISTS preauth_keys (
				id BIGSERIAL PRIMARY KEY,
				user_id INTEGER NOT NULL,
				key TEXT NOT NULL UNIQUE,
				headscale_preauth_id TEXT DEFAULT '',
				reusable INTEGER NOT NULL DEFAULT 0,
				used INTEGER NOT NULL DEFAULT 0,
				expires_at INTEGER DEFAULT 0,
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
			)`,
			`CREATE TABLE IF NOT EXISTS devices (
				id BIGSERIAL PRIMARY KEY,
				user_id INTEGER NOT NULL,
				hostname TEXT NOT NULL,
				node_id TEXT DEFAULT '',
				headscale_node_id TEXT DEFAULT '',
				ip_addresses TEXT DEFAULT '',
				os TEXT DEFAULT '',
				last_seen INTEGER DEFAULT 0,
				online INTEGER DEFAULT 0,
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
			)`,
			`CREATE TABLE IF NOT EXISTS audit_log (
				id BIGSERIAL PRIMARY KEY,
				user_id INTEGER DEFAULT 0,
				username TEXT DEFAULT '',
				action TEXT NOT NULL,
				detail TEXT DEFAULT '',
				ip_address TEXT DEFAULT '',
				created_at INTEGER DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
			)`,
			`CREATE TABLE IF NOT EXISTS node_owner_map (
				node_id TEXT PRIMARY KEY,
				headscale_user_id INTEGER NOT NULL DEFAULT 0,
				username TEXT NOT NULL DEFAULT '',
				tag TEXT NOT NULL DEFAULT '',
				tagged_by_user_id INTEGER NOT NULL DEFAULT 0,
				tagged_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				hostname TEXT NOT NULL DEFAULT ''
			)`,
		}
		for _, q := range queries {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV026PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV026PG(d *sql.DB) error {

		stmts := []string{
			"ALTER TABLE exit_servers ADD COLUMN IF NOT EXISTS accept_routes INTEGER NOT NULL DEFAULT 0",
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// ignore: column may already exist on a re-run
				continue
			}
		}
		return nil
}

// migrateV027PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV027PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS telegram_alerts (
				id BIGSERIAL PRIMARY KEY,
				body TEXT NOT NULL,
				sent_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				acked_at INTEGER NOT NULL DEFAULT 0,
				acked_by TEXT NOT NULL DEFAULT ''
			)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_alerts_unacked
				ON telegram_alerts(id) WHERE acked_at = 0`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV028PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV028PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE device_rules ADD COLUMN IF NOT EXISTS parent_domain TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE node_owner_map ADD COLUMN IF NOT EXISTS username TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE node_owner_map ADD COLUMN IF NOT EXISTS headscale_user_id INTEGER NOT NULL DEFAULT 0`,
			`ALTER TABLE node_owner_map ADD COLUMN IF NOT EXISTS tag TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE node_owner_map ADD COLUMN IF NOT EXISTS tagged_by_user_id INTEGER NOT NULL DEFAULT 0`,
			`ALTER TABLE node_owner_map ADD COLUMN IF NOT EXISTS tag TEXT NOT NULL DEFAULT ''`, // safe no-op if V028 ran twice
			// 2026-07-15: v0.14.1 — the original V028 ALTER list
			// forgot tagged_at. Production DBs got the column
			// out-of-band (commit a8b07f8 added INSERT OR REPLACE
			// before V028 ran, so a manual ALTER was the only way
			// for a fresh install to work), but the v0.25
			// CREATE+ALTER chain + the v0.14.1 test suite
			// exposed the gap: db.UpsertNodeOwner panics on a
			// fresh DB with "no column named tagged_at". Adding
			// the ALTER here closes the gap for new installs;
			// the _, _ = d.Exec(q) below swallows the "duplicate
			// column" error so the migration stays idempotent on
			// existing installs.
			`ALTER TABLE node_owner_map ADD COLUMN IF NOT EXISTS tagged_at INTEGER NOT NULL DEFAULT 0`,
			`ALTER TABLE preauth_keys ADD COLUMN IF NOT EXISTS headscale_preauth_id TEXT NOT NULL DEFAULT ''`,
		}
		for _, q := range stmts {
			// SQLite ALTER TABLE ADD COLUMN fails if the column already
			// exists — that's the case on live DBs (the column was
			// created out-of-band). We swallow the error so the
			// migration is idempotent.
			_, _ = d.Exec(q)
		}
		return nil
}

// migrateV029PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV029PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS telegram_bindings (
				chat_id          INTEGER PRIMARY KEY,
				portal_user_id   INTEGER NOT NULL,
				is_admin         INTEGER NOT NULL DEFAULT 0,
				bound_at         INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				bound_by_user_id INTEGER NOT NULL DEFAULT 0
			)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_bindings_user
				ON telegram_bindings(portal_user_id)`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV030PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV030PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS default_device_node_id TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS default_exit_node_id    TEXT NOT NULL DEFAULT ''`,
		}
		for _, q := range stmts {
			// ALTER TABLE ADD COLUMN returns an error if the column
			// already exists; that's the "migration already applied"
			// signal and we swallow it (same idiom as v0.21/v0.22).
			_, _ = d.Exec(q)
		}
		return nil
}

// migrateV031PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV031PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS telegram_login_tokens (
				token            TEXT PRIMARY KEY,
				portal_user_id   INTEGER NOT NULL,
				created_at       INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
				expires_at       INTEGER NOT NULL,
				used_at          INTEGER NOT NULL DEFAULT 0,
				used_by_chat_id  INTEGER NOT NULL DEFAULT 0,
				request_ip       TEXT    NOT NULL DEFAULT ''
			)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_login_tokens_user
				ON telegram_login_tokens(portal_user_id)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_login_tokens_expiry
				ON telegram_login_tokens(expires_at)`,
			// Default strict_mode = 0 (off) so the migration doesn't
			// surprise existing single-admin-chat deploys. New deploys
			// that want strict mode flip it via /admin/telegram.
			// We use INSERT OR IGNORE so re-running the migration is a
			// no-op (the row already exists from a previous run).
			`INSERT INTO global_settings (key, value, updated_at)
				VALUES ('telegram.strict_mode', '0', EXTRACT(EPOCH FROM now())::bigint)
				ON CONFLICT (key) DO NOTHING`,
			// Default token TTL = 300s (5 min). Operators can tune via
			// /admin/telegram UI or by editing the global_settings row
			// directly. Stored as a string to keep the schema uniform
			// (all global_settings values are TEXT).
			`INSERT INTO global_settings (key, value, updated_at)
				VALUES ('telegram.login_token_ttl_seconds', '300', EXTRACT(EPOCH FROM now())::bigint)
				ON CONFLICT (key) DO NOTHING`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV032PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV032PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS telegram_rate_limit (
				key    TEXT NOT NULL,
				action TEXT NOT NULL DEFAULT '',
				ts     INTEGER NOT NULL
			)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_rate_limit_lookup
				ON telegram_rate_limit(key, ts)`,
			`CREATE INDEX IF NOT EXISTS idx_telegram_rate_limit_prune
				ON telegram_rate_limit(ts)`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				return err
			}
		}
		return nil
}

// migrateV033PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV033PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE telegram_bindings ADD COLUMN IF NOT EXISTS lang TEXT NOT NULL DEFAULT 'en'`,
		}
		for _, q := range stmts {
			// ALTER TABLE ADD COLUMN with a DEFAULT is idempotent
			// in our model: if the column already exists, the
			// statement returns an error and we move on. Fresh
			// DBs get the column with the default; existing DBs
			// silently no-op. Same pattern as the v0.21 ALTER
			// for device_rules.action.
			if _, err := d.Exec(q); err != nil {
				// Column already exists — that's the expected
				// "already migrated" path. Continue.
				continue
			}
		}
		return nil
}

// migrateV034PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV034PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE node_owner_map ADD COLUMN IF NOT EXISTS hostname TEXT NOT NULL DEFAULT ''`,
			`CREATE INDEX IF NOT EXISTS idx_node_owner_map_hostname ON node_owner_map (hostname) WHERE hostname != ''`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// Column / index already exists — that's the
				// "already migrated" path. Continue.
				continue
			}
		}
		return nil
}

// migrateV035PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV035PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS headscale_url TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS headscale_api_key_enc TEXT NOT NULL DEFAULT ''`,
			`CREATE INDEX IF NOT EXISTS idx_portal_users_hs_url ON portal_users (headscale_url) WHERE headscale_url != ''`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// Column / index already exists — that's the
				// "already migrated" path. Continue.
				continue
			}
		}
		return nil
}

// migrateV036PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV036PG(d *sql.DB) error {

		stmts := []string{
			// 2026-07-15: v0.13.0 — exit-node health snapshot.
			// `state` is one of: unknown | online | offline | degraded.
			// `degraded` = online + has the tag but routes are not
			// approved (e.g. admin ran --advertise-routes but forgot
			// to approve on headscale, or the approval was rolled
			// back). `healthy` is the combined boolean that the
			// /admin/exit-nodes page renders as a green/red dot.
			`CREATE TABLE IF NOT EXISTS exit_node_health (
				node_id TEXT PRIMARY KEY,
				hostname TEXT NOT NULL DEFAULT '',
				online INTEGER NOT NULL DEFAULT 0,
				last_seen TEXT NOT NULL DEFAULT '',
				advertised_routes_ok INTEGER NOT NULL DEFAULT 0,
				has_exit_tag INTEGER NOT NULL DEFAULT 0,
				state TEXT NOT NULL DEFAULT 'unknown',
				healthy INTEGER NOT NULL DEFAULT 0,
				last_check_at INTEGER NOT NULL DEFAULT 0,
				last_state_change_at INTEGER NOT NULL DEFAULT 0,
				consecutive_failures INTEGER NOT NULL DEFAULT 0
			)`,
			`CREATE INDEX IF NOT EXISTS idx_exit_node_health_state
				ON exit_node_health (state, healthy)`,
			// 2026-07-15: v0.13.0 — state-transition log.
			// Inserted by the monitor on detected transitions
			// (online→offline, offline→online). `alerted_at` is
			// updated to a unix timestamp once the Telegram alert
			// has been queued. The dispatch loop queries
			// `WHERE alerted_at = 0` to find pending alerts.
			`CREATE TABLE IF NOT EXISTS exit_node_state_changes (
				id BIGSERIAL PRIMARY KEY,
				node_id TEXT NOT NULL,
				hostname TEXT NOT NULL DEFAULT '',
				from_state TEXT NOT NULL,
				to_state TEXT NOT NULL,
				detected_at INTEGER NOT NULL,
				alerted_at INTEGER NOT NULL DEFAULT 0,
				note TEXT NOT NULL DEFAULT ''
			)`,
			`CREATE INDEX IF NOT EXISTS idx_exit_node_state_changes_pending
				ON exit_node_state_changes (alerted_at, detected_at)`,
			`CREATE INDEX IF NOT EXISTS idx_exit_node_state_changes_node
				ON exit_node_state_changes (node_id, detected_at DESC)`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// CREATE IF NOT EXISTS already covers the
				// "already migrated" path; the if-guard is
				// belt-and-suspenders.
				continue
			}
		}
		return nil
}

// migrateV037PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV037PG(d *sql.DB) error {

		stmts := []string{
			`ALTER TABLE personal_api_tokens ADD COLUMN IF NOT EXISTS expires_at INTEGER NOT NULL DEFAULT 0`,
			`ALTER TABLE personal_api_tokens ADD COLUMN IF NOT EXISTS auto_rotate INTEGER NOT NULL DEFAULT 0`,
			`CREATE INDEX IF NOT EXISTS idx_personal_api_tokens_expires
				ON personal_api_tokens (expires_at)`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// ALTER TABLE ADD COLUMN fails with "duplicate
				// column" on a re-run; ignore that case (the
				// column already exists, which is fine).
				// CREATE INDEX IF NOT EXISTS is a no-op on
				// re-run, so it shouldn't hit this branch.
				continue
			}
		}
		return nil
}

// migrateV038PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV038PG(d *sql.DB) error {

		stmts := []string{
			// New table: user_subnets. The unique constraints
			// on user_id and cidr let the allocator rely on
			// the DB to prevent duplicate allocations (a
			// second AllocateCIDR call for the same user_id
			// hits the UNIQUE(user_id) and the manager can
			// detect "already allocated" via the error).
			`CREATE TABLE IF NOT EXISTS user_subnets (
				id INTEGER PRIMARY KEY,
				user_id INTEGER NOT NULL UNIQUE,
				cidr TEXT NOT NULL UNIQUE,
				subnet_bits INTEGER NOT NULL DEFAULT 24,
				control_plane_url TEXT NOT NULL DEFAULT '',
				status TEXT NOT NULL DEFAULT 'pending',
				router_node_id TEXT NOT NULL DEFAULT '',
				router_container_id TEXT NOT NULL DEFAULT '',
				router_hostname TEXT NOT NULL DEFAULT '',
				created_at INTEGER NOT NULL,
				updated_at INTEGER NOT NULL,
				FOREIGN KEY (user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`,
			// Indexes: the (cidr) UNIQUE in the table definition
			// already creates a unique index; we add plain
			// indexes for the (status) and (control_plane_url)
			// lookups that the manager / bot / admin pages do.
			`CREATE INDEX IF NOT EXISTS idx_user_subnets_status
				ON user_subnets (status)`,
			`CREATE INDEX IF NOT EXISTS idx_user_subnets_plane
				ON user_subnets (control_plane_url)`,
			// Denormalized columns on portal_users. The 3
			// queries that read these columns are:
			//   1. /mysubnet: SELECT subnet_cidr, subnet_status,
			//      subnet_router_node_id FROM portal_users WHERE id = ?
			//   2. /myexitnodes: JOIN against user_subnets via
			//      portal_users.subnet_cidr (for "your default
			//      exit-node can route through your personal
			//      subnet" hint, v0.17.0+)
			//   3. /admin/users/{id} admin page: shows the
			//      subnet_status next to the username
			// Keeping these in portal_users saves a JOIN on the
			// hot path. The user_subnets table is the source
			// of truth; the portal_users columns are kept in
			// sync by the manager (internal/subnet/manager.go).
			`ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS subnet_cidr TEXT NOT NULL DEFAULT ''`,
			`ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS subnet_status TEXT NOT NULL DEFAULT 'none'`,
			`ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS subnet_router_node_id TEXT NOT NULL DEFAULT ''`,
			`CREATE INDEX IF NOT EXISTS idx_portal_users_subnet_status
				ON portal_users (subnet_status)`,
		}
		for _, q := range stmts {
			if _, err := d.Exec(q); err != nil {
				// ALTER TABLE ADD COLUMN fails with "duplicate
				// column" on a re-run; ignore that case (the
				// column already exists, which is fine).
				// CREATE TABLE / INDEX IF NOT EXISTS is a no-op
				// on re-run, so it shouldn't hit this branch.
				continue
			}
		}
		return nil
}

// migrateV039PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV039PG(d *sql.DB) error {

		stmts := []string{
			// The shares table. grantor is the user whose
			// subnet is being shared; grantee is the user
			// who gets access to grantor's subnet.
			`CREATE TABLE IF NOT EXISTS user_subnet_shares (
				grantor_user_id INTEGER NOT NULL,
				grantee_user_id INTEGER NOT NULL,
				created_at INTEGER NOT NULL DEFAULT 0,
				PRIMARY KEY (grantor_user_id, grantee_user_id),
				FOREIGN KEY (grantor_user_id) REFERENCES portal_users(id) ON DELETE CASCADE,
				FOREIGN KEY (grantee_user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`,
			// Index on grantee — the ACL builder iterates
			// "for each user, what subnets are shared with
			// them" which is a scan by grantee. The
			// PRIMARY KEY index covers grantor lookups
			// (grantor-side); the grantee-side needs its
			// own index.
			`CREATE INDEX IF NOT EXISTS idx_user_subnet_shares_grantee
				ON user_subnet_shares (grantee_user_id)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return err
			}
		}
		return nil
}

// migrateV041PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV041PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS headscale_releases (
				version TEXT PRIMARY KEY,
				published_at INTEGER NOT NULL DEFAULT 0,
				first_seen_at INTEGER NOT NULL DEFAULT 0,
				html_url TEXT NOT NULL DEFAULT '',
				name TEXT NOT NULL DEFAULT '',
				body TEXT NOT NULL DEFAULT '',
				is_breaking INTEGER NOT NULL DEFAULT 0,
				notified INTEGER NOT NULL DEFAULT 0
			)`,
			// Index on published_at DESC for the
			// /admin/headscale "history" view (newest
			// first). The PRIMARY KEY covers exact
			// lookups; the index covers the range scan
			// the page renders.
			`CREATE INDEX IF NOT EXISTS idx_headscale_releases_published
				ON headscale_releases (published_at DESC)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return err
			}
		}
		return nil
}

// migrateV042PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV042PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS invite_codes (
				id BIGSERIAL PRIMARY KEY,
				code TEXT NOT NULL UNIQUE,
				grantor_user_id INTEGER NOT NULL,
				grantee_username TEXT NOT NULL,
				status TEXT NOT NULL DEFAULT 'active',
				created_at INTEGER NOT NULL DEFAULT 0,
				expires_at INTEGER NOT NULL DEFAULT 0,
				consumed_at INTEGER NOT NULL DEFAULT 0,
				consumed_by_user_id INTEGER NOT NULL DEFAULT 0,
				audit_message TEXT NOT NULL DEFAULT '',
				FOREIGN KEY (grantor_user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`,
			// Note: consumed_by_user_id does NOT have
			// an FK because the user may not exist at
			// generation time (we store grantee by
			// username, resolved to id at consume).
			// At consume time the consuming user IS
			// known (they have to be authenticated to
			// reach /accept), so we add a partial FK
			// to gate "consumed but user_id is now
			// gone" cases. Setting to ON DELETE SET
			// DEFAULT 0 keeps the audit trail even if
			// the consumer is later deleted.
			`CREATE INDEX IF NOT EXISTS idx_invite_codes_grantor
				ON invite_codes (grantor_user_id)`,
			`CREATE INDEX IF NOT EXISTS idx_invite_codes_status_expires
				ON invite_codes (status, expires_at)`,
			// Also: lookup by grantee_username (the
			// "show me invites for me" query — the
			// consume path joins on this).
			`CREATE INDEX IF NOT EXISTS idx_invite_codes_grantee
				ON invite_codes (grantee_username)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return err
			}
		}
		return nil
}

// migrateV043PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV043PG(d *sql.DB) error {

		stmts := []string{
			`CREATE TABLE IF NOT EXISTS meshes (
				id BIGSERIAL PRIMARY KEY,
				code TEXT NOT NULL UNIQUE,
				name TEXT NOT NULL DEFAULT '',
				creator_user_id INTEGER NOT NULL,
				status TEXT NOT NULL DEFAULT 'active',
				created_at INTEGER NOT NULL DEFAULT 0,
				dissolved_at INTEGER NOT NULL DEFAULT 0,
				FOREIGN KEY (creator_user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`,
			`CREATE TABLE IF NOT EXISTS mesh_members (
				mesh_id INTEGER NOT NULL,
				user_id INTEGER NOT NULL,
				joined_at INTEGER NOT NULL DEFAULT 0,
				PRIMARY KEY (mesh_id, user_id),
				FOREIGN KEY (mesh_id) REFERENCES meshes(id) ON DELETE CASCADE,
				FOREIGN KEY (user_id) REFERENCES portal_users(id) ON DELETE CASCADE
			)`,
			// Lookups:
			//   - "which meshes does user U belong to" → idx_mesh_members_user
			//   - "which users are in mesh M" → idx_mesh_members_mesh (PK already covers)
			//   - "find a mesh by its code" → UNIQUE on meshes.code (PK-like)
			`CREATE INDEX IF NOT EXISTS idx_mesh_members_user
				ON mesh_members (user_id)`,
		}
		for _, s := range stmts {
			if _, err := d.Exec(s); err != nil {
				return err
			}
		}
		return nil
}

// migrateV044PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV044PG(d *sql.DB) error {

		// PG 9.6+ supports ADD COLUMN IF NOT EXISTS natively,
		// which is the atomic way to make this idempotent. The
		// pre-v0.32.24 code used a PRAGMA table_info-based
		// `hasColumn` check (a SQLite idiom that didn't work on
		// PG); v0.32.24 replaces it with IF NOT EXISTS.
		if _, err := d.Exec(`ALTER TABLE device_rules ADD COLUMN IF NOT EXISTS user_name TEXT NOT NULL DEFAULT ''`); err != nil {
			return fmt.Errorf("v0.44 add user_name: %w", err)
		}
		if _, err := d.Exec(`ALTER TABLE device_rules ADD COLUMN IF NOT EXISTS device_hostname TEXT NOT NULL DEFAULT ''`); err != nil {
			return fmt.Errorf("v0.44 add device_hostname: %w", err)
		}
		// Backfill user_name from portal_users. Every
		// device_rules row has a non-zero user_id (the FK
		// is NOT NULL); the portal_users row might be gone
		// in pathological cleanup cases, in which case we
		// leave user_name empty and the ACL builder falls
		// back to device_ip.
		if _, err := d.Exec(`
			UPDATE device_rules
			   SET user_name = COALESCE(
			     (SELECT username FROM portal_users WHERE id = device_rules.user_id),
			     ''
			   )
			 WHERE user_name = ''`); err != nil {
			return fmt.Errorf("v0.44 backfill user_name: %w", err)
		}
		// device_hostname is NOT backfilled here — node_owner_map
		// has no tailscale_ip column to JOIN on. The runtime
		// backfill happens in handlers.backfillNodeOwnership
		// on the next /my/devices load (the function knows the
		// device hostname from headscale's list response).
		// For pre-v0.28.0 rules, the ACL builder falls back to
		// src=device_ip until the runtime backfill lands, so
		// the rules are live immediately and switch to the
		// tag-based src transparently on the next /my/devices
		// load.
		return nil
}

// migrateV045PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV045PG(d *sql.DB) error {

		// 2026-07-24: v0.28.1 — user_exit_node_prefs table.
		// One row per user (PK on user_id). Cascade on user
		// delete is intentional: a deleted user has no
		// preference. exit_node_tag is the headscale tag
		// (e.g. "tag:exit-relay-1") — NOT the hostname, NOT
		// the node id. The tag is what `grants[].via` takes.
		const q = `CREATE TABLE IF NOT EXISTS user_exit_node_prefs (
			user_id INTEGER NOT NULL PRIMARY KEY,
			exit_node_tag TEXT NOT NULL,
			set_by_user_id INTEGER NOT NULL DEFAULT 0,
			updated_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
			FOREIGN KEY (user_id) REFERENCES portal_users(id) ON DELETE CASCADE
		)`
		if _, err := d.Exec(q); err != nil {
			return err
		}
		return nil
}

// migrateV046PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV046PG(d *sql.DB) error {

		// 2026-07-25: v0.28.4 — device_exit_node_prefs table.
		// One row per (user_id, device_hostname). Composite
		// primary key enforces uniqueness. Cascade on user
		// delete is intentional: a deleted user has no
		// device prefs (their devices are also gone).
		//
		// device_hostname is the lowercase form (matches the
		// v0.28.0 backfill's tag:dev-<user>-<device> naming).
		// The UI normalizes input to lowercase before the
		// INSERT so case differences don't create duplicate
		// rows for the same device.
		//
		// exit_node_tag is the headscale tag (e.g.
		// "tag:exit-relay-3") — NOT the hostname, NOT the
		// node id. The tag is what `grants[].via` takes.
		const q = `CREATE TABLE IF NOT EXISTS device_exit_node_prefs (
			user_id INTEGER NOT NULL,
			device_hostname TEXT NOT NULL,
			exit_node_tag TEXT NOT NULL,
			set_by_user_id INTEGER NOT NULL DEFAULT 0,
			updated_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
			PRIMARY KEY (user_id, device_hostname),
			FOREIGN KEY (user_id) REFERENCES portal_users(id) ON DELETE CASCADE
		)`
		if _, err := d.Exec(q); err != nil {
			return err
		}
		return nil
}

// migrateV047PG is the v0.27.0 PostgreSQL port of the SQLite migration.
// Review the body for any TODO comments and adjust conflict targets.
func migrateV047PG(d *sql.DB) error {

		// v0.32.24: on PG, ALTER TABLE ADD COLUMN IF NOT EXISTS
		// is the atomic way to add a column idempotently.
		// The pre-fix code used the SQLite-style "try ALTER
		// and catch the duplicate-column error" pattern
		// via the shared `addViaEnabledUserPrefSQL` const
		// (in migrations_v0.47.go) + `isSQLiteDuplicateColumnError`
		// helper — both SQLite-isms that don't work on PG
		// (PG returns SQLSTATE 42701 not a string message).
		// We inline the IF NOT EXISTS form here so the
		// freshlyAdded heuristic isn't needed.
		//
		// For the backfill logic: if the column already exists
		// (IF NOT EXISTS makes the ALTER a no-op), we still
		// run the backfill ONLY on the first deploy — see
		// the freshlyAdded check below. We detect "already
		// existed" via information_schema instead of error
		// matching.
		colExists := func(table, col string) bool {
			var n int
			row := d.QueryRow(`
				SELECT COUNT(*) FROM information_schema.columns
				WHERE table_name = $1 AND column_name = $2`,
				table, col)
			if err := row.Scan(&n); err != nil {
				return false
			}
			return n > 0
		}
		freshlyAdded := !colExists("user_exit_node_prefs", "via_enabled")
		if _, err := d.Exec(`ALTER TABLE user_exit_node_prefs ADD COLUMN IF NOT EXISTS via_enabled INTEGER NOT NULL DEFAULT 0`); err != nil {
			return err
		}
		if !colExists("device_exit_node_prefs", "via_enabled") && freshlyAdded {
			freshlyAdded = true
		}
		if _, err := d.Exec(`ALTER TABLE device_exit_node_prefs ADD COLUMN IF NOT EXISTS via_enabled INTEGER NOT NULL DEFAULT 0`); err != nil {
			return err
		}
		// Backfill ONLY on the first-time migration. On
		// every subsequent startup, skip the UPDATE so
		// the operator's via_enabled=0 (un-pinned) is
		// preserved across restarts.
		if !freshlyAdded {
			return nil
		}
		// Backfill existing rows: every row that was
		// created under v0.28.1 / v0.28.4 had the
		// pinning enforced. Preserve that behavior on
		// upgrade (the operator has to explicitly flip
		// the flag to un-pin). The UPDATE is a no-op on
		// a fresh install (column defaults to 0).
		if _, err := d.Exec(`UPDATE user_exit_node_prefs SET via_enabled = 1 WHERE via_enabled = 0`); err != nil {
			return err
		}
		if _, err := d.Exec(`UPDATE device_exit_node_prefs SET via_enabled = 1 WHERE via_enabled = 0`); err != nil {
			return err
		}
		return nil
}

// migrateV048PG is the v0.32.0 PostgreSQL port of the SQLite migration.
// v0.32.0 devicemeta: per-device OS + device_type on node_owner_map.
// Idempotent via PG's native ADD COLUMN IF NOT EXISTS (PG 9.6+).
func migrateV048PG(d *sql.DB) error {
	stmts := []string{
		`ALTER TABLE node_owner_map ADD COLUMN IF NOT EXISTS os TEXT NOT NULL DEFAULT 'unknown'`,
		`ALTER TABLE node_owner_map ADD COLUMN IF NOT EXISTS device_type TEXT NOT NULL DEFAULT 'unknown'`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.48: %w", err)
		}
	}
	return nil
}

// migrateV049PG is the v0.32.19 PostgreSQL port of the SQLite migration.
// v0.32.19 migration integrity tracking: applied_migrations table.
// Idempotent via CREATE TABLE IF NOT EXISTS.
func migrateV049PG(d *sql.DB) error {
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS applied_migrations (
			version     INTEGER PRIMARY KEY,
			sha256      TEXT    NOT NULL,
			source_file TEXT    NOT NULL DEFAULT '',
			applied_at  BIGINT  NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
			first_seen  TEXT    NOT NULL DEFAULT ''
		)`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.49: %w", err)
		}
	}
	return nil
}

// migrateV050PG — v0.32.27 — define strftime() PG function so the
// existing SQLite-style SQL (strftime('%s','now')) works unchanged
// on PostgreSQL. The function ignores the format arg (always '%s'
// in skygate's queries) and just returns Unix-epoch seconds via
// EXTRACT(EPOCH FROM now()).
//
// Why not rewrite every query? Because strftime appears inline in
// 12+ SQL strings across internal/db/{queries,node_owner_map,
// secrets,telegram_login_tokens,integrations}.go. Defining the
// function once is 1 migration instead of 12 line edits. And
// SQLite 3.38+ also has strftime (and SQLite < 3.38 will continue
// to work since strftime is its native form), so the function
// doesn't break the SQLite path either — it just never gets called
// there (different SQL backend).
//
// 2026-08-04: v0.33.1 — also create the headscale_acl_rules
// table. The pre-fix V050PG was generated by port_migrations_pg.py
// from the v0.32.x source and only emitted the strftime function
// — the headscale_acl_rules table CREATE (added in v0.33.0 by
// porting migrateV050 to PG) was silently dropped by the
// generator. The fix: add the full PG port of migrateV050
// (headscale_acl_rules + idx_headscale_acl_enabled) below the
// strftime function. The pre-fix /admin/headscale/acl page
// returned http.StatusInternalServerError ("relation headscale_acl_rules does not exist")
// until this landed; now the page renders.
func migrateV050PG(d *sql.DB) error {
	stmts := []string{
		`CREATE OR REPLACE FUNCTION strftime(format text, ts text) RETURNS bigint AS $$
			SELECT EXTRACT(EPOCH FROM now())::bigint
		$$ LANGUAGE SQL IMMUTABLE`,
		`CREATE TABLE IF NOT EXISTS headscale_acl_rules (
			id                  TEXT    PRIMARY KEY,
			rule_json           TEXT    NOT NULL,
			fingerprint         TEXT    NOT NULL,
			label               TEXT    NOT NULL DEFAULT '',
			created_at          BIGINT  NOT NULL DEFAULT (strftime('%s', 'now')::bigint),
			created_by_user_id  INTEGER NOT NULL DEFAULT 0,
			enabled             INTEGER NOT NULL DEFAULT 1,
			UNIQUE(fingerprint, enabled)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_headscale_acl_enabled
			ON headscale_acl_rules(enabled, created_at DESC)`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.50: %w", err)
		}
	}
	return nil
}

// migrateV051PG — v0.33.0 — system_tests_runs table.
//
// The pre-fix code-generation pipeline (port_migrations_pg.py)
// didn't emit a V051PG function at all. The PostgreSQL migration
// chain in driver_postgres.go's MigratePostgres() referenced
// migrateV050PG as the last function, so the system_tests_runs
// table was never created on PG deployments. The fix: add the
// full PG port here + add it to the MigratePostgres() slice in
// driver_postgres.go.
//
// 2026-08-04: v0.33.1.
func migrateV051PG(d *sql.DB) error {
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS system_tests_runs (
			id                     BIGSERIAL PRIMARY KEY,
			started_at             BIGINT  NOT NULL DEFAULT (strftime('%s', 'now')::bigint),
			finished_at            BIGINT  NOT NULL DEFAULT 0,
			duration_ms            BIGINT  NOT NULL DEFAULT 0,
			results_json           TEXT    NOT NULL DEFAULT '{}',
			pass_count             INTEGER NOT NULL DEFAULT 0,
			fail_count             INTEGER NOT NULL DEFAULT 0,
			skip_count             INTEGER NOT NULL DEFAULT 0,
			triggered_by_user_id   INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE INDEX IF NOT EXISTS idx_system_tests_runs_started
			ON system_tests_runs(started_at DESC)`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.51: %w", err)
		}
	}
	return nil
}

// migrateV053PG — v0.33.1.33 — exit_servers.ssh_port column.
//
// Same purpose as migrateV053 (SQLite): add the per-row
// SSH port override column so the LookupExitServerSSHTarget
// B85 auto-fallback can include a port suffix. PG version
// uses IF NOT EXISTS for idempotency; the SQLite version
// pre-dates 3.35 on some distros and relies on the
// applied_migrations table check upstream for idempotency.
//
// Why a separate PG function (vs reusing the SQLite one):
// ALTER TABLE ADD COLUMN syntax differs slightly between
// the two backends, and the auto-generation pipeline
// (port_migrations_pg.py) doesn't read the SQLite function
// body — it generates PG from a hand-edited model. The
// V053 + V053PG pair is a copy of the V050 / V050PG
// pattern: same shape, slightly different SQL.
func migrateV053PG(d *sql.DB) error {
	stmts := []string{
		`ALTER TABLE exit_servers ADD COLUMN IF NOT EXISTS ssh_port TEXT NOT NULL DEFAULT ''`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.53: %w", err)
		}
	}
	return nil
}

// migrateV054PG — v0.33.1.39 — Issue 4 technical user.
//
// Same purpose as migrateV054 (SQLite): create the 'infra'
// portal_user row (a system account for skygate-host-* +
// exit-node + subnet-router devices). The corresponding
// headscale user is provisioned at startup by
// ensureInfraUser in cmd/skygate/main.go.
//
// 2026-08-10 v0.33.1.41 #2: uses the reserved id=99
// (system user) to avoid collision with low-id auto-
// assigned values in fresh test DBs. See migrateV054
// (SQLite) for the full rationale. The PG version
// generates a random bcrypt hash for the password_hash
// column (NOT NULL constraint) — same shape as the
// SQLite version, just with $1, $2 placeholders.
func migrateV054PG(d *sql.DB) error {
	var n int
	if err := d.QueryRow(
		`SELECT count(*) FROM portal_users WHERE username = $1`,
		"infra",
	).Scan(&n); err != nil {
		return fmt.Errorf("v0.54: check infra: %w", err)
	}
	if n > 0 {
		return nil
	}
	// bcrypt hash of the literal "infra-never-logs-in-via-web-2026-08-10"
	// — pre-computed so we don't pull golang.org/x/crypto/bcrypt
	// into the PG build path. The 'infra' user is never meant
	// to log in; the hash just ensures bcrypt comparison fails
	// fast if anyone tries.
	const infraHash = "$2a$10$xe4ygoIks1PTpz0aO1jhKeUWTvj2bYQRgoSZE9fyKp6GR8dx7d8oa"
	if _, err := d.Exec(
		`INSERT INTO portal_users (id, username, password_hash, is_admin) VALUES (99, $1, $2, 0) ON CONFLICT (username) DO NOTHING`,
		"infra", infraHash,
	); err != nil {
		return fmt.Errorf("v0.54: insert infra: %w", err)
	}
	return nil
}

// migrateV056PG — v1.3.19.2 follow-up (B125) — UNIQUE INDEX on
// device_rules natural key. Closes the SELECT-then-INSERT race
// in sync.go:432, 512 (auto-add of /32 rules from DNS resolution)
// that previously let duplicate rows accumulate. The
// ON CONFLICT DO NOTHING in internal/feature/exit_rules/sync.go
// relies on this index — without it, the conflict target has no
// unique constraint to match against and PG returns a syntax
// error.
//
// Natural key = (user_id, device_id, exit_node_id, target_type,
// target_value, parent_domain). All 6 columns are NOT NULL in
// the current schema (parent_domain is TEXT NOT NULL DEFAULT ''),
// so a plain UNIQUE INDEX covers every row — no need for
// COALESCE() or partial indexes.
//
// The index is named device_rules_natural_key_uniq so future
// migrations can drop+recreate it for cleanup. If a DB has
// existing duplicates, the CREATE UNIQUE INDEX will fail with
// a clear error; the operator should run the cleanup first
// (see scripts/check_b125.sh for the audit query).
//
// Live state (2026-08-17, post-B123 deploy): 0 duplicates. The
// index will be created cleanly on the first run.
func migrateV056PG(d *sql.DB) error {
	stmts := []string{
		`CREATE UNIQUE INDEX IF NOT EXISTS device_rules_natural_key_uniq
			ON device_rules(user_id, device_id, exit_node_id, target_type, target_value, parent_domain)`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.56 device_rules UNIQUE INDEX: %w", err)
		}
	}
	return nil
}

// migrateV057PG — v1.3.20.6 (B136) — per-user display preferences.
// Adds 3 columns to portal_users:
//   - font_family   TEXT NOT NULL DEFAULT 'manrope' (manrope|inter|geist|sora|system)
//   - font_scale    INTEGER NOT NULL DEFAULT 0       (-2..+2 px delta on body font-size)
//   - selection_bg  TEXT NOT NULL DEFAULT ''         (CSS color for ::selection, '' = use theme default)
//
// These are per-user settings, persisted in DB so the user's
// preferred display travels with their account (the pre-B136
// behavior was theme-only per-user, font+size were global in
// themes.css). After the migration, the user's display prefs
// (font + size + selection color) follow them across devices,
// browsers, and cache clears — the operator's 2026-08-18
// request "чтобы не сбрасывалось с кешем".
//
// DEFAULT 'manrope' is the B135 default (matches the
// post-v1.3.20.5 themes.css --font). Existing rows pick up
// these defaults automatically via ALTER TABLE ... DEFAULT,
// so no backfill is needed. The new columns are NOT NULL
// with explicit DEFAULT, which is the safe form for PG.
//
// B136 contract test: see scripts/check_b136.sh.
func migrateV057PG(d *sql.DB) error {
	stmts := []string{
		`ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS font_family TEXT NOT NULL DEFAULT 'manrope'`,
		`ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS font_scale INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS selection_bg TEXT NOT NULL DEFAULT ''`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.57 portal_users display prefs: %w", err)
		}
	}
	return nil
}

// migrateV055PG — v1.3.17 — DERP relays per-row table.
//
// Replaces the v0.11.0 "comma-separated URLs in global_settings"
// model with a first-class table. v0.11.0's /admin/derp/config had
// a textarea + bundled checkbox, but the operator wanted the
// exit-nodes-style CRUD (per-row add/edit/delete/toggle/test) so
// they can manage multiple relays with region metadata, not a
// flat list of URLs.
//
// Schema mirrors the exit_servers shape (BIGSERIAL id + integer
// enabled flag + sort_order for the operator's preferred order +
// notes for the operator's context). The "is_bundled" flag
// singles out the row that owns the bundled derper container —
// at most ONE row can have is_bundled=1, enforced at the
// application layer (AddDerpRelay rejects a 2nd bundled row;
// the bundled row is undeletable from the UI but its enabled
// flag is freely toggleable).
//
// Backward compat: the v0.11.0 /admin/derp/config still works
// — it reads + writes the same global_settings.derp.external_urls
// + global_settings.derp.bundled_enabled keys. The new DERP CRUD
// UI is additive. db.AutoMigrateDerpRelays (called from
// LoadIntegrationsFromOS on every read) does the one-shot
// migration: if derp_relays is empty, copy the legacy
// global_settings rows in and write a "migrated" marker.
//
// 2026-08-13: v1.3.17.
func migrateV055PG(d *sql.DB) error {
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS derp_relays (
			id BIGSERIAL PRIMARY KEY,
			hostname TEXT NOT NULL,
			url TEXT NOT NULL,
			region_id INTEGER NOT NULL DEFAULT 900,
			region_code TEXT NOT NULL DEFAULT '',
			region_name TEXT NOT NULL DEFAULT '',
			is_bundled INTEGER NOT NULL DEFAULT 0,
			enabled INTEGER NOT NULL DEFAULT 1,
			sort_order INTEGER NOT NULL DEFAULT 100,
			notes TEXT NOT NULL DEFAULT '',
			created_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
			updated_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
		)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS derp_relays_url_uniq
			ON derp_relays(url)`,
		`CREATE INDEX IF NOT EXISTS derp_relays_enabled_idx
			ON derp_relays(enabled)`,
		`CREATE INDEX IF NOT EXISTS derp_relays_is_bundled_idx
			ON derp_relays(is_bundled) WHERE is_bundled = 1`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.55 derp_relays: %w", err)
		}
	}
	return nil
}

// migrateV058PG — v1.5.0 (B156) — preauth key expiry notifications.
//
// Adds ONE column to preauth_keys:
//   - notified_at  INTEGER NOT NULL DEFAULT 0
//     Unix timestamp of the last "your preauth key is
//     expiring soon" Telegram notification sent to the
//     user. 0 = never notified (the B156 scheduler
//     picks the key for notification).
//
// The B156 in-app scheduler (internal/keynotify) reads
// this column to dedup: a key that's already been
// notified within the current 14-day window is skipped
// on subsequent ticks. Resetting the column to 0 on
// PostMyPreauth (fresh key) + PostMyKeyReissue (new key
// replaces the old) means a reissue restarts the
// notification countdown for the new key.
//
// Existing rows get the DEFAULT 0 via the ALTER TABLE
// NOT NULL DEFAULT clause, so no backfill is needed.
// Fresh inserts via db.InsertPreauthKey explicitly set
// the column to 0 (the same default the migration
// applies to existing rows).
//
// B156 contract test: see scripts/check_b156.sh.
func migrateV058PG(d *sql.DB) error {
	stmts := []string{
		`ALTER TABLE preauth_keys ADD COLUMN IF NOT EXISTS notified_at INTEGER NOT NULL DEFAULT 0`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.58 preauth_keys notified_at: %w", err)
		}
	}
	return nil
}

// migrateV059PG — v1.5.0 (B157) — in-web notification inbox.
//
// Adds a first-class notifications table for the B157
// bell-icon inbox on the user sidebar. The table is
// the user-facing mirror of the B156 keynotify
// scheduler: every expiring-key event the scheduler
// finds ALSO writes a row here (in addition to the
// Telegram send), so the user sees a per-page
// notification even if they don't have Telegram
// bound, or if the Telegram send was skipped for
// some reason.
//
// Schema:
//   - id           BIGSERIAL PRIMARY KEY
//   - user_id      INTEGER NOT NULL  -- FK portal_users (ON DELETE CASCADE)
//   - type         TEXT    NOT NULL  -- enum-like: 'key.expiring', future types
//   - severity     TEXT    NOT NULL DEFAULT 'info'  -- 'info' | 'warn' | 'danger'
//   - title        TEXT    NOT NULL  -- short title (1 line)
//   - body         TEXT    NOT NULL DEFAULT ''  -- longer description (1-2 lines)
//   - link         TEXT    NOT NULL DEFAULT ''  -- relative URL the bell links to (e.g. /my/keys)
//   - created_at   INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint)
//   - read_at      INTEGER NOT NULL DEFAULT 0  -- unix-seconds; 0 = unread
//
// Indexes:
//   - idx_notifications_user_unread on (user_id, read_at) — the
//     count-unread + list-unread query. Cheap + covers the
//     "bell badge" hot path (every page render).
//   - idx_notifications_user_created on (user_id, created_at DESC) —
//     the list view, "newest first".
//
// The type field is text (not a PG enum) so future
// B-checks can add new notification kinds without a
// schema migration. Same pattern as B156's storage
// keys.
//
// B157 contract test: see scripts/check_b157.sh.
func migrateV059PG(d *sql.DB) error {
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS notifications (
			id BIGSERIAL PRIMARY KEY,
			user_id INTEGER NOT NULL,
			type TEXT NOT NULL,
			severity TEXT NOT NULL DEFAULT 'info',
			title TEXT NOT NULL,
			body TEXT NOT NULL DEFAULT '',
			link TEXT NOT NULL DEFAULT '',
			created_at INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
			read_at INTEGER NOT NULL DEFAULT 0,
			FOREIGN KEY (user_id) REFERENCES portal_users (id) ON DELETE CASCADE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
			ON notifications(user_id, read_at)`,
		`CREATE INDEX IF NOT EXISTS idx_notifications_user_created
			ON notifications(user_id, created_at DESC)`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.59 notifications: %w", err)
		}
	}
	return nil
}

// migrateV060PG — v1.5.2 (B183) — drop parent_domain from
// the device_rules natural-key UNIQUE INDEX.
//
// The pre-B183 index
//
//   CREATE UNIQUE INDEX device_rules_natural_key_uniq
//     ON device_rules(user_id, device_id, exit_node_id,
//                     target_type, target_value, parent_domain)
//
// was 6-column, which let the autoupdater accumulate one
// row per (user, device, exit, type, value) tuple PER
// PARENT_DOMAIN. Live data for emilia (B182 live-verified):
// 102 subnet rows, but only 32 unique subnets — 70+ rows
// were duplicate CIDRs with different parent_domain
// values (e.g. cdn:cloudflare:discordapp.com and
// cdn:cloudflare:discord.com both resolve to 103.21.244.0/22
// and got separate rows). The visible symptom was
// /admin/exit-nodes "mismatch: have 34, want 102" (the
// want side counts raw rows; the have side counts unique
// routes on the Tailscale client).
//
// B183 fix: drop parent_domain from the natural key. The
// natural key is (user, device, exit, type, value) —
// parent_domain is metadata, not part of what makes a rule
// unique. The autoupdater's two ON CONFLICT clauses (sync.go)
// are also updated in B183 to match the 5-column target.
//
// Dedup strategy: pick the "winner" row per (user, device,
// exit, type, value) natural key. Prefer:
//   1. cdn: prefixed parent_domain (more informative —
//      tells the operator which CDN provides the route)
//   2. most recent id (highest id wins) as a tiebreaker
// All other rows with the same natural key are DELETEd.
//
// The migration is idempotent (IF EXISTS / DROP IF EXISTS
// guards). The new index is created with the same name
// (`device_rules_natural_key_uniq`) so any code that
// references it (sync.go's ON CONFLICT) doesn't need to
// change its index name — only the column list.
//
// B183 contract test: see scripts/check_b183.sh.
func migrateV060PG(d *sql.DB) error {
	stmts := []string{
		// Step 1: dedup existing rows by natural key. The
		// ORDER BY picks the winner — cdn: prefix first
		// (most informative), then most recent id.
		// The DELETE removes all losers (rn > 1).
		`DELETE FROM device_rules
		 WHERE id IN (
		   SELECT id FROM (
		     SELECT id,
		       ROW_NUMBER() OVER (
		         PARTITION BY user_id, device_id, exit_node_id, target_type, target_value
		         ORDER BY
		           CASE WHEN parent_domain LIKE 'cdn:%' THEN 0 ELSE 1 END,
		           id DESC
		       ) AS rn
		     FROM device_rules
		   ) ranked
		   WHERE rn > 1
		 )`,
		// Step 2: drop the old 6-column index
		`DROP INDEX IF EXISTS device_rules_natural_key_uniq`,
		// Step 3: create the new 5-column index (without
		// parent_domain). Same name so ON CONFLICT clauses
		// can target it by name if needed.
		`CREATE UNIQUE INDEX IF NOT EXISTS device_rules_natural_key_uniq
			ON device_rules(user_id, device_id, exit_node_id, target_type, target_value)`,
	}
	for _, s := range stmts {
		if _, err := d.Exec(s); err != nil {
			return fmt.Errorf("v0.60 device_rules natural-key drop parent_domain: %w", err)
		}
	}
	return nil
}

// migrateV061PG — v1.5.2 (B188) — backfill legacy
// tag:exit-<hostname> exit-node-pref rows to the
// canonical tag:dev-infra-<hostname> form, and
// re-enable the per-row pinning that the v0.28.5
// backfill missed.
//
// The original v0.28.5 migration (migrateV047PG)
// was supposed to set via_enabled=1 on every
// pre-existing row so the user's existing pref
// continued to pin the device to the chosen
// exit-node after the opt-in/via_enabled column
// was introduced. It guards on "freshlyAdded" —
// only runs the UPDATE if the column didn't
// pre-exist. In production the column pre-existed
// (likely from a manual ALTER in a prior hotfix),
// so the freshlyAdded check returned false and
// the UPDATE was skipped. Result: every pref row
// shipped with via_enabled=0, and the per-device
// grant in headscale is NEVER emitted with via=.
// The pref is decorative only — the user must
// pick the exit-node manually in Tailscale.
//
// This migration has two parts:
//
// 1. Tag backfill. Walk every row in
//    user_exit_node_prefs + device_exit_node_prefs
//    whose exit_node_tag matches the legacy
//    "tag:exit-<hostname>" form. For each, look up
//    the matching node_owner_map row and replace
//    exit_node_tag with the canonical tag. Rows
//    with no match are LEFT ALONE (with a NOTICEs
//    in the migration log) so the operator can
//    decide whether to clean them up by hand.
//
// 2. Re-enable via pinning. The original intent of
//    v0.28.5 was to set via_enabled=1 for every
//    pre-existing row so the user's intent
//    (pinned exit-node) was preserved through the
//    opt-in migration. We do that here, but ONLY
//    for rows whose exit_node_tag points at a
//    real headscale tag (i.e. starts with
//    "tag:dev-infra-"). A row pointing at a
//    ghost tag (e.g. tag:exit-emilia that the
//    tag backfill couldn't resolve) stays
//    via_enabled=0 — we don't want headscale to
//    reject the policy on a missing tag.
//
// The migration is idempotent: re-running it is a
// no-op (the LIKE 'tag:exit-%' WHERE clause
// matches nothing on the second run; the
// via_enabled=1 UPDATE is idempotent for already-
// pinned rows).
//
// 2026-08-26: v1.5.2 (B188).
func migrateV061PG(d *sql.DB) error {
	// Step 1: user_exit_node_prefs backfill.
	// We can't use a simple JOIN+UPDATE in PG (UPDATE
	// ... FROM is allowed, but the read-side aliasing
	// for the tag rewrite is more readable as two
	// SELECTs). Walk every legacy row, compute the
	// canonical tag, and UPDATE if the lookup
	// succeeded. Rows where the hostname doesn't
	// resolve to a node_owner_map entry are skipped
	// (they keep the legacy tag; the operator can
	// clean up via SQL).
	if _, err := d.Exec(`
		UPDATE user_exit_node_prefs p
		   SET exit_node_tag = n.tag
		  FROM node_owner_map n
		 WHERE p.exit_node_tag LIKE 'tag:exit-%'
		   AND LOWER(SUBSTRING(p.exit_node_tag FROM 10)) = LOWER(n.hostname)
		   AND p.exit_node_tag <> n.tag
	`); err != nil {
		return fmt.Errorf("v0.61 user_exit_node_prefs tag backfill: %w", err)
	}
	// Step 2: device_exit_node_prefs backfill (same
	// logic, different table).
	if _, err := d.Exec(`
		UPDATE device_exit_node_prefs p
		   SET exit_node_tag = n.tag
		  FROM node_owner_map n
		 WHERE p.exit_node_tag LIKE 'tag:exit-%'
		   AND LOWER(SUBSTRING(p.exit_node_tag FROM 10)) = LOWER(n.hostname)
		   AND p.exit_node_tag <> n.tag
	`); err != nil {
		return fmt.Errorf("v0.61 device_exit_node_prefs tag backfill: %w", err)
	}
	// Step 3: re-enable via pinning for rows whose
	// tag is a real headscale tag (tag:dev-infra-*
	// is the post-B118 convention; tag:exit-node is
	// the static catch-all that doesn't need via
	// because it's not a per-host pin).
	//
	// Only flip rows that:
	//   - currently have via_enabled=0 (don't
	//     disturb rows the operator explicitly
	//     opted out of post-B188)
	//   - point at a real headscale tag (the
	//     policy parser will reject any other
	//     form, so we leave them un-pinned)
	if _, err := d.Exec(`
		UPDATE user_exit_node_prefs
		   SET via_enabled = 1
		 WHERE via_enabled = 0
		   AND exit_node_tag LIKE 'tag:dev-infra-%'
	`); err != nil {
		return fmt.Errorf("v0.61 user_exit_node_prefs via_enabled backfill: %w", err)
	}
	if _, err := d.Exec(`
		UPDATE device_exit_node_prefs
		   SET via_enabled = 1
		 WHERE via_enabled = 0
		   AND exit_node_tag LIKE 'tag:dev-infra-%'
	`); err != nil {
		return fmt.Errorf("v0.61 device_exit_node_prefs via_enabled backfill: %w", err)
	}
	return nil
}


// migrateV062PG — v1.5.2 (B189) — DERP health dashboard.
//
// Adds the derp_health table that caches live latency
// measurements for every known DERP server (Tailscale's
// 28 public regions + the operator's own derp_relays
// rows). The derphealth package (internal/derphealth)
// probes each server's HTTPS endpoint with a TLS
// handshake, measures TTFB, and writes results here.
//
// Columns:
//   - region_id: PK. region_id 1-28 = Tailscale's
//     public regions. region_id 900+ = operator's own
//     derp_relays (or the bundled Tailscale default
//     for region_id=901).
//   - is_own: 1 if this row is one of the operator's
//     own DERP servers, 0 if it's a Tailscale public.
//   - host / url: where to probe. `url` is the full
//     https://...; `host` is the bare hostname used
//     for the latency probe and display.
//   - region_code / region_name / locality / country:
//     display metadata. region_code is the IATA-ish
//     code (e.g. "waw" / "hel") when Tailscale's map
//     exposes it; "" otherwise.
//   - latency_ms: the most recent probe's measured
//     TLS-handshake latency in milliseconds. NULL
//     when never probed or the last probe failed.
//   - last_check: unix epoch of the last probe attempt
//     (success or failure).
//   - healthy: 1 if the last probe returned 2xx/3xx on
//     the / endpoint; 0 on any error.
//   - last_error: empty on success, or the last probe's
//     error string. Used for the dashboard's "degraded"
//     hint without losing the last latency value (e.g.
//     if a probe fails intermittently).
//   - probes_total / probes_failed: counters for the
//     DERP health time-series. probes_failed is the
//     number of consecutive failed probes (resets to 0
//     on the first success after any failure).
//
// The table does NOT replace headscale's DERP selection
// or Tailscale's netcheck — it's an operator-facing
// observability surface. The recommended DERP (lowest
// latency among reachable own + public) is highlighted
// in the dashboard, not enforced anywhere.
//
// Idempotent: ON CONFLICT (region_id) DO UPDATE so
// re-probes just refresh the latency + last_check
// columns.
func migrateV062PG(d *sql.DB) error {
	if _, err := d.Exec(`
		CREATE TABLE IF NOT EXISTS derp_health (
			region_id     INTEGER PRIMARY KEY,
			is_own        INTEGER NOT NULL DEFAULT 0,
			host          TEXT    NOT NULL DEFAULT '',
			url           TEXT    NOT NULL DEFAULT '',
			region_code   TEXT    NOT NULL DEFAULT '',
			region_name   TEXT    NOT NULL DEFAULT '',
			locality      TEXT    NOT NULL DEFAULT '',
			country       TEXT    NOT NULL DEFAULT '',
			latency_ms    INTEGER,
			last_check    INTEGER NOT NULL DEFAULT 0,
			healthy       INTEGER NOT NULL DEFAULT 0,
			last_error    TEXT    NOT NULL DEFAULT '',
			probes_total  INTEGER NOT NULL DEFAULT 0,
			probes_failed INTEGER NOT NULL DEFAULT 0
		)
	`); err != nil {
		return fmt.Errorf("v0.62 derp_health table: %w", err)
	}
	return nil
}
