// Code generated by helper build; DO NOT EDIT.
// Returns the SQL expression for "current UNIX timestamp as integer"
// for the current backend. SQLite uses strftime; PostgreSQL uses
// EXTRACT(EPOCH FROM now()).
//
// Two variants below, picked at compile time via build tag:
//   - now_unix_sqlite.go   (default, no tag)
//   - now_unix_postgres.go (`//go:build postgres`)
package db

func nowUnixSQL() string {
	return nowUnix
}
