// internal/db/now_unix.go — the "current UNIX timestamp" SQL fragment.
//
// 2026-09-18: this is now a REAL dialect branch. Pre-fix it was a
// generated wrapper ("Code generated by helper build; DO NOT EDIT")
// that unconditionally returned the PostgreSQL expression, a leftover
// from the v1.3.0 PG-only era that v1.5.4 never re-forked. On SQLite the
// returned SQL is a hard error, and because the fragment is spliced into
// a dozen write paths, essentially every timestamped write failed there.
//
//	  - PostgreSQL: EXTRACT(EPOCH FROM now())::bigint
//	  - SQLite:     strftime('%s','now')
//
// Note the asymmetry that made this so easy to miss: PostgreSQL ALSO
// works with strftime() because migrations_pg.go:965 installs a
// strftime(format text, ts text) compatibility function, so a SQLite-ism
// in a shared file is silently fine on PG. The reverse is not true —
// SQLite has no EXTRACT() and no ::bigint cast.
package db

func nowUnixSQL() string {
	if ActiveDialect() == DialectSQLite {
		return "strftime('%s','now')"
	}
	return nowUnix
}

// NowUnixSQL is the public mirror of nowUnixSQL for callers outside the
// db package (backup/config.go, telegram/commands_phase3.go,
// nodeownership/auto.go).
//
// History: added 2026-08-05 (v0.33.1.12) so the per-backend placeholder
// fix could also swap strftime() for the PG equivalent in one place.
// That intent was lost when the shim was generated PG-only; it is
// restored here.
func NowUnixSQL() string { return nowUnixSQL() }
