// Code generated by helper build; DO NOT EDIT.
// Helpers that dispatch the per-backend `INSERT OR IGNORE` syntax.
// As of v1.3.0, skygate is PG-only; the only supported variant is
// the `INSERT ... ON CONFLICT (<cols>) DO NOTHING` form. The
// `INSERT OR IGNORE` form (pre-v1.3.0 SQLite) is no longer used.
//
// The two public helpers — OnConflictDoNothing + InsertIgnorePrefix —
// remain (with the same signatures) so call sites in
// headscale_version/monitor.go and invite/bridge.go can keep
// their single-form code path. The implementation lives in
// on_conflict_postgres.go (no build tag, always compiled as of
// v1.3.0).
package db

func onConflictDoNothing(cols string) string {
	return onConflict(cols)
}

func insertIgnorePrefix() string {
	return insertIgnoreVerb()
}

// OnConflictDoNothing is the public mirror of
// onConflictDoNothing, used by callers outside the db
// package (e.g. headscale_version/monitor.go's
// saveHeadscaleRelease + invite/bridge.go's subnet.Grant
// path which need to dispatch `INSERT OR IGNORE` between
// SQLite (bare) and PG (ON CONFLICT(<cols>) DO NOTHING)
// without forking the caller). Same pattern as
// db.PlaceholdersList / db.NowUnixSQL.
func OnConflictDoNothing(cols string) string { return onConflictDoNothing(cols) }

// InsertIgnorePrefix is the public mirror of
// insertIgnorePrefix — returns `INSERT OR IGNORE` for
// SQLite (the canonical SQLite syntax) and `INSERT` for
// PG (which needs the `ON CONFLICT(...) DO NOTHING`
// suffix from OnConflictDoNothing instead). Callers that
// want a single cross-backend idempotent INSERT
// statement splice the result between the leading
// whitespace and `INTO <table>`:
//
//	` ` + db.InsertIgnorePrefix() + ` INTO foo (...) VALUES (...)` + db.OnConflictDoNothing(...)
func InsertIgnorePrefix() string { return insertIgnorePrefix() }
