// Code generated by helper build; DO NOT EDIT.
// Helpers that dispatch the SQLite `INSERT OR IGNORE` syntax
// to the cross-backend `INSERT ... ON CONFLICT (<cols>) DO
// NOTHING` equivalent on PostgreSQL.
//
// SQLite uses the bare `INSERT OR IGNORE` keyword on the
// INSERT itself; PostgreSQL needs a plain `INSERT` plus the
// explicit `ON CONFLICT` clause as a suffix. The two helpers
// below let the call site stay in one place:
//
//	` ` + db.InsertIgnorePrefix() + ` INTO <table> (<cols>)
//		VALUES (<placeholders>)` + db.OnConflictDoNothing(<cols>)
//
// On SQLite:  `INSERT OR IGNORE INTO ...` (suffix is "").
// On PG:      `INSERT INTO ...` (suffix is "ON CONFLICT (cols) DO NOTHING").
//
// Two variants below, picked at compile time via build tag:
//   - on_conflict_sqlite.go   (default, no tag)
//   - on_conflict_postgres.go (`//go:build postgres`)
//
// 2026-08-05 v0.33.1.12 — added so the existing
// `INSERT OR IGNORE` sites in headscale_version/monitor.go
// and invite/bridge.go can dispatch to the PG form
// without forking the call site.
package db

func onConflictDoNothing(cols string) string {
	return onConflict(cols)
}

func insertIgnorePrefix() string {
	return insertIgnoreVerb()
}

// OnConflictDoNothing is the public mirror of
// onConflictDoNothing, used by callers outside the db
// package (e.g. headscale_version/monitor.go's
// saveHeadscaleRelease + invite/bridge.go's subnet.Grant
// path which need to dispatch `INSERT OR IGNORE` between
// SQLite (bare) and PG (ON CONFLICT(<cols>) DO NOTHING)
// without forking the caller). Same pattern as
// db.PlaceholdersList / db.NowUnixSQL.
func OnConflictDoNothing(cols string) string { return onConflictDoNothing(cols) }

// InsertIgnorePrefix is the public mirror of
// insertIgnorePrefix — returns `INSERT OR IGNORE` for
// SQLite (the canonical SQLite syntax) and `INSERT` for
// PG (which needs the `ON CONFLICT(...) DO NOTHING`
// suffix from OnConflictDoNothing instead). Callers that
// want a single cross-backend idempotent INSERT
// statement splice the result between the leading
// whitespace and `INTO <table>`:
//
//	` ` + db.InsertIgnorePrefix() + ` INTO foo (...) VALUES (...)` + db.OnConflictDoNothing(...)
func InsertIgnorePrefix() string { return insertIgnorePrefix() }
