// Code generated by helper build; DO NOT EDIT.
// Returns the comma-joined placeholder list for n parameters
// for the current backend. SQLite uses one "?" per parameter
// (supported by every database/sql driver that supports
// positional parameters). PostgreSQL with the pgx stdlib
// uses $1, $2, ... — passing "?" through to PostgreSQL
// results in "syntax error at or near ','" because pgx
// doesn't auto-convert "?" to "$N" (unlike the lib/pq
// driver which DID auto-convert via NamedArg).
//
// Two variants below, picked at compile time via build tag:
//   - placeholders_sqlite.go   (default, no tag)
//   - placeholders_postgres.go (`//go:build postgres`)
package db

func placeholdersList(n int) string {
	return placeholders(n)
}
